Description of findmemberof
Home > mml > findmemberof.m
findmemberof
PURPOSE
FINDMEMBEROF - Finds all family members
SYNOPSIS
function FamilyName = findmemberof(MemberString, Field)
DESCRIPTION
FINDMEMBEROF - Finds all family members
  FamilyName = findmemberof(MemberString, Field)
  An optional Field input can be used to only look through subfields.
  FamilyNameCell = findmemberof(MemberString, Field)
  Subfield membership is usually not used.
  INPUTS
  1. MemberString - Must be a string or cell array of strings
  2. Field - Optional field
  OUPUTS
  1. FamilyName - Cell array of family name (Column cell)
                  {} if no member is found
  EXAMPLES
  1. findmemberof('Magnet')
  See Also getmemberof, ismemberof, isfamily
CROSS-REFERENCE INFORMATION
This function calls:
getfamilylist GETFAMILYLIST - Returns a list of all the family names
getmemberof GETMEMBEROF - Returns the membership information of a family (cell of strings)
This function is called by:
findrf FINDRF - Finds the RF frequency that minimizes the energy change due
getchroresp GETCHRORESP - Loads the chromaticity response vector (or matrix) for multiple sextupole families
getenergy GETENERGY - Returns the beam energy base on the bend magnet
gethbpmfamily GETHBPMFAMILY - Return the default horizontal BPM family
gethcmfamily GETHCMFAMILY - Returns the default horizontal corrector family
gettuneresp GETTUNERESP - Loads the tune response vector (or matrix) for multiple quadrupole families
getvbpmfamily GETVBPMFAMILY - Return the default vertical BPM family
getvcmfamily GETVCMFAMILY - Returns the default vertical corrector family
measchroresp MEASCHRORESP - measures the response from sextupoles to chromaticity
meastuneresp MEASTUNERESP - Measures the response from quadrupole to tune
monmags MONMAGS - Monitors all magnet power supplies and plots various statistics
quad2bpm QUAD2BPM - Returns the nearest BPM to the specified quadrupole
setchro SETCHRO - Measures then sets the chromaticity
setgolden SETGOLDEN - Set the golden values
setoffset SETOFFSET - Set the offset
settune SETTUNE - Set the tune
stepchro STEPCHRO - Incremental change in the chromaticity (Delta Tune / Delta RF)
steptune STEPTUNE - Step the tune
SOURCE CODE
function  FamilyName = findmemberof(MemberString, Field)
%FINDMEMBEROF - Finds all family members
%  FamilyName = findmemberof(MemberString, Field)
%
%  An optional Field input can be used to only look through subfields.
%  FamilyNameCell = findmemberof(MemberString, Field)
%  Subfield membership is usually not used.
%
%  INPUTS
%  1. MemberString - Must be a string or cell array of strings
%  2. Field - Optional field
%
%  OUPUTS
%  1. FamilyName - Cell array of family name (Column cell)
%                  {} if no member is found
%
%  EXAMPLES
%  1. findmemberof('Magnet')
%
%  See Also getmemberof, ismemberof, isfamily
%
% Written by Gregory J. Portmann
%
if nargin < 1
    error('1 inputs required');
end
FamilyName = {};
FamilyList = getfamilylist;
if nargin >= 2
    % Look for subfield membership
    for i = 1:size(FamilyList,1)
        Family = deblank(FamilyList(i,:));
        if iscell(MemberString)
            Hit = zeros(length(MemberString),1);
            for j = 1:length(MemberString)
                if any(strcmpi(MemberString{j}, getmemberof(Family, Field)))
                    Hit(j) = 1;
                end
            end
            if all(Hit)
                FamilyName = [FamilyName; {Family}];
            end
        else
            if any(strcmpi(MemberString, getmemberof(Family, Field)))
                FamilyName = [FamilyName; {Family}];
            end
        end
    end
else
    % Look for main field membership
    for i = 1:size(FamilyList,1)
        Family = deblank(FamilyList(i,:));
        if iscell(MemberString)
            Hit = zeros(length(MemberString),1);
            for j = 1:length(MemberString)
                if any(strcmpi(MemberString{j}, getmemberof(Family)))
                    Hit(j) = 1;
                end
            end
            if all(Hit)
                FamilyName = [FamilyName; {Family}];
            end
        else
            if any(strcmpi(MemberString, getmemberof(Family)))
                FamilyName = [FamilyName; {Family}];
            end
        end
    end
end