Description of getenergy
Home > mml > getenergy.m
getenergy
PURPOSE
GETENERGY - Returns the beam energy base on the bend magnet
SYNOPSIS
function [Energy, HCMEnergy] = getenergy(varargin)
DESCRIPTION
GETENERGY - Returns the beam energy base on the bend magnet
  [Energy, HCMEnergy] = getenergy(Keyword)
  Keyword can be:
  'Production'         - Energy of the production lattice
  'Injection'          - Energy of the injection lattice
  'Model' or Simulator - Energy based on the model bend magnet (bend2gev('Model'))
  'Online'             - Energy based on the online bend magnet (bend2gev('Online'))
  'Present'            - Energy based on the present bend magnet mode (bend2gev)   {Default}
  OUTPUTS
  1. Energy - Main storage ring energy (usually based on the BEND magnet) [GeV]
  2. HCMEnergy - Energy change due to all the horizontal corrector magnets [dE/E]
                 Algorithm:  dE/E = sum(-HCM * DxHCM / getmcf / L)
  See also plotcm
CROSS-REFERENCE INFORMATION
This function calls:
findmemberof FINDMEMBEROF - Finds all family members
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
gethcmfamily GETHCMFAMILY - Returns the default horizontal corrector family
getinjectionlattice GETINJECTIONLATTICE - Get data from the production lattice file
getmcf GETMCF - Returns the momentum compaction factor (MCF) stored in the AD or the model
getproductionlattice GETPRODUCTIONLATTICE - Read the Golden lattice from file GoldenLattice
getsp GETSP - Gets setpoint channels
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
This function is called by:
getbrho GETBRHO - Calculations of the beam rigidity
getrespmat GETRESPMAT - Get response matrix data from a file
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
measchro MEASCHRO - measures the chromaticity function emperically
measdisp MEASDISP - Measures the dispersion function
measidfftable FFGETTBL - Measures an insertion device feed forward table for the vertical gap
measrespmat MEASRESPMAT - Measure a response matrix
physics2hw PHYSICS2HW - Converts from 'Physics' units to 'Hardware' units
setenergy SETENERGY - Sets the storage ring energy (GeV) by ramping all lattice magnets
SUBFUNCTIONS
function HCMEnergy = gethcmenergylocal(HCMStruct);
SOURCE CODE
function [Energy, HCMEnergy] = getenergy(varargin)
%GETENERGY - Returns the beam energy base on the bend magnet
%  [Energy, HCMEnergy] = getenergy(Keyword)
%
%  Keyword can be:
%  'Production'         - Energy of the production lattice
%  'Injection'          - Energy of the injection lattice
%  'Model' or Simulator - Energy based on the model bend magnet (bend2gev('Model'))
%  'Online'             - Energy based on the online bend magnet (bend2gev('Online'))
%  'Present'            - Energy based on the present bend magnet mode (bend2gev)   {Default}
%
%  OUTPUTS
%  1. Energy - Main storage ring energy (usually based on the BEND magnet) [GeV]
%  2. HCMEnergy - Energy change due to all the horizontal corrector magnets [dE/E]
%                 Algorithm:  dE/E = sum(-HCM * DxHCM / getmcf / L)
%
%  See also plotcm
%
%  Written by Gregory J. Portmann
for i = length(varargin):-1:1
    if strcmpi(varargin{i},'Production')
        Energy = getfamilydata('Energy');
        if nargout >= 2
            FamilyCell = findmemberof('HCM');
            if isempty(FamilyCell)
                Family = gethcmfamily;
            else
                Family = FamilyCell{1};
            end
            SP = getproductionlattice;
            HCMEnergy = gethcmenergylocal(SP.(Family).Setpoint);
        end
        return
    elseif strcmpi(varargin{i},'Injection')
        Energy = getfamilydata('InjectionEnergy');
        if nargout >= 2
            FamilyCell = findmemberof('HCM');
            if isempty(FamilyCell)
                Family = gethcmfamily;
            else
                Family = FamilyCell{1};
            end
            SP = getinjectionlattice;
            HCMEnergy = gethcmenergylocal(SP.(Family).Setpoint);
        end
        return
    elseif strcmpi(varargin{i},'Present')
        Energy = bend2gev;
        if nargout >= 2
            HCMEnergy = gethcmenergylocal(SP.(Family));
        end
        return
    elseif strcmpi(varargin{i},'Model') | strcmpi(varargin{i},'Simulator')
        Energy = bend2gev('Model');
        if nargout >= 2
            FamilyCell = findmemberof('HCM');
            if isempty(FamilyCell)
                Family = gethcmfamily;
            else
                Family = FamilyCell{1};
            end
            HCMEnergy = gethcmenergylocal(getsp(Family, 'Model', 'Struct'));
        end
        return
    elseif strcmpi(varargin{i},'Online')
        Energy = bend2gev('Online');
        if nargout >= 2
            FamilyCell = findmemberof('HCM');
            if isempty(FamilyCell)
                Family = gethcmfamily;
            else
                Family = FamilyCell{1};
            end
            HCMEnergy = gethcmenergylocal(getsp(Family, 'Online', 'Struct'));
        end
        return
    end
end
% Default
Energy = bend2gev;
%Energy = getfamilydata('Energy');
Energy = Energy(1);
if nargout >= 2
    HCMEnergy = gethcmenergylocal;
end
function HCMEnergy = gethcmenergylocal(HCMStruct);
if nargin == 0
    % Get the energy change of the horizontal correctors
    FamilyCell = findmemberof('HCM');
    if isempty(FamilyCell)
        Family = gethcmfamily;
    else
        Family = FamilyCell{1};
    end
    HCMStruct = getsp(Family, 'Struct');
end
% Compute the energy change due to the correctors
L = getfamilydata('Circumference');
HCM = hw2physics(HCMStruct);
HCM = HCM.Data;
[DxHCM, DyHCM] = modeldisp([], HCMStruct.FamilyName, HCMStruct.DeviceList, 'Physics');
HCMEnergyChange = -1 *HCM.*DxHCM / getmcf / L;
HCMEnergy = sum(HCMEnergyChange);