Description of getmcf
Home > mml > getmcf.m
getmcf
PURPOSE
GETMCF - Returns the momentum compaction factor (MCF) stored in the AD or the model
SYNOPSIS
function Alpha = getmcf(ModelString)
DESCRIPTION
GETMCF - Returns the momentum compaction factor (MCF) stored in the AD or the model
  Alpha = getmcf               % returns getfamilydata('MCF')
  Alpha = getmcf('Model')      % returns mcf(THERING)
 INPUTS
 1. ModelString - optional 'Model' or 'Simulator' Calls modelmcf
                - default online
 OUTPUTS
 1. Alpha - Momen compaction factor
 NOTES
 1. Make sure the model is up to date before calling.
 See Also getbrho, getenergy, modelmcf, makephysdata
CROSS-REFERENCE INFORMATION
This function calls:
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
This function is called by:
findrf1 FINDRF1 - Finds the RF frequency that minimizes the horizonal dispersion
getenergy GETENERGY - Returns the beam energy base on the bend magnet
getgolden GETGOLDEN - Returns the golden values for a family
measchro MEASCHRO - measures the chromaticity function emperically
measdisp MEASDISP - Measures the dispersion function
orbitcorrectionmethods ORBITCORRECTIONMETHODS - Some the orbit correction methods used on light sources
plotcm PLOTCM - Plots the horizontal and vertical corrector magnet families and
rmdisp RMDISP - Removes the portion of the orbit that correlates with the dispersion
setchro SETCHRO - Measures then sets the chromaticity
SOURCE CODE
function Alpha = getmcf(ModelString)
%GETMCF - Returns the momentum compaction factor (MCF) stored in the AD or the model
%  Alpha = getmcf               % returns getfamilydata('MCF')
%  Alpha = getmcf('Model')      % returns mcf(THERING)
%
% INPUTS
% 1. ModelString - optional 'Model' or 'Simulator' Calls modelmcf
%                - default online
%
% OUTPUTS
% 1. Alpha - Momen compaction factor
%
% NOTES
% 1. Make sure the model is up to date before calling.
%
% See Also getbrho, getenergy, modelmcf, makephysdata
%
%  Written by Gregory J. Portmann
if nargin < 1
    ModelString = '';
end
if strcmpi(ModelString,'model') | strcmpi(ModelString,'simulator')
    % Get from the model
    Alpha = modelmcf;
else
    Alpha = getfamilydata('MCF');
%     try
%         % Get from the model
%         Alpha = modelmcf;
%     catch
%         Alpha = getfamilydata('MCF');
%         fprintf('   modelmcf failing so MCF = %f (getfamilydata(''MCF'')) is being used.\n', Alpha);
%     end
end