Description of getnumberofsectors
Home > mml > getnumberofsectors.m
getnumberofsectors
PURPOSE
GETNUMBEROFSECTORS - Number of sectors in the lattice
SYNOPSIS
function N = getnumberofsectors
DESCRIPTION
GETNUMBEROFSECTORS - Number of sectors in the lattice
  N = getnumberofsectors
CROSS-REFERENCE INFORMATION
This function calls:
family2dev FAMILY2DEV - Return the device list for a family
gethbpmfamily GETHBPMFAMILY - Return the default horizontal BPM family
gethcmfamily GETHCMFAMILY - Returns the default horizontal corrector family
This function is called by:
SOURCE CODE
function N = getnumberofsectors
%GETNUMBEROFSECTORS - Number of sectors in the lattice
%  N = getnumberofsectors
%
% Written By Gregory J. Portmann
% Get the sectors from the device list.
% Guess at a few family names.
List = family2dev(gethcmfamily);
if isempty(List)
    List = family2dev(gethbpmfamily);
end
if isempty(List)
    List = family2dev('BEND');
end
if isempty(List)
    N = 1;
else
    N = max(List(:,1));
end