Description of getpv
Home > mml > getpv.m
getpv
PURPOSE
GETPV - Returns a variable from the online system or the model
SYNOPSIS
function [AM, tout, DataTime, ErrorFlag] = getpv(varargin)
DESCRIPTION
GETPV - Returns a variable from the online system or the model
  FamilyName/DeviceList Method
  [AM, tout, DataTime] = getpv(Family, Field, DeviceList, t, FreshDataFlag, TimeOutPeriod)
  Data Structure
  [AM, tout, DataTime] = getpv(DataStructure, t, FreshDataFlag, TimeOutPeriod)
  TangoName or ChannelName Method
  [AM, tout, DataTime, ErrorFlag] = getpv(TangoName, t, FreshDataFlag, TimeOutPeriod)
  CommonName Method (Family can be '' to search all families, Field is optional)
  [AM, tout, DataTime] = getpv(CommonName, Field, t, FreshDataFlag, TimeOutPeriod)
  [AM, tout, DataTime] = getpv(Family, Field, CommonName, t, FreshDataFlag, TimeOutPeriod)
  INPUTS
  1. Family - Family Name
              Data Structure
              Channel Name
              TangoName
              Accelerator Object
              For CommonNames, Family=[] searches all families
              (or Cell Array of inputs)
  2. Field - Subfield name of an accelerator family ('Monitor', 'Setpoint', etc)
             {Default: 'Monitor' or '' or ChannelName method}
             (For non-Family subfields, Field is added as .Field, see Note #8 below for more information.)
  3. DeviceList - [Sector Device #] or [element #] list {Default or empty list: Entire family}
                  Note: if input 1 is a cell array then DeviceList must be a cell array
     CommonName - Common name can replace a DeviceList (scalar or vector outputs)
  4. t - Time vector of when to start taking data (t can not be a cell) {Default: 0}
  5. FreshDataFlag -  0   -> Return after first measurement {Default}
                     else -> Return after FreshDataFlag number of new measurements have been read
                     Ie, getpv('BPMx',[1 1],0,2) measures the orbit then continues to read the orbit
                         until 2 new orbits have been measured and returns the last measurement.
                     Note: 1. t can only be a scalar when using the FreshDataFlag.
                           2. FreshDataFlag cannot be used with 'Matrix' data types.
  6. TimeOutPeriod - Time-out period when waiting for fresh data {Default: 10 seconds}
  7. 'Struct'  - Return a data structure {Default for data structure inputs}
     'Numeric' - Return numeric outputs  {Default for non-data structure inputs}
     'Object'  - Return a accelerator object (AccObj)
  8. Units flag overrides
     'Physics'  - Use physics  units
     'Hardware' - Use hardware units
  9. Mode flag overrides
     'Online' - Get data online
     'Model'  - get data on the model
     'Manual' - Get data manually
  10. 'Double' - The output will be a double {Default}
      'String' - The output will be a string
  OUTPUTS
  1. AM   - Monitor values (Column vector or matrix where each column is a data point in time)
  2. tout - Time when measurement was completed according to the computer time (Matlab time) (row vector)
            tout-t is the time it took to make the measurement.  diff(t) can be arbitarily small, but tout will
            report the actual completion time.
  3. DataTime - Time when the data was measured (as report by the hardware)
                Time since 00:00:00, Jan 1, 1970 in days (in the present time zone)
                Units are in Matlab "serial day number" format (days) to be compatible with
                timing functions like datevec, datenum, datetick, etc.
                For exemple, [d,t,datatime] = getam('BPMx',[],0:.5:10);
                            plot(datatime, d); datetick x
                When using the model, the datatime is the same a the computer time (Matlab time).
  NOTES
  1. The output will be a data structure if the word 'struct' appears somewhere on the input line
     or if the input is a data structure and 'numeric' is not on the input line.
  2. For data structure inputs:
     Family     - DataStructure.FamilyName (This field must exist)
     Field      - DataStructure.Field      (Field can be overridden on the input line)
     DeviceList - DataStructure.DeviceList (DeviceList can be overridden on the input line)
     Units      - DataStructure.Units      (Units can be overridden on the input line)
     (The Mode field is ignored!)
  3. For data structure outputs:
     TimeStamp  - Time (Matlab clock) at the start of the function
     tout       - Delta time vector at the end of each measurement (relative to TimeStamp)
  4. diff(t) should not be too small.  If the desired time to collect the data is too
     short then the data collecting will not be able to keep up.  Always check tout.
     (t - tout) is the time it took to collect the data on each iteration.
  5. An easy way to averaged 10 monitors is:
     PVmean = mean(getpv(Family,DeviceList,0:.5:4.5)')';   % .5 second between measurements
  6. Channel name method is always Online!
  7. It is often useful to measure the update rate of a set of channel by using a very
     small time between measurements.
     For exmple, [d, tout] = getpv('BPMx', 'Monitor', [], 0:eps:100*eps);
                 plot(tout(1:end-1), 1./diff(tout),'.-'); % Point-wise data rate
                 If the update rate of the hardware is slower then the control system, then
                 hardware data rate can be visually inspected by plotting,
                 plot(tout, d,'.-');
  8. For cell array inputs:
     a. Input 1 defines the size of all cells
     b. All of the cell array inputs must be the same size
     c. Field does not have to be a cell array but DeviceList does (if they exist)
     d. t, FreshDataFlag, TimeOutPeriod can not be cell arrays
     e. Waveforms do not work with cell arrays.
  8. The Field input can be used for getting the "dot" EPICS field.  For instance, at the ALS
     getpv('BPMx','SCAN',[1 2],'String') will return SR01S___IBPM2X_AM02.SCAN as a string.
     (Note: at Spear ':' is used instead of '.')
  10. Error flaga are not used at the moment since all errors cause a Matlab error.
      Use try;catch statements to catch errors.
  12. If say Golden is a software field in the MML structure in the BPMx family, then
      getpv('BPMx','Golden', DeviceList) will return the data in that field.
  See also getam, getsp, setpv, steppv
  Written by Greg Portmann
CROSS-REFERENCE INFORMATION
This function calls:
common2dev COMMON2DEV - Converts a common name to a device list
elem2dev ELEM2DEV - Converts a device list to an element list
family2dev FAMILY2DEV - Return the device list for a family
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getmode GETMODE - Returns the present family mode ('Online', 'Simulator', 'Manual', 'Special', etc)
getpv GETPV - Returns a variable from the online system or the model
getrf GETRF - Gets the RF frequency
getunits GETUNITS - Return the present family units and units string
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
isfamily ISFAMILY - True for family names
physics2hw PHYSICS2HW - Converts from 'Physics' units to 'Hardware' units
This function is called by:
getam GETAM - Gets monitor channels
getdcct GETDCCT - returns the beam current
getmachineconfig GETMACHINECONFIG - Returns or saves to file the present storage ring setpoints and monitors
getpv GETPV - Returns a variable from the online system or the model
getramprate GETRAMPRATE - Returns the ramp rate for a family
getrf GETRF - Gets the RF frequency
getrunflag GETRUNFLAG - Returns position if the device is in the process of changing a setpoint
getsp GETSP - Gets setpoint channels
gettune GETTUNE - Returns the betatron tunes
getx GETX - Returns the horizontal orbit
gety GETY - Returns the vertical orbit
measidfftable FFGETTBL - Measures an insertion device feed forward table for the vertical gap
plotwaveform PJ BOussina waveform loader September 11, 2006
rmgolden RMGOLDEN - Remove the golden values for data set
rmoffset RMOFFSET - Remove the offset values for data set
setorbit SETORBIT - Orbit correction function
setpv SETPV - Setpoint change of the online system or model
SUBFUNCTIONS
function [AM, tout, DataTime, DeviceList, ErrorFlag] = getbycommonname(CommonNames, Field, t, t0, FreshDataFlag, TimeOutPeriod, varargin)
function [AM, tout, DataTime, ErrorFlag] = local_getbyname(ChannelName, OutputDataType, N, t, FreshDataFlag, TimeOutPeriod)
function [AM, tout, DataTime, ErrorFlag, DeviceIndex] = local_getpv(AO, Field, DeviceList, OutputDataType, t, FreshDataFlag, TimeOutPeriod)
SOURCE CODE
function [AM, tout, DataTime, ErrorFlag] = getpv(varargin)
%GETPV - Returns a variable from the online system or the model
%
%  FamilyName/DeviceList Method
%  [AM, tout, DataTime] = getpv(Family, Field, DeviceList, t, FreshDataFlag, TimeOutPeriod)
%
%  Data Structure
%  [AM, tout, DataTime] = getpv(DataStructure, t, FreshDataFlag, TimeOutPeriod)
%
%  TangoName or ChannelName Method
%  [AM, tout, DataTime, ErrorFlag] = getpv(TangoName, t, FreshDataFlag, TimeOutPeriod)
%
%  CommonName Method (Family can be '' to search all families, Field is optional)
%  [AM, tout, DataTime] = getpv(CommonName, Field, t, FreshDataFlag, TimeOutPeriod)
%  [AM, tout, DataTime] = getpv(Family, Field, CommonName, t, FreshDataFlag, TimeOutPeriod)
%
%  INPUTS
%  1. Family - Family Name
%              Data Structure
%              Channel Name
%              TangoName
%              Accelerator Object
%              For CommonNames, Family=[] searches all families
%              (or Cell Array of inputs)
%
%  2. Field - Subfield name of an accelerator family ('Monitor', 'Setpoint', etc)
%             {Default: 'Monitor' or '' or ChannelName method}
%             (For non-Family subfields, Field is added as .Field, see Note #8 below for more information.)
%
%  3. DeviceList - [Sector Device #] or [element #] list {Default or empty list: Entire family}
%                  Note: if input 1 is a cell array then DeviceList must be a cell array
%     CommonName - Common name can replace a DeviceList (scalar or vector outputs)
%
%  4. t - Time vector of when to start taking data (t can not be a cell) {Default: 0}
%
%  5. FreshDataFlag -  0   -> Return after first measurement {Default}
%                     else -> Return after FreshDataFlag number of new measurements have been read
%                     Ie, getpv('BPMx',[1 1],0,2) measures the orbit then continues to read the orbit
%                         until 2 new orbits have been measured and returns the last measurement.
%                     Note: 1. t can only be a scalar when using the FreshDataFlag.
%                           2. FreshDataFlag cannot be used with 'Matrix' data types.
%
%  6. TimeOutPeriod - Time-out period when waiting for fresh data {Default: 10 seconds}
%
%  7. 'Struct'  - Return a data structure {Default for data structure inputs}
%     'Numeric' - Return numeric outputs  {Default for non-data structure inputs}
%     'Object'  - Return a accelerator object (AccObj)
%
%  8. Units flag overrides
%     'Physics'  - Use physics  units
%     'Hardware' - Use hardware units
%
%  9. Mode flag overrides
%     'Online' - Get data online
%     'Model'  - get data on the model
%     'Manual' - Get data manually
%
%  10. 'Double' - The output will be a double {Default}
%      'String' - The output will be a string
%
%
%  OUTPUTS
%  1. AM   - Monitor values (Column vector or matrix where each column is a data point in time)
%
%  2. tout - Time when measurement was completed according to the computer time (Matlab time) (row vector)
%            tout-t is the time it took to make the measurement.  diff(t) can be arbitarily small, but tout will
%            report the actual completion time.
%
%  3. DataTime - Time when the data was measured (as report by the hardware)
%                Time since 00:00:00, Jan 1, 1970 in days (in the present time zone)
%                Units are in Matlab "serial day number" format (days) to be compatible with
%                timing functions like datevec, datenum, datetick, etc.
%                For exemple, [d,t,datatime] = getam('BPMx',[],0:.5:10);
%                            plot(datatime, d); datetick x
%                When using the model, the datatime is the same a the computer time (Matlab time).
%
%  NOTES
%  1. The output will be a data structure if the word 'struct' appears somewhere on the input line
%     or if the input is a data structure and 'numeric' is not on the input line.
%
%  2. For data structure inputs:
%     Family     - DataStructure.FamilyName (This field must exist)
%     Field      - DataStructure.Field      (Field can be overridden on the input line)
%     DeviceList - DataStructure.DeviceList (DeviceList can be overridden on the input line)
%     Units      - DataStructure.Units      (Units can be overridden on the input line)
%     (The Mode field is ignored!)
%
%  3. For data structure outputs:
%     TimeStamp  - Time (Matlab clock) at the start of the function
%     tout       - Delta time vector at the end of each measurement (relative to TimeStamp)
%
%  4. diff(t) should not be too small.  If the desired time to collect the data is too
%     short then the data collecting will not be able to keep up.  Always check tout.
%     (t - tout) is the time it took to collect the data on each iteration.
%
%  5. An easy way to averaged 10 monitors is:
%     PVmean = mean(getpv(Family,DeviceList,0:.5:4.5)')';   % .5 second between measurements
%
%  6. Channel name method is always Online!
%
%  7. It is often useful to measure the update rate of a set of channel by using a very
%     small time between measurements.
%     For exmple, [d, tout] = getpv('BPMx', 'Monitor', [], 0:eps:100*eps);
%                 plot(tout(1:end-1), 1./diff(tout),'.-'); % Point-wise data rate
%                 If the update rate of the hardware is slower then the control system, then
%                 hardware data rate can be visually inspected by plotting,
%                 plot(tout, d,'.-');
%
%  8. For cell array inputs:
%     a. Input 1 defines the size of all cells
%     b. All of the cell array inputs must be the same size
%     c. Field does not have to be a cell array but DeviceList does (if they exist)
%     d. t, FreshDataFlag, TimeOutPeriod can not be cell arrays
%     e. Waveforms do not work with cell arrays.
%
%  8. The Field input can be used for getting the "dot" EPICS field.  For instance, at the ALS
%     getpv('BPMx','SCAN',[1 2],'String') will return SR01S___IBPM2X_AM02.SCAN as a string.
%     (Note: at Spear ':' is used instead of '.')
%
%  10. Error flaga are not used at the moment since all errors cause a Matlab error.
%      Use try;catch statements to catch errors.
%
%  12. If say Golden is a software field in the MML structure in the BPMx family, then
%      getpv('BPMx','Golden', DeviceList) will return the data in that field.
%
%  See also getam, getsp, setpv, steppv
%
%  Written by Greg Portmann
% Starting time
t0 = clock;
% Defaults
FieldDefault = 'Monitor';
Field = FieldDefault;
DeviceList = [];
t = 0;
FreshDataFlag = 0;
TimeOutPeriod = 10;
ErrorFlag = 0;
StructOutputFlag = 0;
NumericOutputFlag = 0;
ObjectOutputFlag = 0;
ModeFlag = '';
UnitsFlag = '';
OutputDataType = 'Double';
% Look if 'struct' or 'numeric' in on the input line
InputFlags = {};
for i = length(varargin):-1:1
    if isstruct(varargin{i})
        % Ignor structures
    elseif iscell(varargin{i})
        % Ignor cells
    elseif isa(varargin{i},'AccObj')
        AccObj1 = struct(varargin{i});
        Families = fieldnames(AccObj1);
        j = 0;
        for k = 1:length(Families)
            if ~isempty(AccObj1.(Families{k}))
                j = j + 1;
                tmpcell{j} = AccObj1.(Families{k});
            end
        end
        if length(tmpcell) == 1
            varargin{i} = tmpcell{1};
        else
            varargin{i} = tmpcell;
        end
        if ~NumericOutputFlag
            ObjectOutputFlag = 1;
            StructOutputFlag = 1;
        end
    elseif strcmpi(varargin{i},'struct')
        StructOutputFlag = 1;
        ObjectOutputFlag = 0;
        varargin(i) = [];
    elseif strcmpi(varargin{i},'numeric')
        NumericOutputFlag = 1;
        StructOutputFlag = 0;
        ObjectOutputFlag = 0;
        varargin(i) = [];
    elseif strcmpi(varargin{i},'simulator') || strcmpi(varargin{i},'model')
        ModeFlag = 'SIMULATOR';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Online')
        ModeFlag = 'Online';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Manual')
        ModeFlag = 'Manual';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Special')
        ModeFlag = 'Special';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'physics')
        UnitsFlag = 'Physics';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'hardware')
        UnitsFlag = 'Hardware';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'archive')
        % Just remove
        varargin(i) = [];
    elseif strcmpi(varargin{i},'noarchive')
        % Just remove
        varargin(i) = [];
    elseif strcmpi(varargin{i},'String')
        OutputDataType = 'String';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Double')
        OutputDataType = 'Double';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'WaveForm') || strcmpi(varargin{i},'Matrix')
        OutputDataType = 'Matrix';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Object')
        ObjectOutputFlag = 1;
        StructOutputFlag = 1;
        varargin(i) = [];
    end
end
if isempty(varargin)
    error('Must have at least one input (Family, Data structure, or Channel Name).');
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CELL OR CELL ARRAY INPUT %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if iscell(varargin{1})
    %if strcmpi(ModeFlag, 'Online') | (isempty(ModeFlag) & strcmpi(getmode(varargin{1}{1}), 'Online'))
    %     % Unfortunately the following code using channelnames is not much of a speed improvement over
    %     % interating over cell arrays (which is needed for simulator mode)
    %
    %     % Online cell arrays
    %     %
    %     % Online cell arrays are treated differently because to the desired for speed.
    %     % By loading all the channel names into one array then sending to the c-function
    %     % with the t-vector, the total time is greatly sped up.  However, using channel names
    %     % only works in online mode.  The one problem is all output have to scalars.
    %
    %
    %     % Count the number of inputs which are cells (Family or DeviceList) or strings (possibly Field)
    %     NCellOrString = 1;
    %     for i = 2:length(varargin)
    %         if ~iscell(varargin{i})
    %             if ~ischar(varargin{i})
    %                 break;
    %             else
    %                 NCellOrString = NCellOrString + 1;
    %             end
    %         else
    %             NCellOrString = NCellOrString + 1;
    %             %if length(varargin{1})~=length(varargin{NCellOrString}) | length(varargin{NCellOrString})==1
    %             %    error('When using cell, all the cells must be the same size as input 1 or be length one.');
    %             %end
    %         end
    %     end
    %
    %     % t (if it exists) should be the next input
    %     if length(varargin) >= NCellOrString+1
    %         if iscell(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be a time vector not a cell', NCellOrString+1));
    %         end
    %         if ischar(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be a time vector not a string', NCellOrString+1));
    %         end
    %         t = varargin{NCellOrString+1};
    %         varargin{NCellOrString+1} = [];
    %         if isempty(t)
    %             t = 0;
    %         end
    %     end
    %
    %     % FreshDataFlag (if it exists) should be the next input
    %     if length(varargin) >= NCellOrString+1
    %         if iscell(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be FreshDataFlag not a cell', NCellOrString+2));
    %         end
    %         if ischar(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be FreshDataFlag not a string', NCellOrString+2));
    %         end
    %         FreshDataFlag = varargin{NCellOrString+1};
    %         varargin{NCellOrString+1} = [];
    %     end
    %
    %     % TimeOutPeriod (if it exists) should be the next input
    %     if length(varargin) >= NCellOrString+1
    %         if iscell(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be TimeOutPeriod not a cell', NCellOrString+2));
    %         end
    %         if ischar(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be TimeOutPeriod not a string', NCellOrString+2));
    %         end
    %         TimeOutPeriod = varargin{NCellOrString+1};
    %         varargin{NCellOrString+1} = [];
    %     end
    %
    %     % Build the channel name matrix
    %     ChannelNames = [];
    %     for i = 1:size(varargin{1},1)
    %         for j = 1:size(varargin{1},2)
    %             if NCellOrString == 1
    %                 NewNames = family2channel(varargin{1}{i,j});
    %             elseif NCellOrString == 2
    %                 if iscell(varargin{2})
    %                     NewNames = family2channel(varargin{1}{i,j}, varargin{2}{i,j});
    %                 else
    %                     NewNames = family2channel(varargin{1}{i,j}, varargin{2});
    %                 end
    %             elseif NCellOrString == 3
    %                 if iscell(varargin{2})
    %                     NewNames = family2channel(varargin{1}{i,j}, varargin{2}{i,j}, varargin{3}{i,j});
    %                 else
    %                     NewNames = family2channel(varargin{1}{i,j}, varargin{2}, varargin{3}{i,j});
    %                 end
    %             end
    %             ChannelNames = strvcat(ChannelNames, NewNames);
    %             NameSize(i,j) = size(NewNames,1);
    %         end
    %     end
    %
    %     ExtraTimeDelay = etime(clock, t0);
    %
    %     %if nargout >= 3
    %     [AMtmp, tout, DataTimetmp, ErrorFlag] = local_getbyname(ChannelNames, 'Double', 1, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
    %     %else
    %     %    [AMtmp, tout] = local_getbyname(ChannelNames, 'Double', 1, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod)
    %     %end
    %
    %     %if StructOutputFlag | nargout >= 3
    %     % .DataTime is the time on computer taking the data but
    %     % reference it w.r.t. the time zone where Matlab is running
    %     DateNumber1970 = 719529;  %datenum('1-Jan-1970');
    %     days = datenum(t0(1:3)) - DateNumber1970;
    %     t0_sec = 24*60*60*days + 60*60*t0(4) + 60*t0(5) + t0(6);
    %     TimeZoneDiff = round((t0_sec - real(DataTimetmp(1,1)))/60/60);
    %     DataTimetmp = (real(DataTimetmp)/60/60 + TimeZoneDiff)/24 + DateNumber1970 + imag(DataTimetmp)/(1e9 * 60 * 60 * 24);
    %
    %     % No time zone adjustment (UTC 00:00:00 Jan 1, 1970)
    %     %DataTime = real(DataTime)/60/60/24 + imag(DataTime)/(1e9 * 60 * 60 * 24);
    %     %end
    %
    %     for i = 1:size(varargin{1},1)
    %         for j = 1:size(varargin{1},2)
    %             AM{i,j} = AMtmp(1:NameSize(i,j),:);
    %             AMtmp(1:NameSize(i,j),:) = [];
    %             %if nargout >= 3
    %             DataTime{i,j} = DataTimetmp(1:NameSize(i,j),:);
    %             DataTimetmp(1:NameSize(i,j),:) = [];
    %             %end
    %
    %             % If input is a data structure, only change StructOutputFlag if 'numeric' is not on the input line
    %             StructOutputFlagStart = StructOutputFlag;
    %             if isstruct(varargin{1}{i,j})
    %                 if isfield(varargin{1}{i,j},'Field')
    %                     if ~NumericOutputFlag
    %                         StructOutputFlag = 1;
    %                     end
    %                 end
    %             end
    %
    %             if StructOutputFlag
    %                 Datatmp = AM{i,j};
    %                 DataTimetmp = DataTime{i,j};
    %                 if NCellOrString == 1
    %                     if isempty(UnitsFlag)
    %                         AM{i,j} = family2datastruct(varargin{1}{i,j});
    %                     else
    %                         AM{i,j} = family2datastruct(varargin{1}{i,j}, UnitsFlag);
    %                     end
    %                 elseif NCellOrString == 2
    %                     if iscell(varargin{2})
    %                         if isempty(UnitsFlag)
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}{i,j});
    %                         else
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}{i,j}, UnitsFlag);
    %                         end
    %                     else
    %                         if isempty(UnitsFlag)
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2});
    %                         else
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}, UnitsFlag);
    %                         end
    %                     end
    %                 elseif NCellOrString == 3
    %                     if iscell(varargin{2})
    %                         if isempty(UnitsFlag)
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}{i,j}, varargin{3}{i,j});
    %                         else
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}{i,j}, varargin{3}{i,j}, UnitsFlag);
    %                         end
    %                     else
    %                         if isempty(UnitsFlag)
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}, varargin{3}{i,j});
    %                         else
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}, varargin{3}{i,j}, UnitsFlag);
    %                         end
    %                     end
    %                 end
    %                 AM{i,j}.Data = Datatmp;
    %                 AM{i,j}.t = t;
    %                 AM{i,j}.tout = tout;
    %                 AM{i,j}.DataTime = DataTimetmp;
    %                 AM{i,j}.Mode = 'Online';
    %                 AM{i,j}.CreatedBy = 'getpv';
    %             end
    %             StructOutputFlag = StructOutputFlagStart;
    %         end
    %     end
    %
    %     return
    %
    %else
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % CELL OR CELL ARRAY INPUT %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Iterate on each cell with special attention to the t vector input
    % For an empty input, return empty
    if isempty(varargin{1})
        AM =[]; tout = []; DataTime = []; ErrorFlag = 0;
        return
    end
    % If input is a data structure, only change StructOutputFlag if 'numeric' is not on the input line
    if isstruct(varargin{1}{1}) && isfield(varargin{1}{1},'Field')
        if ~NumericOutputFlag
            StructOutputFlag = 1;
        end
    end
    % Count the number of inputs which are cells (Family or DeviceList) or strings (possibly Field)
    NCellOrString = 1;
    for i = 2:length(varargin)
        if ~iscell(varargin{i})
            if ~ischar(varargin{i})
                break;
            else
                NCellOrString = NCellOrString + 1;
            end
        else
            NCellOrString = NCellOrString + 1;
            %if length(varargin{1})~=length(varargin{NCellOrString}) | length(varargin{NCellOrString})==1
            %    error('When using cell, all the cells must be the same size as input 1 or be length one.');
            %end
        end
    end
    % t (if it exists) should be the next input.  Save it then zero it in varargin
    if length(varargin) >= NCellOrString+1
        if iscell(varargin{NCellOrString+1})
            error(sprintf('Expecting input #%d to be a time vector not a cell', NCellOrString+1));
        end
        if ischar(varargin{NCellOrString+1})
            error(sprintf('Expecting input #%d to be a time vector not a string', NCellOrString+1));
        end
        t = varargin{NCellOrString+1};
        varargin{NCellOrString+1} = 0;
    end
    ExtraTimeDelay = etime(clock, t0);
    t = t - ExtraTimeDelay;
    % Loop according to t
    for itime = 1:length(t)
        T = t(itime)-etime(clock, t0);
        if T > 0
            pause(T);
        end
        for i = 1:size(varargin{1},1)
            for j = 1:size(varargin{1},2)
                % Build the input line
                for k = 1:length(varargin)
                    if ~iscell(varargin{k})
                        Inputs1{1,k} = varargin{k};
                    elseif length(varargin{k}) == 1
                        Inputs1{1,k} = varargin{k}{1};
                    elseif (size(varargin{k},1) == size(varargin{1},1)) && (size(varargin{k},2) == size(varargin{1},2))
                        Inputs1{1,k} = varargin{k}{i,j};
                    else
                        error('When using cells, all the cells must be the same size or length 1 (repeated).');
                    end
                end
                if StructOutputFlag
                    if itime == 1
                        % Form the structure on the first time
                        [AM{i,j}, tout(1,itime), DataTime{i,j}, ErrorFlagNew] = getpv(Inputs1{:}, 'Struct', InputFlags{:});
                    else
                        % Add to the Data and time fields
                        [AM{i,j}.Data(:,itime), tmp, AM{i,j}.DataTime(:,itime), ErrorFlagNew] = getpv(Inputs1{:}, 'Numeric', InputFlags{:});
                        AM{i,j}.t(1,itime) = t(itime);
                        AM{i,j}.tout(1,itime) = etime(clock, t0);
                        DataTime{i,j}(:,itime) = AM{i,j}.DataTime(:,itime);
                    end
                else
                    [AM{i,j}(:,itime), tmp, DataTime{i,j}(:,itime), ErrorFlagNew] = getpv(Inputs1{:}, 'Numeric', InputFlags{:});
                end
                ErrorFlag = ErrorFlag | any(ErrorFlagNew);
            end
            tout(itime) = etime(clock, t0);
        end
    end
    % Make the output an AccObj object
    if ObjectOutputFlag
        AM = AccObj(AM);
    end
    return
end
%%%%%%%%%%%%%%%%%%
% End cell input %
%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% COMMONNAME - Commonname input with no family input %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isempty(varargin{1})
    if length(varargin) >= 2
        if ischar(varargin{2})
            Field = varargin{2};
            varargin(2) = [];
        end
    else
        % For an empty input, return empty
        if isempty(varargin{1})
            AM =[]; tout = []; DataTime = []; ErrorFlag = 0;
            return
        end
    end
    if isempty(Field)
        Field = FieldDefault;
    end
    if length(varargin) >= 2
        CommonNames = varargin{2};
    else
        error('Common names not found on the input line.');
    end
    if length(varargin) >= 3
        t = varargin{3};
    end
    if length(varargin) >= 4
        FreshDataFlag = varargin{4};
    end
    if length(varargin) >= 5
        TimeOutPeriod = varargin{5};
    end
    % Common names with no family name
    if ~ischar(CommonNames)
        error('If Family=[], then DeviceList must be a string of common names.')
    end
    [AM, tout, DataTime, DeviceList, ErrorFlag] = getbycommonname(CommonNames, Field, t, t0, FreshDataFlag, TimeOutPeriod, InputFlags{:});
    if ErrorFlag
        return;
    end
    if StructOutputFlag || nargout >= 3
        % .DataTime is the time on computer taking the data but
        % reference it w.r.t. the time zone where Matlab is running
        DateNumber1970 = 719529;  %datenum('1-Jan-1970');
        days = datenum(t0(1:3)) - DateNumber1970;
        t0_sec = 24*60*60*days + 60*60*t0(4) + 60*t0(5) + t0(6);
        TimeZoneDiff = round((t0_sec - real(DataTime(1,1)))/60/60);
        DataTime = (real(DataTime)/60/60 + TimeZoneDiff)/24 + DateNumber1970 + imag(DataTime)/(1e9 * 60 * 60 * 24);
    end
    % Structure output
    if StructOutputFlag
        AM = struct('Data', AM);
        AM.FamilyName = CommonNames;
        AM.Field = Field;
        AM.DeviceList = DeviceList;
        AM.Status = [];
        AM.t = t;
        AM.tout = tout;
        AM.DataTime = DataTime;
        AM.TimeStamp = t0;
        [DeviceList1, Family1] = common2dev(CommonNames(1,:));
        AM.Mode = getmode(Family1);                      % Base on just the first common name
        [AM.Units, AM.UnitsString] = getunits(Family1);  % Base on just the first common name
        AM.DataDescriptor = 'Get by Common Name';
        AM.CreatedBy = 'getpv';
        % Make the output an AccObj object
        if ObjectOutputFlag
            AM = AccObj(AM);
        end
    end
    return
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End CommonName input with no family input %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Parce inputs depending on Data structure, AO structure, Family, ChannelName method %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isstruct(varargin{1})
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % STRUCTURE INPUTS - Data structure or AO structure %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    if isfield(varargin{1},'FamilyName') && isfield(varargin{1},'Field')
        % Data structure - select FamilyName, DeviceList, Units  from the structure (.Mode flag???)
        % [AM, tout, DataTime, ErrorFlag] = getpv(DataStruct, Field {opt}, t, FreshDataFlag, TimeOutPeriod)
        % Only change StructOutputFlag if 'numeric' is not on the input line
        if ~NumericOutputFlag
            StructOutputFlag = 1;
        end
        Family = varargin{1}.FamilyName;
        Field = varargin{1}.Field;
        if length(varargin) >= 2
            if ischar(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        DeviceList = varargin{1}.DeviceList;
        if length(varargin) >= 2
            % If the input exists use it
            t = varargin{2};
        else
            % Else, get it from the structure if the field exists
            if isfield(varargin{1},'t')
                t = varargin{1}.t;
            end
        end
        if length(varargin) >= 3
            FreshDataFlag = varargin{3};
        end
        if length(varargin) >= 4
            TimeOutPeriod = varargin{4};
        end
        [FamilyIndex, AO] = isfamily(Family);
        % Change Units to the data structure units
        if isfield(AO, Field)
            AO.(Field).Units = varargin{1}.Units;
        end
    elseif isfield(varargin{1},'FamilyName')
        % AO structure - use the AO structure directly
        %  [AM, tout, DataTime, ErrorFlag] = getpv(AO, Field, DeviceList, t, FreshDataFlag, TimeOutPeriod)
        FamilyIndex = 1;
        AO = varargin{1};
        Family = varargin{1}.FamilyName;
        Field = '';
        if length(varargin) >= 2
            if ischar(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        if length(varargin) >= 2
            DeviceList = varargin{2};
        else
            DeviceList = AO.DeviceList;
            iStatus = find(varargin{1}.Status == 0);
            DeviceList(iStatus,:) = [];
        end
        if length(varargin) >= 3
            t = varargin{3};
        end
        if length(varargin) >= 4
            FreshDataFlag = varargin{4};
        end
        if length(varargin) >= 5
            TimeOutPeriod = varargin{5};
        end
    else
        error('Input #1 of unknown type');
    end
else
    % Family, ChannelName, or Common name are still left
    [FamilyIndex, AO] = isfamily(varargin{1});
    if FamilyIndex
        %%%%%%%%%%%%%%%%
        % FAMILY INPUT %
        %%%%%%%%%%%%%%%%
        %  [AM, tout, DataTime, ErrorFlag] = getpv(Family, Field {opt}, DeviceList, t, FreshDataFlag, TimeOutPeriod)
        Family = varargin{1};
        if length(varargin) >= 2
            if ischar(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        if isempty(Field)
            Field = FieldDefault;
        end
        if length(varargin) >= 2
            DeviceList = varargin{2};
        end
        if length(varargin) >= 3
            t = varargin{3};
        end
        if length(varargin) >= 4
            FreshDataFlag = varargin{4};
        end
        if length(varargin) >= 5
            TimeOutPeriod = varargin{5};
        end
    else
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % CHANNEL NAME OR COMMON NAME INPUT %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Just do input parsing here
        Family = varargin{1};
        % Default field is '' for channel names or it would be added as ChannelName.Field
        % But for common names it needs to be 'Monitor'
        Field = '';
        if length(varargin) >= 2
            if ~isnumeric(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        if length(varargin) >= 2
            t = varargin{2};
        end
        if length(varargin) >= 3
            FreshDataFlag = varargin{3};
        end
        if length(varargin) >= 4
            TimeOutPeriod = varargin{4};
        end
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End selection of inputs depending on Family, Data Structure, AO structure, or ChannelName method %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% AO, ChannelName, or CommonName %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isempty(t)
    t = 0;
end
if FamilyIndex
    %%%%%%%%%%%%%%%%%
    % FAMILY INPUTS %
    %%%%%%%%%%%%%%%%%
    % All ready done
    %if isempty(Field)
    %    Field = 'Monitor';
    %end
    if isempty(DeviceList)
        DeviceList = family2dev(Family);     % Default behavior comes from family2dev
        %DeviceList = family2dev(Family,1);  % Good status only
        %DeviceList = AO.DeviceList;         % All devices
    end
    if ischar(DeviceList)
        % Convert common name to a DeviceList
        DeviceList = common2dev(DeviceList, AO);
    end
    if (size(DeviceList,2) == 1)
        DeviceList = elem2dev(Family, DeviceList);
    end
    % Look for command-line over-rides
    if isfield(AO, Field)
        if ~isempty(UnitsFlag)
            AO.(Field).Units = UnitsFlag;
        end
        if ~isempty(ModeFlag)
            if strcmp(ModeFlag, 'Online') && strcmp(AO.(Field).Mode, 'Special')
                % For Online over-rides, look for Special mode first
                AO.(Field).Mode = 'Special';
            else
                AO.(Field).Mode = ModeFlag;
            end
        end
    end
    % Get data
    ExtraTimeDelay = etime(clock, t0);
    if StructOutputFlag || nargout >= 3
        [AM, tout, DataTime, ErrorFlag, DeviceIndex] = local_getpv(AO, Field, DeviceList, OutputDataType, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
    else
        [AM, tout] = local_getpv(AO, Field, DeviceList, OutputDataType, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
    end
    tout = tout + ExtraTimeDelay;
    if StructOutputFlag
        % Structure output
        AM = struct('Data', AM);
        %AM.Data = AM;
        AM.FamilyName = Family;
        AM.Field = Field;
        AM.DeviceList = DeviceList;
        if length(AO.Status) == 1
            AM.Status = AO.Status * ones(size(DeviceIndex));
        else
            %AM.Status = family2status(Family, AM.DeviceList);
            AM.Status = AO.Status(DeviceIndex);
        end
        if isfield(AO, Field)
            AM.Mode = AO.(Field).Mode;
            AM.Units = AO.(Field).Units;
            if strcmpi(AM.Units,'hardware')
                AM.UnitsString = AO.(Field).HWUnits;
            else
                AM.UnitsString = AO.(Field).PhysicsUnits;
            end
            AM.DataDescriptor = 'Get by FamilyName';
        else
            AM.Mode = 'Online';
            AM.Units = '';
            AM.UnitsString = '';
            AM.DataDescriptor = 'Get by Channel Name';
        end
        AM.CreatedBy = 'getpv';
    end
else
    % Look to see if it's a channel name or a common name
    % Just check the first name so it's a faster test
    [DeviceListTest, FamilyTest] = common2dev(Family(1,:));
    if ~isempty(FamilyTest)
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Common names where the family was the common name %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Field default will come from getbycommonname via another getpv call
        % The DeviceList does not matter (and should not be used)
        CommonNames = Family;
        [AM, tout, DataTime, DeviceList, ErrorFlag] = getbycommonname(CommonNames, Field, t, t0, FreshDataFlag, TimeOutPeriod, InputFlags{:});
        if ErrorFlag
            return;
        end
        % Structure output
        if StructOutputFlag
            AM = struct('Data', AM);
            AM.FamilyName = CommonNames;
            AM.Field = Field;
            AM.DeviceList = DeviceList;
            AM.Status = [];
            AM.Mode = getmode(FamilyTest(1,:));                      % Base on just the first common name
            [AM.Units, AM.UnitsString] = getunits(FamilyTest(1,:));  % Base on just the first common name
            AM.DataDescriptor = 'Get by Common Name';
            AM.CreatedBy = 'getpv';
        end
    else
        %%%%%%%%%%%%%%%%
        % CHANNEL NAME %
        %%%%%%%%%%%%%%%%
        % Can't use overrides with channel name method
        if ~isempty(UnitsFlag)
            error('You cannot change the units when using tango names.')
        end
        if ~(isempty(ModeFlag) || strcmpi(ModeFlag, 'Online'))
            error('Tango names only have an ''Online'' Mode.')
        end
        % Add Field to Family.Field
        FamilyOld = Family;
        if ~isempty(Field)
            Family = strcat(Family, ['.',Field]);
        end
        ExtraTimeDelay = etime(clock, t0);
        if strcmpi(OutputDataType,'String')
            % Get data with strings output
            if StructOutputFlag || nargout >= 3
                [AM, tout, DataTime, ErrorFlag] = getpvonline(Family, 'String', 0, t-ExtraTimeDelay);
            else
                [AM, tout] = getpvonline(Family, 'String', 0, t-ExtraTimeDelay);
            end
        else
            % Get data at every point in time vector, t
            if StructOutputFlag || nargout >= 3
                [AM, tout, DataTime, ErrorFlag] = local_getbyname(Family, OutputDataType, 0, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
            else
                [AM, tout] = local_getbyname(Family, OutputDataType, 0, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
            end
        end
        tout = tout + ExtraTimeDelay;
        % Structure output for channel name method
        if StructOutputFlag
            AM = struct('Data', AM);
            %AM.Data = AM;
            AM.FamilyName = FamilyOld;
            AM.Field = Field;
            AM.DeviceList = [];
            AM.Status = [];
            AM.Mode = 'Online';
            AM.Units = '';
            AM.UnitsString = '';
            AM.DataDescriptor = 'Get by Channel Name';
            AM.CreatedBy = 'getpv';
        end
    end
end
if StructOutputFlag || nargout >= 3
    % .DataTime is the time on computer taking the data but
    % reference it w.r.t. the time zone where Matlab is running
    DateNumber1970 = 719529;  %datenum('1-Jan-1970');
    days = datenum(t0(1:3)) - DateNumber1970;
    t0_sec = 24*60*60*days + 60*60*t0(4) + 60*t0(5) + t0(6);
    TimeZoneDiff = round((t0_sec - real(DataTime(1,1)))/60/60);
    DataTime = (real(DataTime)/60/60 + TimeZoneDiff)/24 + DateNumber1970 + imag(DataTime)/(1e9 * 60 * 60 * 24);
    % No time zone adjustment (UTC 00:00:00 Jan 1, 1970)
    %DataTime = real(DataTime)/60/60/24 + imag(DataTime)/(1e9 * 60 * 60 * 24);
end
% Structure output
if StructOutputFlag
    % Add time to structure
    AM.t = t;
    AM.tout = tout;
    AM.DataTime = DataTime;
    AM.TimeStamp = t0;
    % Make the output an AccObj object
    if ObjectOutputFlag
        AM = AccObj(AM);
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Main Function for Getting Data Using Common Names  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [AM, tout, DataTime, DeviceList, ErrorFlag] = getbycommonname(CommonNames, Field, t, t0, FreshDataFlag, TimeOutPeriod, varargin)
% Convert all the common names to Family and Device lists
[DeviceList, Family, ErrorFlag] = common2dev(CommonNames);
if ErrorFlag
    AM=[]; tout=[]; DataTime=[];
    return;
else
1000     % If all the families are the same then compress them
1001     FamilyTest = unique(Family, 'rows');
1002
1003     if size(FamilyTest, 1) == 1
1004         % 1 Family, Multiple devices are ok
1005         [AM, tout, DataTime, ErrorFlag] = getpv(FamilyTest, Field, DeviceList, t, FreshDataFlag, TimeOutPeriod, 'Numeric', varargin{:});
1006     else
1007         % Multiple families (loop)
1008         % It has to be in a loop for the simulator and to pickup special functions
1009
1010         if FreshDataFlag >= 1
1011             error('The FreshDataFlag is not programmed yet when when getting common names from multiple families (GJP).');
1012         end
1013
1014         % Loop on the time vector (t0 has already been started)
1015         for itime = 1:length(t)
1016             T = t(itime)-etime(clock, t0);
1017             if T > 0
1018                 pause(T);
1019             end
1020             for i = 1:size(Family,1)
1021                 [AM(i,itime), tmp, DataTime(i,itime), ErrorFlag1] = getpv(Family(i,:), Field, DeviceList(i,:), 'Numeric', varargin{:});
1022                 tout(1,itime) = etime(clock, t0);
1023                 ErrorFlag = ErrorFlag | ErrorFlag1;
1024             end
1025         end
1026     end
1027 end
1028
1029
1030
1031 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1032 %  Main Function for Getting Data using the Channel Names  %
1033 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1034 function [AM, tout, DataTime, ErrorFlag] = local_getbyname(ChannelName, OutputDataType, N, t, FreshDataFlag, TimeOutPeriod)
1035
1036 t0 = clock;
1037 ErrorFlag = 0;
1038
1039
1040 if nargout < 3
1041     [AM, tout] = getpvonline(ChannelName, OutputDataType, N, t);
1042 else
1043     [AM, tout, DataTime, ErrorFlag] = getpvonline(ChannelName, OutputDataType, N, t);
1044 end
1045
1046
1047 % FreshDataFlag
1048 if FreshDataFlag && length(t) == 1
1049     % Only use FreshDataFlag for scalar t
1050     FreshDataCounter = FreshDataFlag;
1051     AM0 = AM;
1052     while FreshDataCounter
1053         if nargout < 3
1054             [AM, tout] = getpvonline(ChannelName, OutputDataType, N);
1055         else
1056             [AM, tout, DataTime, ErrorFlag] = getpvonline(ChannelName, OutputDataType, N);
1057         end
1058
1059         if ~any((AM-AM0)==0)
1060             FreshDataCounter = FreshDataCounter - 1;
1061             AM0 = AM;
1062         end
1063
1064         if etime(clock, t0) > TimeOutPeriod
1065             k = find((AM-AM0)==0);
1066             for j = 1:length(k)
1067                 fprintf('%s not changing.\n', deblank(ChannelName(k(j),:)));
1068             end
1069             error('Timed out waiting for fresh data.');
1070         end
1071     end
1072     tout = etime(clock, t0);
1073 end
1074
1075 return
1076
1077 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1078 %  Main Function for Getting Data using the Accelerator Object  %
1079 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1080 function [AM, tout, DataTime, ErrorFlag, DeviceIndex] = local_getpv(AO, Field, DeviceList, OutputDataType, t, FreshDataFlag, TimeOutPeriod)
1081 %  INPUTS
1082 %  1. AO - the ACCELERATOR_OBJECT structure for the called family
1083 %  2. Field - 'Monitor' or 'Setpoint'
1084 %  3. DeviceList - Device list
1085 %
1086 %  OUTPUTS
1087 %  1. AM - Vector a read values
1088 %  2. TimeStamp - timestamp when data collected
1089 %  3. ErrorFlag - 0 if OK, else 1
1090 %  4. DeviceIndex - List of status 1 devices
1091
1092 %  Written by Gregory J. Portmann
1093 %  Modified by Laurent S. Nadolski
1094
1095 t0 = clock;
1096 ErrorFlag = 0;
1097 N = 0;  % Output size
1098
1099
1100 % Find the index for where the desired data is in the total device list
1101 DeviceListTotal = AO.DeviceList;
1102 [DeviceIndex, iNotFound] = findrowindex(DeviceList, DeviceListTotal);
1103 if length(iNotFound) > 0
1104     % Device not found
1105     for i = 1:length(iNotFound)
1106         fprintf('   No devices to get for Family %s(%d,%d)\n', AO.FamilyName, DeviceList(i,1), DeviceList(i,2));
1107     end
1108     error('%d Devices not found', length(iNotFound));
1109 end
1110
1111 % Check the DeviceIndex
1112 if isempty(DeviceIndex)
1113     DataTime = 0 + 0*sqrt(-1);
1114     tout = etime(clock, t0);
1115     AM = [];
1116     %fprintf('   WARNING:  No devices to get for Family %s (getpv)\n', AO.FamilyName);
1117     return;
1118 end
1119
1120 %% TANGO specific part
1121
1122 % Load Field sub-structure into AOField
1123 if ~isfield(AO, Field);
1124     % Try to check it online or simulator
1125     if isfield(AO, 'Setpoint')
1126         Mode = getfamilydata(AO.FamilyName, 'Setpoint', 'Mode');
1127     elseif isfield(AO, 'Monitor')
1128         Mode = getfamilydata(AO.FamilyName, 'Monitor', 'Mode');
1129     else
1130         Mode = '';
1131     end
1132     if strcmpi(Mode,'Simulator') || strcmpi(Mode,'Model')
1133         ExtraTimeDelay = etime(clock, t0);
1134         [AM, tout, DataTime, ErrorFlag] = getpvmodel(AO.FamilyName, Field, DeviceList, t-ExtraTimeDelay, 'Physics', 'Numeric');
1135         tout = tout + ExtraTimeDelay;
1136
1137         % Since physics2hw conversions are not known for fields that are not families, just return
1138         return
1139     end
1140
1141     % Try changing the suffix of the Monitor or Setpoint field
1142     if isfield(AO, 'Setpoint')
1143         Tango = family2tango(AO, 'Setpoint', DeviceList);
1144     elseif isfield(AO, 'Monitor')
1145         Tango = family2tango(AO, 'Monitor', DeviceList);
1146     else
1147         error(sprintf('Field %s not found for Family %s', Field, AO.FamilyName));
1148     end
1149     if any(strcmpi(getfamilydata('Machine'),{'spear3','spear'}))
1150         % Spear likes to change the channel name after the ':'
1151
1152         %i = findstr(Channel(1,:),':');
1153         %if ~isempty(i)
1154         %    Channel(:,i:end) = [];
1155         %end
1156         %Channel = strcat(Channel, [':',Field]);
1157
1158         % Since the location of ":" can be different in each row, loop
1159         ChannelMat = [];
1160         for j = 1:size(Channel,1)
1161             i = findstr(Channel(j,:),':');
1162             if isempty(i)
1163                 % I'm not sure what to do if ":" is missing, I'm just add a ":"
1164                 ChannelMat = strvcat(ChannelMat, [Channel(j,1:i), ':', Field]);
1165             else
1166                 ChannelMat = strvcat(ChannelMat, [Channel(j,1:i), Field]);
1167             end
1168         end
1169         Tango = strcat(Tango, [':',Field]);
1170     else
1171         % Add a .Field
1172         Tango = strcat(Tango, ['.',Field]);
1173     end
1174
1175     ExtraTimeDelay = etime(clock, t0);
1176     if nargout < 3
1177         [AM, tout] = getpvonline(Tango, OutputDataType, N, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
1178     else
1179         [AM, tout, DataTime, ErrorFlag] = getpvonline(Tango, OutputDataType, N, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
1180     end
1181     tout = tout + ExtraTimeDelay;
1182     return
1183 end
1184
1185
1186 AOField = AO.(Field);   % Should I replace this????
1187
1188 % If mode does not exist, force to online mode
1189 if isfield(AOField, 'Mode')
1190     Mode = AOField.Mode;
1191 else
1192     Mode = 'Online';
1193 end
1194
1195
1196 % Check if Online should really be special
1197 if strcmpi(Mode, 'Online')
1198    if isfield(AO.(Field), 'SpecialFunctionGet')
1199        Mode = 'Special';
1200    end
1201 end
1202
1203
1204 if ~isstruct(AO.(Field))
1205     % If it's not a structure that just get the field
1206     % Hardward and physics get ignored
1207     t1 = clock;
1208     [AM, ErrorFlag] = getfamilydata(AO.FamilyName, Field, DeviceList);
1209
1210     tout = etime(t1, t0);
1211     if nargout >= 3
1212         days = datenum(t1(1:3)) - 719529;  %datenum('1-Jan-1970');
1213         tt = 24*60*60*days + 60*60*t1(4) + 60*t1(5) + t1(6);
1214         DataTime(1:size(AM,1),1:length(t)) = fix(tt) + rem(tt,1)*1e9*sqrt(-1);
1215     end
1216
1217 elseif strcmpi(Mode,'online')
1218     % Online
1219     if strcmpi(AOField.DataType,'Scalar')
1220         N = 1;  % Output size
1221
1222         ExtraTimeDelay = etime(clock, t0);
1223         if nargout < 3
1224             [AM, tout] = getpvonline(AOField.TangoNames(DeviceIndex,:), Field, OutputDataType, N, t-ExtraTimeDelay);
1225         else
1226             [AM, tout, DataTime, ErrorFlag] = getpvonline(AOField.TangoNames(DeviceIndex,:), Field, OutputDataType, N, t-ExtraTimeDelay);
1227         end
1228         tout = tout + ExtraTimeDelay;
1229
1230         % FreshDataFlag
1231         if FreshDataFlag && length(t) == 1
1232             % Only use FreshDataFlag for scalar t
1233             FreshDataCounter = FreshDataFlag;
1234             AM0 = AM;
1235             while FreshDataCounter
1236                 if nargout < 3
1237                     [AM, tout] = getpvonline(AOField.TangoNames(DeviceIndex,:), Field,OutputDataType, N);
1238                 else
1239                     [AM, tout, DataTime, ErrorFlag] = getpvonline(AOField.TangoNames(DeviceIndex,:), Field, OutputDataType, N);
1240                 end
1241
1242                 if ~any((AM-AM0)==0)
1243                     FreshDataCounter = FreshDataCounter - 1;
1244                     AM0 = AM;
1245                 end
1246
1247                 if etime(clock, t0) > TimeOutPeriod
1248                     k = find((AM-AM0)==0);
1249                     for j = 1:length(k)
1250                         fprintf('%s not changing.\n', deblank((AOField.TangoNames(DeviceIndex(k(j)),:))));
1251                     end
1252                     error('Timed out waiting for fresh data.');
1253                 end
1254             end
1255             tout = etime(clock, t0);
1256         end
1257
1258     elseif strcmpi(AOField.DataType, 'Vector')
1259
1260
1261         % Output(DataTypeIndex) must be equal to the number of elements in the family
1262
1263         % There can only be one Tango or channel name for DataType='Vector'
1264         TangoNames = deblank(AOField.TangoNames(1,:));
1265
1266
1267
1268         % Get data at every point in time vector, t
1269         AM = [];
1270         ExtraTimeDelay = etime(clock, t0);
1271         t = t - ExtraTimeDelay;
1272         for itime = 1:length(t)
1273             T = t(itime)-etime(clock, t0);
1274             if T > 0
1275                 pause(T);
1276             end
1277
1278             % Get data
1279             if nargout >= 3
1280                 [tmp, tout, DataTime(:,itime), ErrorFlag] = getpvonline(TangoNames, 'Vector', N);
1281             else
1282                 tmp = getpvonline(TangoNames, 'Vector', N);
1283             end
1284             if isfield(AOField, 'DataTypeIndex')
1285                 tmp = tmp(AOField.DataTypeIndex);
1286             end
1287             AM = [AM tmp(DeviceIndex,:)];
1288
1289             tout(itime) = etime(clock, t0);
1290         end
1291
1292         % FreshDataFlag
1293         if FreshDataFlag & length(t) == 1
1294             % Only use FreshDataFlag for scalar t
1295             FreshDataCounter = FreshDataFlag;
1296             AM0 = AM;
1297             while FreshDataCounter
1298                 if nargout >= 3
1299                     [AM, tout, DataTime, ErrorFlag] = getpvonline(TangoNames, 'Vector', N);
1300                 else
1301                     AM = getpvonline(TangoNames, 'Vector', N);
1302                 end
1303                 if isfield(AOField, 'DataTypeIndex')
1304                     AM = AM(AOField.DataTypeIndex);
1305                 end
1306                 AM = AM(DeviceIndex,:);
1307
1308                 if ~any((AM-AM0)==0)
1309                     FreshDataCounter = FreshDataCounter - 1;
1310                     AM0 = AM;
1311                 end
1312
1313                 if etime(clock, t0) > TimeOutPeriod
1314                     k = find((AM-AM0)==0);
1315                     for j = 1:length(k)
1316                         fprintf('%s[%d,%d] not changing.\n', AO.FamilyName, DeviceList(k(j),1), DeviceList(k(j),2));
1317                     end
1318                     error('Timed out waiting for fresh data.');
1319                 end
1320             end
1321             tout = etime(clock, t0);
1322         end
1323
1324     elseif strcmpi(AOField.DataType,'Matrix')
1325
1326         for iDev = 1:length(DeviceIndex)
1327             %AM(iDev,:) = rand(1,10); DataTime(iDev,:) = now; ErrorFlag(iDev,:)=0;
1328             [AM(iDev,:), tout, DataTime(iDev,:), ErrorFlag(iDev,1)] = getpvonline(AOField.TangoNames(DeviceIndex(iDev),:), 'Matrix', N);
1329         end
1330         ErrorFlag = any(ErrorFlag);
1331         tout = etime(clock, t0);
1332
1333     else
1334         error(sprintf('Unknown DataType for family %s.', AO.FamilyName));
1335     end
1336
1337     % Change to physics units if Units = 'physics'
1338     if strcmpi(AO.(Field).Units,'physics')
1339         % Change to physics units
1340         AM = hw2physics(AO.FamilyName, Field, AM, DeviceList);
1341     end
1342
1343 elseif strcmpi(Mode,'Special')
1344
1345     if isfield(AOField, 'SpecialFunctionGet')
1346         SpecialFunction = AOField.SpecialFunctionGet;
1347     elseif isfield(AOField, 'SpecialFunction')
1348         SpecialFunction = AOField.SpecialFunction;
1349     else
1350         error(sprintf('No special function specified for Family %s (getpv).', AO.FamilyName));
1351     end
1352
1353     % Get data at every point in time vector, t
1354     ExtraTimeDelay = etime(clock, t0);
1355     t = t - ExtraTimeDelay;
1356     [AM, tout, DataTime, ErrorFlag] = feval(SpecialFunction, AO.FamilyName, Field, DeviceList, t);
1357     t1 = clock;
1358     if isempty(tout)
1359         tout = etime(t1, t0);
1360     end
1361     if nargout >= 3 && isempty(DataTime)
1362         days = datenum(t1(1:3)) - 719529;  %datenum('1-Jan-1970');
1363         tt = 24*60*60*days + 60*60*t1(4) + 60*t1(5) + t1(6);
1364         DataTime(1:size(AM,1),1) = fix(tt) + rem(tt,1)*1e9*sqrt(-1);
1365     end
1366     if length(t) > length(tout)
1367         for itime = 2:length(t)
1368             T = t(itime)-etime(clock, t0);
1369             if T > 0
1370                 pause(T);
1371             end
1372
1373             % Get data
1374             [Tmp, toutTmp, DataTimeTmp, ErrorFlag] = feval(SpecialFunction, AO.FamilyName, Field, DeviceList, t);
1375
1376             AM = [AM Tmp];
1377             DataTime = [DataTime DataTimeTmp];
1378
1379             t1 = clock;
1380             tout(1,itime) = etime(t1, t0);
1381             if nargout >= 3 && isempty(DataTimeTmp)
1382                 days = datenum(t1(1:3)) - 719529;  %datenum('1-Jan-1970');
1383                 tt = 24*60*60*days + 60*60*t1(4) + 60*t1(5) + t1(6);
1384                 DataTime(1:size(AM,1),itime) = fix(tt) + rem(tt,1)*1e9*sqrt(-1);
1385             end
1386         end
1387     end
1388
1389     % FreshDataFlag
1390     if FreshDataFlag && length(t) == 1
1391         % Only use FreshDataFlag for scalar t
1392         FreshDataCounter = FreshDataFlag;
1393         AM0 = AM;
1394         while FreshDataCounter
1395             % Get data
1396             [AM, tout, DataTime, ErrorFlag] = feval(SpecialFunction, AO.FamilyName, Field, DeviceList, t);
1397
1398             if ~any((AM-AM0)==0)
1399                 FreshDataCounter = FreshDataCounter - 1;
1400                 AM0 = AM;
1401             end
1402
1403             t1 = clock;
1404             if etime(t1, t0) > TimeOutPeriod
1405                 k = find((AM-AM0)==0);
1406                 for j = 1:length(k)
1407                     fprintf('%s[%d,%d] not changing.\n', AO.FamilyName, DeviceList(k(j),1), DeviceList(k(j),2));
1408                 end
1409                 error('Timed out waiting for fresh data.');
1410             end
1411         end
1412         tout = etime(t1, t0);
1413
1414         if nargout >= 3 && isempty(DataTime)
1415             days = datenum(t1(1:3)) - 719529;  %datenum('1-Jan-1970');
1416             tt = 24*60*60*days + 60*60*t1(4) + 60*t1(5) + t1(6);
1417             DataTime(1:size(AM,1),1) = fix(tt) + rem(tt,1)*1e9*sqrt(-1);
1418         end
1419     end
1420
1421     % Change to physics units if Units = 'physics'
1422     if strcmpi(AO.(Field).Units,'physics')
1423         % Change to physics units
1424         AM = hw2physics(AO.FamilyName, Field, AM, DeviceList);
1425     end
1426
1427 elseif strcmpi(Mode,'manual')
1428     % Always return in hardware units (like connected to the IOC)
1429     % The conversion to physics in done at the end
1430     t = 0;
1431     if strcmp(AO.FamilyName, 'TUNE')
1432         HarmNumber = [];
1433         RF = [];
1434         if find(DeviceIndex == 1)
1435             AM(1,1) = input(sprintf('   Input the horizontal tune (fraction or Hz) = '));
1436             if AM(1,1) > 1
1437                 HarmNumber = getharmonicnumber;
1438                 RF = getrf('Struct');
1439                 if strcmpi(RF.UnitsString,'MHz')
1440                     FundFreq = 1e6*RF.Data / HarmNumber;
1441                 elseif strcmpi(RF.UnitsString,'Hz')
1442                     FundFreq = RF.Data / HarmNumber;
1443                 else
1444                     error('RF units in not known.');
1445                 end
1446                 %AM(1,1) = (AM(1,1)- RF) / FundFreq;
1447                 AM(1,1) = AM(1,1) / FundFreq;
1448                 fprintf('   Horizontal fraction tune computed to be %f\n\n', AM(1,1));
1449             end
1450         end
1451         if find(DeviceIndex == 2)
1452             AM(2,1) = input(sprintf('   Input the vertical   tune (fraction or Hz) = '));
1453             if AM(2,1) > 1
1454                 if isempty(HarmNumber)
1455                     HarmNumber = getharmonicnumber;
1456                 end
1457                 if isempty(RF)
1458                     RF = getrf('Struct');
1459                 end
1460                 if strcmpi(RF.UnitsString,'MHz')
1461                     FundFreq = 1e6*RF.Data / HarmNumber;
1462                 elseif strcmpi(RF.UnitsString,'Hz')
1463                     FundFreq = RF.Data / HarmNumber;
1464                 else
1465                     error('RF units in not known.');
1466                 end
1467                 AM(2,1) = AM(2,1)/FundFreq;
1468                 %AM(2,1) = (AM(2,1) - HarmNumber * FundFreq)/FundFreq;
1469                 fprintf('   Vertical   fraction tune computed to be %f\n\n', AM(2,1));
1470             end
1471         end
1472         if find(DeviceIndex == 3)
1473             AM(2,1) = input('   Input the synchrotron tune = ');
1474         end
1475     elseif strcmp(AO.FamilyName, 'RF')
1476         if strcmpi(AO.(Field).Units, 'Hardware')
1477             AM(1) = input(sprintf('   Input the RF frequency [%s] = ', AO.(Field).HWUnits));
1478         else
1479             AM(1) = input(sprintf('   Input the RF frequency [%s] = ', AO.(Field).PhysicsUnits));
1480             AM = physics2hw(AO.FamilyName, Field, AM, [1 1]);
1481         end
1482     else
1483         for i = 1:length(DeviceIndex)
1484             if strcmpi(AO.(Field).Units, 'Hardware')
1485                 AM(i,:) = input(sprintf('   Manual input:  %s(%d,%d) [%s] = ', AO.FamilyName, AO.DeviceList(DeviceIndex(i),1), AO.DeviceList(DeviceIndex(i),2), AO.(Field).HWUnits));
1486             else
1487                 AM(i,:) = input(sprintf('   Manual input:  %s(%d,%d) [%s] = ', AO.FamilyName, AO.DeviceList(DeviceIndex(i),1), AO.DeviceList(DeviceIndex(i),2), AO.(Field).PhysicsUnits));
1488                 AM(i,:) = physics2hw(AO.FamilyName, Field, AM(i,:), AO.DeviceList(DeviceIndex(i),:));
1489             end
1490         end
1491     end
1492
1493     t1 = clock;
1494     tout = etime(t1, t0);
1495     days = datenum(t1(1:3)) - 719529;  %datenum('1-Jan-1970');
1496     tt = 24*60*60*days + 60*60*t1(4) + 60*t1(5) + t1(6);
1497     DataTime(1:size(AM,1),1) = fix(tt) + rem(tt,1)*1e9*sqrt(-1);
1498
1499     % Change to physics units if Units = 'physics'
1500     if strcmpi(AO.(Field).Units,'physics')
1501         % Change to physics units
1502         AM = hw2physics(AO.FamilyName, Field, AM, DeviceList);
1503     end
1504
1505
1506 elseif strcmpi(Mode,'Simulator') || strcmpi(Mode,'Model')
1507
1508     ExtraTimeDelay = etime(clock, t0);
1509     %[AM, tout, DataTime, ErrorFlag] = getpvmodel(AO, Field, DeviceList, t-ExtraTimeDelay, 'Physics', 'Numeric');
1510     [AM, tout, DataTime, ErrorFlag] = getpvmodel(AO, Field, DeviceList, t-ExtraTimeDelay, AO.(Field).Units, 'Numeric');
1511     tout = tout + ExtraTimeDelay;
1512
1513
1514     if strcmpi(OutputDataType, 'String')
1515         AM = num2str(AM);
1516     end
1517
1518     % Change to physics units if Units = 'physics'
1519     %if strcmpi(AO.(Field).Units,'Hardware')
1520     %    % Change to physics units
1521     %    AM = physics2hw(AO.FamilyName, Field, AM, DeviceList, getenergymodel);
1522     %end
1523
1524 else
1525     error(sprintf('Unknown mode for family %s.', AO.FamilyName));
1526 end
1527
1528
1529