Description of getvbpmfamily
Home > mml > getvbpmfamily.m
getvbpmfamily
PURPOSE
GETVBPMFAMILY - Return the default vertical BPM family
SYNOPSIS
function Family = getvbpmfamily
DESCRIPTION
GETVBPMFAMILY - Return the default vertical BPM family
  Family = getvbpmfamily
  The family name is determined by the MemberOf field equal to 'BPMy' or 'VBPM'
  See also gethbpmfamily, gethcmfamily, getvcmfamily
  Writen by Greg Portmann
CROSS-REFERENCE INFORMATION
This function calls:
findmemberof FINDMEMBEROF - Finds all family members
This function is called by:
amp2mm AMPS2MM - Returns the maximum millimeter orbit change per change in corrector
getbpm GETBPM - Returns the horizontal and vertical orbit
getbpmresp GETBPMRESP - Returns the BPM response matrix in the horizontal and vertical planes
gety GETY - Returns the vertical orbit
loadorbit LOADORBIT - Loads orbit by file/directory specification - or - Golden %orbit by default
magstep HCM Step
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
measbpmresplinearity MEASBPMRESPLINEARITY - Compute BPMlinearity
measchro MEASCHRO - measures the chromaticity function emperically
meascmhysteresis MEASCMHYSTERESIS - Measure corrector magnet hysteresis
measdisp MEASDISP - Measures the dispersion function
mm2amp MM2AMPS - Returns the change in corrector need for a maximum orbit change
orbitcorrectionmethods ORBITCORRECTIONMETHODS - Some the orbit correction methods used on light sources
plotdisp PLOTDISP - Plots the dispersion function
plotgoldenorbit PLOTGOLDENORBIT - Plots the golden orbit
plotoffsetorbit PLOTOFFSETORBIT - Plots the offset orbit
plotorbit PLOTORBIT - Plot the present orbit w.r.t. the golden or offset orbit
plotorbitdata PLOTORBITDATA - Plots BPM statistics
quad2bpm QUAD2BPM - Returns the nearest BPM to the specified quadrupole
quadcenterfit BBASEARCH - Model search method to find a quarupole center
saveoffsetorbit SAVEOFFSETORBIT - Save offset orbit into file
setgolden SETGOLDEN - Set the golden values
setoffset SETOFFSET - Set the offset
setorbit SETORBIT - Orbit correction function
setorbitbump SETORBITBUMP - Local bump program (uses setorbit)
setorbitsetup SETORBITSETUP - BPM & CM setup function for setorbitgui
SOURCE CODE
function Family = getvbpmfamily
%GETVBPMFAMILY - Return the default vertical BPM family
%  Family = getvbpmfamily
%
%  The family name is determined by the MemberOf field equal to 'BPMy' or 'VBPM'
%
%  See also gethbpmfamily, gethcmfamily, getvcmfamily
%
%  Writen by Greg Portmann
persistent WarningFlag
Family = findmemberof('BPMy');
if isempty(Family)
    Family = findmemberof('VBPM');
    if isempty(Family)
        %Family = {'BPMy'};
        if isempty(WarningFlag)
            fprintf('\n   No default vertical BPM family has been specified in the MML.\n');
            fprintf('   To define one, add ''BPMy'' or ''VBPM'' to the .MemberOf field for the default family.\n\n');
            WarningFlag = 1;
        end
        Family = {''};
    end
end
Family = Family{1};