Description of getvcmfamily
Home > mml > getvcmfamily.m
getvcmfamily
PURPOSE
GETVCMFAMILY - Returns the default vertical corrector family
SYNOPSIS
function Family = getvcmfamily
DESCRIPTION
GETVCMFAMILY - Returns the default vertical corrector family
  Family = getvcmfamily
  The family name is determined by the MemberOf field equal to 'VCM'
  See also gethbpmfamily, getvbpmfamily, gethcmfamily
  Writen by Greg Portmann
CROSS-REFERENCE INFORMATION
This function calls:
findmemberof FINDMEMBEROF - Finds all family members
This function is called by:
correctors2golden CORRECTORS2GOLDEN - Sets the default corrector families to the golden configuration values
findrf FINDRF - Finds the RF frequency that minimizes the energy change due
getbpmresp GETBPMRESP - Returns the BPM response matrix in the horizontal and vertical planes
golden2sim GOLDEN2SIM - loads online machine configuration to AT configuration
machine2sim MACHINE2SIM - loads online machine configuration to AT configuration
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
meascmhysteresis MEASCMHYSTERESIS - Measure corrector magnet hysteresis
measdispresp MEASDISPRESP - Measures Amman TERMs in response matrix
orbitcorrectionmethods ORBITCORRECTIONMETHODS - Some the orbit correction methods used on light sources
plotcm PLOTCM - Plots the horizontal and vertical corrector magnet families and
scanorbit SCANORBIT - Scans 2 correctors 90 degrees out of phase
setorbit SETORBIT - Orbit correction function
setorbitbump SETORBITBUMP - Local bump program (uses setorbit)
setorbitsetup SETORBITSETUP - BPM & CM setup function for setorbitgui
vcm2golden VCM2GOLDEN - Set vertical corrector strengths to golden values
vcm2zero VCM2ZERO - Set vertical corrector strengths to zero
SOURCE CODE
function Family = getvcmfamily
%GETVCMFAMILY - Returns the default vertical corrector family
%  Family = getvcmfamily
%
%  The family name is determined by the MemberOf field equal to 'VCM'
%
%  See also gethbpmfamily, getvbpmfamily, gethcmfamily
%
%  Writen by Greg Portmann
persistent WarningFlag
Family = findmemberof('VCM');
if isempty(Family)
    Family = findmemberof('VCOR');
    if isempty(Family)
        %Family = {'VCM'};
        if isempty(WarningFlag)
            fprintf('\n   No default vertical corrector family has been specified in the MML.\n');
            fprintf('   To define one, add ''VCM'' or ''VCOR'' to the .MemberOf field for the default family.\n\n');
            WarningFlag = 1;
        end
        Family = {''};
    end
end
Family = Family{1};