Description of ismemberof
Home > mml > ismemberof.m
ismemberof
PURPOSE
ISMEMBEROF - Returns turn if the membership information of a family (cell of strings)
SYNOPSIS
function [IsTest, Index] = ismemberof(FamilyName, Field, MemberString)
DESCRIPTION
ISMEMBEROF - Returns turn if the membership information of a family (cell of strings)
  [MemberOfBooleanVector, Index] = ismemberof(FamilyName, MemberString)
  If FamilyName is a matrix, then a column of individual ismemberof calls is returned.
  MemberString must be a string.
  If the family was not found, then [] is returned.
  An optional Field input can be used to only look through subfields.
  [MemberOfBooleanVector, Index] = ismemberof(FamilyName, Field, MemberString)
  Subfield membership is usually not used.
 INPUTS
  1. If FamilyName is a matrix, then a column of individual ismemberof calls is returned.
  2. MemberString must be a string.
  If the family was not found, then [] is returned.
  See Also getmemberof, findmemberof, isfamily
CROSS-REFERENCE INFORMATION
This function calls:
getmemberof GETMEMBEROF - Returns the membership information of a family (cell of strings)
This function is called by:
getcrunch GETCRUNCH- Returns the crunch values for a family (radians)
getdata GETDATA - Searches through a file (or group of files) for a data structure which matches the family name
getgain GETGAIN - Returns the gain for a family
getgolden GETGOLDEN - Returns the golden values for a family
getmachineconfig GETMACHINECONFIG - Returns or saves to file the present storage ring setpoints and monitors
getoffset GETOFFSET - Returns the offset values for a family
getroll GETROLL - Returns the roll values for a family (radians)
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
makephysdata MAKEPHYSDATA - Make a starting physics data file
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
orbitcorrectionmethods ORBITCORRECTIONMETHODS - Some the orbit correction methods used on light sources
physics2hw PHYSICS2HW - Converts from 'Physics' units to 'Hardware' units
quad2bpm QUAD2BPM - Returns the nearest BPM to the specified quadrupole
quadcenter QUADCENTER - Measure the magnet center of a quadrupole magnet
quadcenterinit QMS = quadcenterinit(Family, Device, QuadPlane)
rmgolden RMGOLDEN - Remove the golden values for data set
rmoffset RMOFFSET - Remove the offset values for data set
sext2bpm SEXT2BPM - Returns the nearest BPM to the specified sextupole
showmachinedata SHOWMACHINEDATA - Display setpoints and readbacks for families in AcceleratorObjects
sweepenergy SWEEPENERGY - Energy sweep of the storage ring
SOURCE CODE
function  [IsTest, Index] = ismemberof(FamilyName, Field, MemberString)
%ISMEMBEROF - Returns turn if the membership information of a family (cell of strings)
%  [MemberOfBooleanVector, Index] = ismemberof(FamilyName, MemberString)
%
%  If FamilyName is a matrix, then a column of individual ismemberof calls is returned.
%  MemberString must be a string.
%  If the family was not found, then [] is returned.
%
%  An optional Field input can be used to only look through subfields.
%  [MemberOfBooleanVector, Index] = ismemberof(FamilyName, Field, MemberString)
%  Subfield membership is usually not used.
%
% INPUTS
%  1. If FamilyName is a matrix, then a column of individual ismemberof calls is returned.
%  2. MemberString must be a string.
%  If the family was not found, then [] is returned.
%
%
%  See Also getmemberof, findmemberof, isfamily
%
%  Written by Gregory J. Portmann
if nargin < 2
    error('2 inputs required');
end
if nargin == 2
    MemberString = Field;
end
if isstruct(FamilyName)
    if isfield(FamilyName, 'FamilyName')
        FamilyName = FamilyName.FamilyName;
    else
        error('For structure inputs, FamilyName field must exist');
    end
end
IsTest = [];
Index = [];
for i = 1:size(FamilyName,1)
    Family = deblank(FamilyName(i,:));
    if nargin == 2
        IsTest(i,1) = any(strcmpi(MemberString, getmemberof(Family)));
    else
        IsTest(i,1) = any(strcmpi(MemberString, getmemberof(Family, Field)));
    end
    if IsTest(i,1) == 1
        Index = [Index; i];
    end
end