Description of minsp
Home > mml > minsp.m
minsp
PURPOSE
MINSP - Minimum value of the setpoint
SYNOPSIS
function [Data, ErrorFlag] = minsp(varargin)
DESCRIPTION
MINSP - Minimum value of the setpoint
  FamilyName/DeviceList Method
  SPmin = maxsp(Family, DeviceList)
  SPmin = maxsp(DataStructure)
  ChannelName Method
  SPmin = maxsp(ChannelNames)
  INPUTS
  1. Family - Family Name
              Data Structure
              Accelerator Object
  2. DeviceList - [Sector Device #] or [element #] list {Default or empty list: whole family}
  OUTPUTS
  1. SPmin - Minimum setpoint of the device
  NOTES
  1. If Family is a cell array, then DeviceList and Field can also be a cell arrays
  See Also maxsp, getfamilydata(Family, Field, 'Range')
CROSS-REFERENCE INFORMATION
This function calls:
minpv MinPV - Maximum value of a process variable
This function is called by:
quadcenter QUADCENTER - Measure the magnet center of a quadrupole magnet
setorbit SETORBIT - Orbit correction function
SOURCE CODE
function [Data, ErrorFlag] = minsp(varargin)
%MINSP - Minimum value of the setpoint
%
%  FamilyName/DeviceList Method
%  SPmin = maxsp(Family, DeviceList)
%  SPmin = maxsp(DataStructure)
%
%  ChannelName Method
%  SPmin = maxsp(ChannelNames)
%
%  INPUTS
%  1. Family - Family Name
%              Data Structure
%              Accelerator Object
%  2. DeviceList - [Sector Device #] or [element #] list {Default or empty list: whole family}
%
%  OUTPUTS
%  1. SPmin - Minimum setpoint of the device
%
%  NOTES
%  1. If Family is a cell array, then DeviceList and Field can also be a cell arrays
%
%  See Also maxsp, getfamilydata(Family, Field, 'Range')
%
%  Written by Gregory J. Portmann
[Data, ErrorFlag] = minpv(varargin{:});