Description of setorbit
Home > mml > setorbit.m
setorbit
PURPOSE
SETORBIT - Orbit correction function
SYNOPSIS
function [OCS, OCS0, V, S, ErrorFlag] = setorbit(varargin)
DESCRIPTION
SETORBIT - Orbit correction function
  Family/DeviceList method:
  [CM, OCS0, V, Svalues] = setorbit(GoalOrbit, BPMFamily, BPMDevList, CMFamily, CMDevList, NIter, SVDIndex, BPMWeight);
  Data structure method:
  [CM, OCS0, V, Svalues] = setorbit(GoalOrbit, BPMstruct,             CMstruct,            NIter, SVDIndex, BPMWeight);
  Use cell arrays for multiple family correction (like coupled planes):
  [CM, OCS0, V, Svalues] = setorbit(GoalOrbitCell, BPMcell, CMcell, NIter, SVDIndex, BPMWeight);
  Note: BPMcell and CMcell must be a data structures when using cell arrays (GoalOrbitCell can be a cell or a string)
  Orbit Correction Structure (OCS) method:
  [CM, OCS0, V, Svalues] = setorbit(OCS, NIter, SVDIndex, BPMWeight);
  INPUTS
  1. GoalOrbit - Goal orbit (vector or cell array)
                'Golden' for the golden orbit {Default}
                'Offset' for the offset orbit
  2. BPM - BPM data structure (or cell array of structures)
     or BPMFamily and BPMDevList
  3. CM - Corrector magnet data structure (or cell array of structures)
     or CMFamily and CMDevList
  4. SVDIndex - vector, maximum number, 'All', or
                base on a threshold of min/max singular value {Default: 1e-3}
  5. NIter - Number of iterations  {Default: 1}
            (NIter can be 0, see note 1 below)
  6. BPMWeight - Weight applied to the BPMs (OCS.BPMWeight)
  7. FLAGS  - 'Abs' or 'Inc' - GoalOrbit is an absolute or incremental change {Default: 'Abs'}
                               ('Absolute' or 'Incremental' can also be used)
              'CorrectorGain', Gain - Scale the correction by Gain {Default: 1}
              'Display' - plot orbit information before applying the correction
              'FigureHandles' followed by a vector of 1 or 2 elements for figure handles and
                                                      4 or 8 elements for axes handles.
              'FitRF' or 'SetRF' - Fit and change the RF frequency
                   'GoldenDisp' - Use the golden dispersion {Default}
                   'MeasDisp'   - Measure the dispersion
                   'ModelDisp'  - Calculate the model dispersion
              'GetPV' or 'NoGetPV' - Get new data or use the data already in the OCS {Default: 'GetPV' (for the first iteration)}
                                     This allows one make a correction based on data already checked and analyzed.
                                     ('GetAM' or 'NoGetAM' does the same thing)
              'GoldenResp' or 'ModelResp' - Golden BPM response or calculate from the model {Default: 'GoldenResp'}
              'SetPV' or 'NoSetPV' - Set or don't set the correctors and RF {Default: 'SetSP'}
                                    'NoSetPV' does the calculation without making the correction.  That way one can
                                     take a look at the expected correction results before applying them.
                                     ('SetSP' or 'NoSetSP' does the same thing)
              'Tolerance', Tol - Quit correction if the std(error) < Tol {Tol: 0}
              'RampSteps', NSteps - Number of steps to ramp in the correction {NSteps: 1}
                                    This is used to avoid a large transient between setpoint changes.
                                    Note: NSteps is only used on the first iteration.
              'FitRF','SetRF','RFCorrector'                       - Set the RF frequency (Eta Column)
              'FitRFHCM0','FitRFEnergy','SetRFHCM0','SetRFEnergy' - Set the RF frequency (HCM energy constraint)
              'FitRFDeltaHCM0','SetRFDeltaHCM0'                   - Set the RF frequency (Delta HCM energy constraint)
              'FitRFDispersionOrbit','SetRFDispersionOrbit'       - Set the RF frequency (Dispersion orbit constraint)
              'FitRFDispersionHCM','SetRFDispersionHCM'           - Set the RF frequency (Dispersion correction constraint)
              The usual Units and Mode flags can also be used.
              Flags are not case sensitive
  OUTPUTS
  1. OCS    - New orbit correction structure (OCS)
  2. OCS0   - Starting OCS
  3. V      - Corrector magnet singular vectors
  4. Svalue - Singular values (vector)
  ALGORITHM
  SVD orbit correction:
  Decompose the response matrix, Rmat:
    [U, S, V] = svd(Rmat);
  The V matrix columns are the singular vectors in the corrector magnet space
  The U matrix columns are the singular vectors in the BPM space
    Rmat = U * S = Rmat * V
  Modify the response matrix by removing singular vector with small singular values
    Rmod = U(:,SVDIndex) * S(SVDIndex,SVDIndex) = Rmat * V(:,SVDIndex)
  Only project (least squares) on to the modified response matrix
    b = inv(Rmod'*Rmod)*Rmod' * (GoalOrbit - PresentOrbit);
  Or
    b = Rmod \ (GoalOrbit - PresentOrbit);
  The b coefficients are in terms of the singular vectors.
  The corrector strengths come from the linear combination of the singular vectors
    DeltaCM = V(:,SVDIndex) * b;
  ORBIT CORRECTION STRUCTURE (OCS)
    OCS.BPM (Data structure or cell array of data structures)
    OCS.CM  (Data structure or cell array of data structures)
    OCS.GoalOrbit
    OCS.NIter         - Number of correction iterations
    OCS.NCorrections  - Number of corrections actually done
    OCS.Tolerance     - Tolerance level to quit iterating
    OCS.RampSteps     - Number of steps to ramp in the each correction
    OCS.SVDIndex
    OCS.FitRF         - Methods for RF correction
                        1 Standard way with no constraints
                        2 Sum of the energy change to zero Also remove the
                          energy change due to the present corrector setpoints
                        3 Sum of the energy change to zero
                          remove energy change due to the incremental change in the correctors
                        4 Constraint: dot(DispersionX,   Smat * dHCM) = 0
                        5 Constraint: dot(HCM(Dispersion), dHCM) = 0
    OCS.RF
    OCS.DeltaRF
    OCS.Display
    OCS.Incremental   - GoalOrbit is an incremental change from the present (1) or absolute (0) {Default: 0}
    OCS.CorrectorGain - Scales the correction (usually used in slow feedback)
    OCS.BPMWeight     - Row    weights on the response matrix
    OCS.CMWeight      - Column weights on the response matrix
    OCS.Flags = {}
  EXAMPLES
  1. The default behavior us horizontal and vertical (coupled) orbit correction to the golden orbit
     setorbit;
     is equivalent to
     x = getx('struct');
     y = gety('struct');
     hcm = getsp('HCM','struct');
     vcm = getsp('VCM','struct');
     setorbit('Golden', {x,y}, {hcm,vcm});
  2. Horizontal orbit correction with the follow criterion:
     a. Correct to the golden orbit
     b. Use the first 10 singular values
     c. Display results
     x = getx([1 1;1 2;12 1; 13 4],'struct');
     hcm = getsp('HCM',[3 1;5 1;10 1],'struct');
     setorbit('Golden', x, hcm, 10, 'Display');
  3. Horizontal and vertical (coupled) orbit correction to the golden orbit (display results)
     x = getx([1 1;1 2;12 1; 13 4],'struct');
     y = gety([1 1;1 2;12 1; 13 4],'struct');
     hcm = getsp('HCM',[3 1;5 1;10 1],'struct');
     vcm = getsp('VCM',[3 1;4 1;9 1;10 1],'struct');
     setorbit('Golden', {x,y}, {hcm,vcm}, 'Display');
  NOTES
  1. Incremental orbit changes with more then one iteration are treated algorithmically
     just like absolute orbit changes.  For a 1 iteration incremental orbit change
     BPM data is not needed and hence not used.  However, if one uses the
     'Display' flag then BPM data is used to show results.  If BPM data is not
     available and one wants to still display corrector and estimated orbit
     information then use the special mode: 'Inc', 'Display', NIter=0.
  2. The 'Display' flag only displays the first iteration and the final result.
     Intermediate iterations (if used) are not displayed.
  3. If horizontal and vertical corrector are used, then the
     coupling terms in the response matrix will be used.
     To avoid using coupling terms, use separate calls.
  4. OCS0.CM.Data is the corrector strength before setorbit ran
     OCS.CM.Data  is the corrector strength after  setorbit ran
     Hence, DeltaCM = OCS.CM.Data - OCS0.CM.Data;
     However, if the 'NoSetSP' flag was used, then no correction was done and
     OCS.CM.Data=OCS0.CM.Data (ie, the present corrector strength).  To apply
     the correction, use OCS.CM.Data + OCS.CM.Delta
  See also orbitcorrectionmethods, setorbitbump, setorbitgui, rmdisp, plotcm
CROSS-REFERENCE INFORMATION
This function calls:
family2datastruct FAMILY2DATASTRUCTURE - Returns a datastructure corresponding to a Family
family2dev FAMILY2DEV - Return the device list for a family
family2status FAMILY2STATUS - Returns the device status
getdcct GETDCCT - returns the beam current
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getgolden GETGOLDEN - Returns the golden values for a family
gethbpmfamily GETHBPMFAMILY - Return the default horizontal BPM family
gethcmfamily GETHCMFAMILY - Returns the default horizontal corrector family
getmode GETMODE - Returns the present family mode ('Online', 'Simulator', 'Manual', 'Special', etc)
getoffset GETOFFSET - Returns the offset values for a family
getpv GETPV - Returns a variable from the online system or the model
getrf GETRF - Gets the RF frequency
getsp GETSP - Gets setpoint channels
getspos GETSPOS - Returns the longitudinal position in meters
getvbpmfamily GETVBPMFAMILY - Return the default vertical BPM family
getvcmfamily GETVCMFAMILY - Returns the default vertical corrector family
maxsp MAXSP - Maximum value of the setpoint
minsp MINSP - Minimum value of the setpoint
orbitcorrectionmethods ORBITCORRECTIONMETHODS - Some the orbit correction methods used on light sources
setpv SETPV - Setpoint change of the online system or model
steprf STEPRF - Increment change in the RF frequency
This function is called by:
setorbitbump SETORBITBUMP - Local bump program (uses setorbit)
SUBFUNCTIONS
function [StopFlag, OCS, Smat, S, U, V, FigureHandles, MorePlotsFlag] = answersetorbitcall(OCS, Smat, S, U, V, FigureHandles, InputFlags)
function [H, Haxis, OCS] = PreCorrectionDisplay(H, OCS0, OCS, Smat, S, U, V, NumberOfTrys, MorePlotsFlag, InputFlags)
function drawmoreplots(Haxis, OCS, Smat, S, U, V)
function PostCorrectionDisplay(H, OCS0, OCS, Smat, S, U, V, Iteration, NumberOfTrys, MorePlotsFlag, InputFlags)
SOURCE CODE
function [OCS, OCS0, V, S, ErrorFlag] = setorbit(varargin)
%SETORBIT - Orbit correction function
%  Family/DeviceList method:
%  [CM, OCS0, V, Svalues] = setorbit(GoalOrbit, BPMFamily, BPMDevList, CMFamily, CMDevList, NIter, SVDIndex, BPMWeight);
%
%  Data structure method:
%  [CM, OCS0, V, Svalues] = setorbit(GoalOrbit, BPMstruct,             CMstruct,            NIter, SVDIndex, BPMWeight);
%
%  Use cell arrays for multiple family correction (like coupled planes):
%  [CM, OCS0, V, Svalues] = setorbit(GoalOrbitCell, BPMcell, CMcell, NIter, SVDIndex, BPMWeight);
%  Note: BPMcell and CMcell must be a data structures when using cell arrays (GoalOrbitCell can be a cell or a string)
%
%  Orbit Correction Structure (OCS) method:
%  [CM, OCS0, V, Svalues] = setorbit(OCS, NIter, SVDIndex, BPMWeight);
%
%  INPUTS
%  1. GoalOrbit - Goal orbit (vector or cell array)
%                'Golden' for the golden orbit {Default}
%                'Offset' for the offset orbit
%  2. BPM - BPM data structure (or cell array of structures)
%     or BPMFamily and BPMDevList
%  3. CM - Corrector magnet data structure (or cell array of structures)
%     or CMFamily and CMDevList
%  4. SVDIndex - vector, maximum number, 'All', or
%                base on a threshold of min/max singular value {Default: 1e-3}
%  5. NIter - Number of iterations  {Default: 1}
%            (NIter can be 0, see note 1 below)
%  6. BPMWeight - Weight applied to the BPMs (OCS.BPMWeight)
%  7. FLAGS  - 'Abs' or 'Inc' - GoalOrbit is an absolute or incremental change {Default: 'Abs'}
%                               ('Absolute' or 'Incremental' can also be used)
%              'CorrectorGain', Gain - Scale the correction by Gain {Default: 1}
%              'Display' - plot orbit information before applying the correction
%              'FigureHandles' followed by a vector of 1 or 2 elements for figure handles and
%                                                      4 or 8 elements for axes handles.
%              'FitRF' or 'SetRF' - Fit and change the RF frequency
%                   'GoldenDisp' - Use the golden dispersion {Default}
%                   'MeasDisp'   - Measure the dispersion
%                   'ModelDisp'  - Calculate the model dispersion
%              'GetPV' or 'NoGetPV' - Get new data or use the data already in the OCS {Default: 'GetPV' (for the first iteration)}
%                                     This allows one make a correction based on data already checked and analyzed.
%                                     ('GetAM' or 'NoGetAM' does the same thing)
%              'GoldenResp' or 'ModelResp' - Golden BPM response or calculate from the model {Default: 'GoldenResp'}
%              'SetPV' or 'NoSetPV' - Set or don't set the correctors and RF {Default: 'SetSP'}
%                                    'NoSetPV' does the calculation without making the correction.  That way one can
%                                     take a look at the expected correction results before applying them.
%                                     ('SetSP' or 'NoSetSP' does the same thing)
%              'Tolerance', Tol - Quit correction if the std(error) < Tol {Tol: 0}
%              'RampSteps', NSteps - Number of steps to ramp in the correction {NSteps: 1}
%                                    This is used to avoid a large transient between setpoint changes.
%                                    Note: NSteps is only used on the first iteration.
%              'FitRF','SetRF','RFCorrector'                       - Set the RF frequency (Eta Column)
%              'FitRFHCM0','FitRFEnergy','SetRFHCM0','SetRFEnergy' - Set the RF frequency (HCM energy constraint)
%              'FitRFDeltaHCM0','SetRFDeltaHCM0'                   - Set the RF frequency (Delta HCM energy constraint)
%              'FitRFDispersionOrbit','SetRFDispersionOrbit'       - Set the RF frequency (Dispersion orbit constraint)
%              'FitRFDispersionHCM','SetRFDispersionHCM'           - Set the RF frequency (Dispersion correction constraint)
%              The usual Units and Mode flags can also be used.
%              Flags are not case sensitive
%
%  OUTPUTS
%  1. OCS    - New orbit correction structure (OCS)
%  2. OCS0   - Starting OCS
%  3. V      - Corrector magnet singular vectors
%  4. Svalue - Singular values (vector)
%
%  ALGORITHM
%  SVD orbit correction:
%  Decompose the response matrix, Rmat:
%    [U, S, V] = svd(Rmat);
%
%  The V matrix columns are the singular vectors in the corrector magnet space
%  The U matrix columns are the singular vectors in the BPM space
%    Rmat = U * S = Rmat * V
%
%  Modify the response matrix by removing singular vector with small singular values
%    Rmod = U(:,SVDIndex) * S(SVDIndex,SVDIndex) = Rmat * V(:,SVDIndex)
%
%  Only project (least squares) on to the modified response matrix
%    b = inv(Rmod'*Rmod)*Rmod' * (GoalOrbit - PresentOrbit);
%  Or
%    b = Rmod \ (GoalOrbit - PresentOrbit);
%
%  The b coefficients are in terms of the singular vectors.
%  The corrector strengths come from the linear combination of the singular vectors
%    DeltaCM = V(:,SVDIndex) * b;
%
%  ORBIT CORRECTION STRUCTURE (OCS)
%    OCS.BPM (Data structure or cell array of data structures)
%    OCS.CM  (Data structure or cell array of data structures)
%    OCS.GoalOrbit
%    OCS.NIter         - Number of correction iterations
%    OCS.NCorrections  - Number of corrections actually done
%    OCS.Tolerance     - Tolerance level to quit iterating
%    OCS.RampSteps     - Number of steps to ramp in the each correction
%    OCS.SVDIndex
%    OCS.FitRF         - Methods for RF correction
%                        1 Standard way with no constraints
%                        2 Sum of the energy change to zero Also remove the
%                          energy change due to the present corrector setpoints
%                        3 Sum of the energy change to zero
%                          remove energy change due to the incremental change in the correctors
%                        4 Constraint: dot(DispersionX,   Smat * dHCM) = 0
%                        5 Constraint: dot(HCM(Dispersion), dHCM) = 0
%    OCS.RF
%    OCS.DeltaRF
%    OCS.Display
%    OCS.Incremental   - GoalOrbit is an incremental change from the present (1) or absolute (0) {Default: 0}
%    OCS.CorrectorGain - Scales the correction (usually used in slow feedback)
%    OCS.BPMWeight     - Row    weights on the response matrix
%    OCS.CMWeight      - Column weights on the response matrix
%    OCS.Flags = {}
%
%  EXAMPLES
%  1. The default behavior us horizontal and vertical (coupled) orbit correction to the golden orbit
%     setorbit;
%     is equivalent to
%     x = getx('struct');
%     y = gety('struct');
%     hcm = getsp('HCM','struct');
%     vcm = getsp('VCM','struct');
%     setorbit('Golden', {x,y}, {hcm,vcm});
%
%  2. Horizontal orbit correction with the follow criterion:
%     a. Correct to the golden orbit
%     b. Use the first 10 singular values
%     c. Display results
%
%     x = getx([1 1;1 2;12 1; 13 4],'struct');
%     hcm = getsp('HCM',[3 1;5 1;10 1],'struct');
%     setorbit('Golden', x, hcm, 10, 'Display');
%
%  3. Horizontal and vertical (coupled) orbit correction to the golden orbit (display results)
%     x = getx([1 1;1 2;12 1; 13 4],'struct');
%     y = gety([1 1;1 2;12 1; 13 4],'struct');
%     hcm = getsp('HCM',[3 1;5 1;10 1],'struct');
%     vcm = getsp('VCM',[3 1;4 1;9 1;10 1],'struct');
%     setorbit('Golden', {x,y}, {hcm,vcm}, 'Display');
%
%  NOTES
%  1. Incremental orbit changes with more then one iteration are treated algorithmically
%     just like absolute orbit changes.  For a 1 iteration incremental orbit change
%     BPM data is not needed and hence not used.  However, if one uses the
%     'Display' flag then BPM data is used to show results.  If BPM data is not
%     available and one wants to still display corrector and estimated orbit
%     information then use the special mode: 'Inc', 'Display', NIter=0.
%  2. The 'Display' flag only displays the first iteration and the final result.
%     Intermediate iterations (if used) are not displayed.
%  3. If horizontal and vertical corrector are used, then the
%     coupling terms in the response matrix will be used.
%     To avoid using coupling terms, use separate calls.
%  4. OCS0.CM.Data is the corrector strength before setorbit ran
%     OCS.CM.Data  is the corrector strength after  setorbit ran
%     Hence, DeltaCM = OCS.CM.Data - OCS0.CM.Data;
%     However, if the 'NoSetSP' flag was used, then no correction was done and
%     OCS.CM.Data=OCS0.CM.Data (ie, the present corrector strength).  To apply
%     the correction, use OCS.CM.Data + OCS.CM.Delta
%
%  See also orbitcorrectionmethods, setorbitbump, setorbitgui, rmdisp, plotcm
%
%  Written by Greg Portmann
% Initialize
ErrorFlag = 0;
ExtraDelay = 0;
DefaultNIter = 1;
DefaultSVDIndex = 1e-4;
DefaultGoalOrbit = 'Golden';
DefaultFitRF = 0;
DefaultDisplay = 0;
DefaultCorrectorGain = 1;
RespFlag = 'GoldenResp';
DispFlag = 'GoldenDisp';
SetSPFlag = 1;
GetPVFlag = 1;
RF0 = [];
RF  = [];
FigHandles = [];
AxesHandles = [];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Input parsing and checking %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
IncrementalFlag = -1;
ModeFlag = '';
InputFlags = {};
OCSFlags = {};
DCCTLOW = .1; % A minimum stored current into the machine
% OCS init and defaults
OCS.BPM = [];
OCS.CM  = [];
OCS.GoalOrbit = DefaultGoalOrbit;
OCS.SVDIndex  = DefaultSVDIndex;
OCS.FitRF     = DefaultFitRF;
OCS.NIter     = DefaultNIter;
OCS.Display   = DefaultDisplay;
OCS.CorrectorGain = DefaultCorrectorGain;
OCS.Incremental = 0;
OCS.Tolerance = 0;
OCS.RampSteps = 1;
% First check if an OCS structure was input
OCSInputFlag = 0;
if length(varargin) >= 1
    if isstruct(varargin{1})
        if isfield(varargin{1},'BPM') && isfield(varargin{1},'CM')
            OCSInputFlag = 1;
            OCSin = varargin{1};
            varargin(1) = [];
            % Copy the input OSC on top of the defaults
            FieldCell = fieldnames(OCSin);
            for i = 1:length(FieldCell)
                OCS.(FieldCell{i}) = OCSin.(FieldCell{i});
            end
            % Attach the flags
            if isfield(OCS, 'Flags')
                varargin = [varargin OCS.Flags];
            end
        end
    end
end
for i = length(varargin):-1:1
    if isstruct(varargin{i})
        % Ignor structures
    elseif iscell(varargin{i})
        % Ignor cells
    elseif strcmpi(varargin{i},'Golden')
        % Use the golden orbit
        OCS.GoalOrbit = 'Golden';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Offset')
        % Use the offset orbit
        OCS.GoalOrbit = 'Offset';
        varargin(i) = [];
    elseif any(strcmpi(varargin{i},{'FitRF','SetRF','RFCorrector'}))
        %SetRFString = 'Set the RF frequency (Eta Column)';
        OCS.FitRF = 1;
        varargin(i) = [];
    elseif any(strcmpi(varargin{i},{'FitRFHCM0','FitRFEnergy','SetRFHCM0','SetRFEnergy'}))
        %SetRFString = 'Set the RF frequency (HCM energy constraint)';
        OCS.FitRF = 2;
        varargin(i) = [];
    elseif any(strcmpi(varargin{i},{'FitRFDeltaHCM0','SetRFDeltaHCM0'}))
        %SetRFString = 'Set the RF frequency (Delta HCM energy constraint)';
        OCS.FitRF = 3;
        varargin(i) = [];
    elseif any(strcmpi(varargin{i},{'FitRFDispersionOrbit','SetRFDispersionOrbit'}))
        %SetRFString = 'Set the RF frequency (Dispersion orbit constraint)';
        OCS.FitRF = 4;
        varargin(i) = [];
    elseif any(strcmpi(varargin{i},{'FitRFDispersionHCM','SetRFDispersionHCM'}))
        %SetRFString = 'Set the RF frequency (Dispersion correction constraint)';
        OCS.FitRF = 5;
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Display')
        OCS.Display = 1;
        varargin(i) = [];
    elseif strcmpi(varargin{i},'NoDisplay') || strcmpi(varargin{i},'No Display')
        OCS.Display = 0;
        varargin(i) = [];
    elseif strcmpi(varargin{i},'ModelResp')
        RespFlag = varargin{i};
        varargin(i) = [];
    elseif strcmpi(varargin{i},'GoldenResp')
        RespFlag = varargin{i};
        varargin(i) = [];
    elseif strcmpi(varargin{i},'ModelDisp')
        DispFlag = varargin{i};
        varargin(i) = [];
    elseif strcmpi(varargin{i},'MeasDisp')
        DispFlag = varargin{i};
        varargin(i) = [];
    elseif strcmpi(varargin{i},'GoldenDisp')
        DispFlag = varargin{i};
        varargin(i) = [];
    elseif any(strcmpi(varargin{i},{'Inc','Incremental'}))
        OCS.Incremental = 1;
        varargin(i) = [];
    elseif any(strcmpi(varargin{i},{'Abs','Absolute'}))
        OCS.Incremental = 0;
        varargin(i) = [];
    elseif any(strcmpi(varargin{i},{'SetPV','SetSP'}))
        SetSPFlag = 1;
        varargin(i) = [];
    elseif any(strcmpi(varargin{i},{'NoSetPV','NoSetSP'}))
        SetSPFlag = 0;
        varargin(i) = [];
    elseif any(strcmpi(varargin{i},{'GetPV','GetAM'}))
        GetPVFlag = 1;
        varargin(i)   = [];
    elseif any(strcmpi(varargin{i},{'NoGetPV','NoGetAM'}))
        GetPVFlag = 0;
        varargin(i)   = [];
    elseif strcmpi(varargin{i},'Simulator') || strcmpi(varargin{i},'Model')
        ModeFlag = 'Simulator';
        %OCSFlags = [OCSFlags varargin(i)];    % Don't maintain the mode field, it must be on the input field
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Online')
        ModeFlag = 'Online';
        %OCSFlags = [OCSFlags varargin(i)];    % Don't maintain the mode field, it must be on the input field
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Manual')
        ModeFlag = 'Manual';
        %OCSFlags = [OCSFlags varargin(i)];    % Don't maintain the mode field, it must be on the input field
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'physics')
        OCSFlags = [OCSFlags varargin(i)];
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'hardware')
        OCSFlags = [OCSFlags varargin(i)];
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'FigureHandles')
        OCS.Display = 1;
        FigHandles = varargin{i+1};
        if ~any(length(FigHandles) == [1 2  3 6])
            error('Figure handles must be of length 1 or 2 for figures or 3 or 6 for axes.');
        end
        varargin(i+1) = [];
        varargin(i)   = [];
    elseif strcmpi(varargin{i},'CorrectorGain')
        OCS.CorrectorGain = varargin{i+1};
        varargin(i+1) = [];
        varargin(i)   = [];
    elseif strcmpi(varargin{i},'Tolerance')
        OCS.Tolerance = varargin{i+1};
        varargin(i+1) = [];
        varargin(i)   = [];
    elseif strcmpi(varargin{i},'RampSteps')
        OCS.RampSteps = varargin{i+1};
        varargin(i+1) = [];
        varargin(i)   = [];
    elseif strcmpi(varargin{i},'Archive')
        % Just remove
        varargin(i) = [];
    elseif strcmpi(varargin{i},'NoArchive')
        % Just remove
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Struct')
        % Just remove
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Numeric')
        % Just remove
        varargin(i) = [];
    end
end
OCSFlags = [OCSFlags {RespFlag} {DispFlag}];
if ~OCSInputFlag
    if iscell(varargin{1})
        if isstruct(varargin{1}{1})
            % BPM, CM
            if length(varargin) < 2
                error('Input parsing problem');
            end
            if ~iscell(varargin{1}) || ~iscell(varargin{2})
                error('When using cell arrays BPM and CM inputs must all be cell arrays');
            end
            OCS.BPM = varargin{1};
            OCS.CM = varargin{2};
            varargin(1:2) = [];
        else
            % GoalOrbit, BPM, CM
            if length(varargin) < 3
                error('Input parsing problem');
            end
            OCS.GoalOrbit = varargin{1};
            if ~iscell(varargin{2}) || ~iscell(varargin{3})
                error('When using cell arrays BPM and CM inputs must all be cell arrays');
            end
            OCS.BPM = varargin{2};
            OCS.CM = varargin{3};
            varargin(1:3) = [];
        end
    elseif isstruct(varargin{1})
        % BPM and CM are structures, Golden orbit is not
        % Golden orbit could have been a string which has already been removed
        if length(varargin) < 2
            error('Input parsing problem: BPM and/or CM not found');
        end
        OCS.BPM = varargin{1};
        varargin(1) = [];
        if ischar(OCS.BPM)
            FamilyName = OCS.BPM;
            DeviceList = varargin{1};
            if length(varargin) < 1
                error('BPM device list must exist');
            end
            varargin(1) = [];
            OCS.BPM = family2datastruct(FamilyName, DeviceList);
        end
        OCS.CM = varargin{1};
        varargin(1) = [];
        if ischar(OCS.CM)
            FamilyName = OCS.CM;
            if length(varargin) < 1
                error('Corrector magnet device list must exist');
            end
            DeviceList = varargin{1};
            varargin(1) = [];
            OCS.CM = getsp(FamilyName, DeviceList, 'struct');
        end
    else
        if isnumeric(varargin{1})
            if length(varargin) < 3
                error('Input parsing problem: GoalOrbit, BPM, CM not all found');
            end
            OCS.GoalOrbit = varargin{1};
            varargin(1) = [];
        else
            if length(varargin) < 2
                error('Input parsing problem: BPM and/or CM not found');
            end
        end
        OCS.BPM = varargin{1};
        varargin(1) = [];
        if ischar(OCS.BPM)
            FamilyName = OCS.BPM;
            if isnumeric(varargin{1})
                DeviceList = varargin{1};
                varargin(1) = [];
            else
                DeviceList = [];
            end
            if length(varargin) < 1
                error('BPM device list must exist');
            end
            OCS.BPM = family2datastruct(FamilyName, DeviceList);
        end
        OCS.CM = varargin{1};
        varargin(1) = [];
        if ischar(OCS.CM)
            FamilyName = OCS.CM;
            if length(varargin) < 1
                error('Corrector magnget device list must exist');
            end
            if isnumeric(varargin{1})
                DeviceList = varargin{1};
                varargin(1) = [];
            else
                DeviceList = [];
            end
            OCS.CM = getsp(FamilyName, DeviceList, 'struct');
        end
    end
end
% Get NIter
if length(varargin) >= 1
    OCS.NIter = varargin{1};
    varargin(1) = [];
end
if isempty(OCS.NIter)
    OCS.NIter = DefaultNIter;
end
% Get SVDIndex
if length(varargin) >= 1
    OCS.SVDIndex = varargin{1};
    varargin(1) = [];
end
if isempty(OCS.SVDIndex)
    OCS.SVDIndex = DefaultSVDIndex;
end
% Get BPMWeight
if length(varargin) >= 1
    OCS.BPMWeight = varargin{1};
    varargin(1) = [];
end
% Check BPM field
if isempty(OCS.BPM)
    OCS.BPM = {gethbpmfamily, getvbpmfamily};
end
% Check CM field
if isempty(OCS.CM)
    OCS.CM = {gethcmfamily,  getvcmfamily};
end
% Check the Display field
if isempty(OCS.Display)
    OCS.Display = DefaultDisplay;
end
% Check the corrector gain
if isempty(OCS.CorrectorGain)
    OCS.CorrectorGain = DefaultCorrectorGain;
end
% Check NIter
if OCS.Incremental
    if ~OCS.Display && OCS.NIter == 1
        % Use OCS.NIter=0, since BPM data is not needed
        OCS.NIter = 0;
    end
else
    if OCS.NIter == 0
        error('Number of iterations cannot be zero for absolute orbit changes');
    end
end
% Make cell arrays if they are not already
if ~iscell(OCS.BPM)
    NoCellBPMFlag = 1;
    OCS.BPM = {OCS.BPM};
else
    NoCellBPMFlag = 0;
end
if ~iscell(OCS.CM)
    NoCellCMFlag = 1;
    OCS.CM = {OCS.CM};
    if isfield(OCS, 'CMWeight') && ~iscell(OCS.CMWeight)
        OCS.CMWeight = {OCS.CMWeight};
    end
else
    NoCellCMFlag = 0;
end
% Attach the flags
OCS.Flags = OCSFlags;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End input parsing and checking %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Check for good status if online %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for i = 1:length(OCS.BPM)
    if strcmpi(getmode(OCS.BPM{i}),'Online')
        [S, IndexList] = family2status(OCS.BPM{i});
        if find(S==0)
            tmp = questdlg({sprintf(...
                'BPM family %s is showing %d element(s) with bad status.', OCS.BPM{i}.FamilyName, length(find(S==0))), ...
                'Do you want to continue with orbit correction?'},...
                'SETORBIT','YES','NO','NO');
            if ~strcmpi(tmp,'YES')
                return
            end
        end
    end
end
for i = 1:length(OCS.CM)
    if strcmpi(getmode(OCS.CM{i}),'Online')
        [S, IndexList] = family2status(OCS.CM{i});
        if find(S==0)
            tmp = questdlg({sprintf(...
                'Corrector family %s is showing %d element(s) with bad status.', OCS.CM{i}.FamilyName, length(find(S==0))), ...
                'Do you want to continue with orbit correction?'},...
                'SETORBIT','YES','NO','NO');
            if ~strcmpi(tmp,'YES')
                return
            end
        end
    end
end
% Check BPMWeight
if ~isfield(OCS, 'BPMWeight')
    for i = 1:length(OCS.BPM)
        OCS.BPMWeight{i} = [];
    end
end
if ~iscell(OCS.BPMWeight)
    OCS.BPMWeight = {OCS.BPMWeight};
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Build the goal orbit cell %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ischar(OCS.GoalOrbit)
    GoalOrbitFlag = OCS.GoalOrbit;
    OCS.GoalOrbit = [];
    for i = 1:length(OCS.BPM)
        if strcmpi(GoalOrbitFlag,'Golden')
            tmp = getgolden(OCS.BPM{i}, 'Numeric');
        elseif strcmpi(GoalOrbitFlag,'Offset')
            tmp = getoffset(OCS.BPM{i}, 'Numeric');
        else
            error('Only golden and offset orbits are known')
        end
        OCS.GoalOrbit{i} = tmp;
    end
end
if ~iscell(OCS.GoalOrbit)
    OCS.GoalOrbit = {OCS.GoalOrbit};
end
%%%%%%%%%%%%%%%%%%%%%%
% End of Input Setup %
%%%%%%%%%%%%%%%%%%%%%%
% Save the starting RF frequency
if GetPVFlag
    OCS.RF = getrf('Struct', InputFlags{:});
end
% Number of iterations (OCS.NIter can be 0 for display reasons with increment changes)
if OCS.NIter == 0
    NumberOfTrys = 1;
else
    NumberOfTrys = OCS.NIter;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Build the starting orbit %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for i = 1:length(OCS.BPM)
    if OCS.NIter == 0
        % Don't use BPM data for zero interations
        OCS.BPM{i}.Data = zeros(size(OCS.BPM{i}.DeviceList,1),1);
    else
        if GetPVFlag
            % Get new BPM data if not in calculate mode
            OCS.BPM{i} = getpv(OCS.BPM{i}, 'Struct', InputFlags{:});
        end
    end
end
% For increment changes, convert the goal orbit to an absolute orbit
if OCS.Incremental
    for i = 1:length(OCS.GoalOrbit)
        OCS.GoalOrbit{i} = OCS.GoalOrbit{i} + OCS.BPM{i}.Data;
    end
    % The incremental flag is always zero on exit because the orbits are absolute at this point
    OCS.Incremental = 0;
end
% Interactively select singular value
SVDquestion = 'Select Again';
MorePlotsFlag = 0;
while strcmp(SVDquestion,'Select Again')
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Build the starting orbit %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    for i = 1:length(OCS.BPM)
        if OCS.NIter == 0
            % Don't use BPM data for zero interations
            OCS.BPM{i}.Data = zeros(size(OCS.BPM{i}.DeviceList,1),1);
        else
            if GetPVFlag
                % Get new BPM data if not in calculate mode
                OCS.BPM{i} = getpv(OCS.BPM{i}, 'Struct', InputFlags{:});
            end
        end
    end
    % Get the present setpoints
    if GetPVFlag
        OCS.CM = getpv(OCS.CM, 'Struct', InputFlags{:});
    end
    % Compute the correction
    [OCS, Smat, S, U, V] = orbitcorrectionmethods(OCS);
    % Save the starting OCS (with possible CM & BPM list changes)
    OCS0 = OCS;
    if OCS.Display  % || length(FigHandles>=3)
        [FigHandles, AxesHandles, OCS] = PreCorrectionDisplay(FigHandles, OCS0, OCS, Smat, S, U, V, NumberOfTrys, MorePlotsFlag, InputFlags);
    else
        SVDquestion = 'Correct Orbit';
    end
    if SetSPFlag && OCS.Display && length(FigHandles)<3
        Units = get(0,'units');
        if strcmpi(Units, 'Normalized')
            fprintf('   Setting the command window units to pixels since the menu command fails with normalized units.\n');
            set(0,'units','pixels');
        end
        if MorePlotsFlag == 0
            tmp = menu('', ...
                'Apply orbit correction', ...
                'Change the number of singular values', ...
                'Change the BPMs', ...
                'Change the correctors', ...
                'Plot more information (AT Model required)', ...
                'Exit - No orbit correction');
        else
            tmp = menu('', ...
                'Apply orbit correction', ...
                'Change the number of singular values', ...
                'Change the BPMs', ...
                'Change the correctors', ...
                'Close "more information plot"', ...
                'Exit - No orbit correction');
        end
        if tmp == 6
            fprintf('   Orbit not corrected\n');
            SVDquestion = 'Correct not corrected';
            SetSPFlag = 0;
        elseif tmp == 1
            SVDquestion = 'Correct Orbit';
        elseif tmp == 2
            % Change the singular values
            def = {sprintf('[%d:%d]',OCS.SVDIndex(1),OCS.SVDIndex(end))};
            answer=inputdlg({'Which singular values:'}, 'SETORBIT', 1, def);
            if ~isempty(answer)
                tmp = str2num(answer{1});
                % Test for out-ot-range
                if all(tmp<=size(V,2)) && ~isempty(tmp)
                    OCS.SVDIndex = tmp;
                else
                    fprintf('   Singular value selection out-of-range.  Select again and try a new range.\n');
                end
            end
        elseif tmp == 3
            % Change BPMs
            for i = 1:length(OCS.BPM)
                List0 = OCS.BPM{i}.DeviceList;
                ListTotal = family2dev(OCS.BPM{i}.FamilyName);
                j = findrowindex(OCS.BPM{i}.DeviceList, ListTotal);
                CheckedList = zeros(size(ListTotal,1),1);
                CheckedList(j) = 1;
                OCS.BPM{i}.DeviceList = editlist(ListTotal, OCS.BPM{i}.FamilyName, CheckedList);
                [j,jNotFound] = findrowindex(OCS.BPM{i}.DeviceList, List0);
                if isempty(jNotFound)
                    OCS.GoalOrbit{i} = OCS.GoalOrbit{i}(j);
                    if ~isempty(OCS.BPMWeight{i}) && isvector(OCS.BPMWeight{i})
                        OCS.BPMWeight{i} = OCS.BPMWeight{i}(j);
                    end
                else
                    % New BPMs were added
                    if any(strcmpi(OCS.Flags,'Golden'))
                        OCS.GoalOrbit{i} = getgolden(OCS.BPM{i}, 'Numeric');
                    elseif any(strcmpi(OCS.Flags,'Offset'))
                        OCS.GoalOrbit{i} = getoffset(OCS.BPM{i}, 'Numeric');
                    else
                        error('Unknown goal orbit for the new BPMs');
                    end
                    if ~isempty(OCS.BPMWeight{i})
                        if all(OCS.BPMWeight{i} == max(OCS.BPMWeight{i}))
                            % If all the weights are the same, then the new BPMs get the same weight
                            OCS.BPMWeight{i} = OCS.BPMWeight{i}(1) * ones(size(OCS.BPM{i}.DeviceList,1),1);
                        else
                            error('Unknown BPM weights for new BPMs');
                        end
                    end
                end
            end
        elseif tmp == 4
            % Change correctors
            for i = 1:length(OCS.CM)
                ListTotal = family2dev(OCS.CM{i}.FamilyName);
                j = findrowindex(OCS.CM{i}.DeviceList, ListTotal);
                CheckedList = zeros(size(ListTotal,1),1);
                CheckedList(j) = 1;
                OCS.CM{i}.DeviceList = editlist(ListTotal, OCS.CM{i}.FamilyName, CheckedList);
            end
        elseif tmp == 5
            if MorePlotsFlag == 0
                MorePlotsFlag = 1;
            else
                MorePlotsFlag = 0;
                close(FigHandles(2));
                FigHandles = [FigHandles(1); NaN];
                % Make figure 1 a little wider
                p = get(FigHandles(1), 'Position');
                set(FigHandles(1), 'Position', [p(1)-.1*p(3) p(2) p(3)+.1*p(3) p(4)]);
            end
        end
    else
        SVDquestion = 'Get out of loop';
    end
end
%%%%%%%%%%%%%%%%%%%%%%
% Exit if ~SetSPFlag %
%%%%%%%%%%%%%%%%%%%%%%
if ~SetSPFlag
    %% Put Delta into OCS.CM (don't do this since setorbit can be called multiple times before correcting)
    %for i = 1:length(OCS.CM)
    %    OCS.CM{i}.Data = OCS.CM{i}.Data + OCS.CM{i}.Delta;
    %end
    %if OCS.FitRF
    %    OCS.RF.Data = OCS.RF.Data + OCS.DeltaRF;
    %end
    % Remove the cell array if it was not input as a cell array
    if NoCellBPMFlag
        OCS.BPM = OCS.BPM{1};
        OCS0.BPM = OCS0.BPM{1};
        OCS.GoalOrbit = OCS.GoalOrbit{1};
        OCS0.GoalOrbit = OCS0.GoalOrbit{1};
        OCS.BPMWeight = OCS.BPMWeight{1};
        OCS0.BPMWeight = OCS0.BPMWeight{1};
    end
    if NoCellCMFlag
        OCS.CM = OCS.CM{1};
        OCS0.CM = OCS0.CM{1};
        if isfield(OCS, 'CMWeight')
            OCS.CMWeight = OCS.CMWeight{1};
            OCS0.CMWeight = OCS0.CMWeight{1};
        end
    end
    return;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Iterate on orbit correction %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ~isfield(OCS, 'MinimumPeriod')
    OCS.MinimumPeriod = 0;
end
if isempty(OCS.MinimumPeriod)
    OCS.MinimumPeriod = 0;
end
% Running flag
RingSetOrbit.RunFlag = 1;
setappdata(0, 'RingSetOrbit', RingSetOrbit);
OCS.NCorrections = 0;
for iloop = 1:NumberOfTrys
    tic;
    % The 1st iteration is already computed
    if iloop > 1
        % Build the new starting orbit
        for i = 1:length(OCS.BPM)
            OCS.BPM{i} = getpv(OCS.BPM{i}, 'Struct', InputFlags{:});
        end
        % Compute the correction
        OCS = orbitcorrectionmethods(OCS, Smat, S, U, V);
    end
    % Tolerance check
    for i = 1:length(OCS.BPM)
        TolFlag(i) = std(OCS.BPM{i}.Data(:) - OCS.GoalOrbit{i}(:)) < OCS.Tolerance;
    end
    if all(TolFlag)
        break;
    end
    % Put Delta into OCS.CM & OCS.RF
    for i = 1:length(OCS.CM)
        OCS.CM{i}.Data = OCS.CM{i}.Data + OCS.CorrectorGain * OCS.CM{i}.Delta;
    end
    if OCS.FitRF
        OCS.RF.Data = OCS.RF.Data + OCS.CorrectorGain * OCS.DeltaRF;
    end
    % Check corrector power supply limits
    for i = 1:length(OCS.CM)
        MinSP = minsp(OCS.CM{i});
        MaxSP = maxsp(OCS.CM{i});
        % Since the Max or Min sign is really arbitary, any(OCS.CM{i}.Data > MaxSP) will not work
        % For instance, a max in hardware units can be a min in physics units.
        % It's better to check if it's between the max and min
        [Tmp, SortIndex] = sort([MinSP OCS.CM{i}.Data MaxSP],2);
        if any(SortIndex(:,2) ~= 2)
            icm = find(SortIndex(:,2) ~= 2);
            for j = 1:length(icm)
                fprintf('   Setting %s(%d,%d) to %f would exceed [%f %f] %s range.\n', OCS.CM{i}.FamilyName, OCS.CM{i}.DeviceList(icm(j),:), OCS.CM{i}.Data(icm(j)), MinSP(icm(j)), MaxSP(icm(j)), OCS.CM{i}.UnitsString);
            end
            fprintf('   Orbit correction stopped on iteration %d.\n   A power supply limit would have been exceeded!\n', iloop);
            RingSetOrbit.RunFlag = 0;
            setappdata(0, 'RingSetOrbit', RingSetOrbit);
            ErrorFlag = 1;
            break;
            %return;
        end
    end
    if ErrorFlag
        break;
    end
    %if OCS.Display
    %    if OCS.NIter > 1
    %        fprintf('   Iteration %d. Changing the correctors (%s)\n', iloop, datestr(clock, 0));
    %        if OCS.FitRF
    %            fprintf('   Iteration %d. Changing the RF frequency by %d %s\n', iloop, OCS.DeltaRF, OCS.RF.UnitsString);
    %        end
    %    else
    %        fprintf('   Setting the correctors (%s)\n', datestr(clock, 0));
    %        if OCS.FitRF
    %            fprintf('   Changing the RF frequency by %d %s (%s)\n', OCS.DeltaRF, OCS.RF.UnitsString, datestr(clock, 0));
    %        end
    %    end
    %end
    % Since power supplies get out of sync, it can be useful
    % to set the power supplies in smaller steps.
    if OCS.RampSteps == 1 || iloop > 1
        % Apply correction in 1 step
        % Set the RF frequency
        if OCS.FitRF
            steprf(OCS.DeltaRF, -1, InputFlags{:});
        end
        % Set the correctors in one step
        setpv(OCS.CM, -2, InputFlags{:});
    else
        % Apply correction slowly
        CM  = OCS.CM;
        CM1 = getpv(OCS.CM,'Struct');
        CM2 = OCS.CM;
        if OCS.FitRF
            dRF = OCS.DeltaRF / OCS.RampSteps;
        end
        for j = 1:OCS.RampSteps
            if j == OCS.RampSteps
                WaitFlag = -2;
            else
                WaitFlag = -1;
            end
            if OCS.FitRF
                steprf(dRF, -1, InputFlags{:});
            end
            for i = 1:length(OCS.CM)
                CM{i}.Data = CM1{i}.Data + (CM2{i}.Data - CM1{i}.Data)*(j/OCS.RampSteps);
                setpv(CM{i}, WaitFlag, InputFlags{:});
            end
        end
    end
    OCS.NCorrections = iloop;            % Count the actual number of corrections made
    sleep(ExtraDelay);
1000     %%%%%%%%%%%%%%%%%%%%%%%%%
1001     % Build the final orbit %
1002     %%%%%%%%%%%%%%%%%%%%%%%%%
1003     for i = 1:length(OCS.BPM)
1004         if OCS.NIter > 0
1005             OCS.BPM{i}.Data = getpv(OCS.BPM{i}, 'Numeric', InputFlags{:});
1006         end
1007     end
1008
1009
1010     % Get the present setpoints
1011     % Some accelerators might have digitizing errors that gets picked up with a reread
1012     OCS.CM = getpv(OCS.CM, 'Struct', InputFlags{:});
1013
1014     if OCS.FitRF
1015         OCS.RF = getrf('Struct', InputFlags{:});
1016     end
1017
1018
1019     % Display final result if OCS.Display, more than 0 iterations, and a setpoint change was made
1020     %if (OCS.Display | length(FigHandles>=4)) & OCS.NIter & SetSPFlag
1021     if OCS.Display && OCS.NIter && SetSPFlag
1022         PostCorrectionDisplay(AxesHandles, OCS0, OCS, Smat, S, U, V, iloop, NumberOfTrys, MorePlotsFlag, InputFlags);
1023     end
1024
1025     % Update timestamp
1026     if OCS.Display && isfield(OCS,'Handles') && isfield(OCS.Handles, 'TimeStamp') && ~isempty(OCS.Handles.TimeStamp)
1027         set(OCS.Handles.TimeStamp, 'String', datestr(clock,0));
1028         drawnow;
1029     end
1030
1031
1032     if iloop ~= NumberOfTrys
1033         % Check if another application is trying to change a setting
1034         [StopFlag, OCS, Smat, S, U, V, AxesHandles, MorePlotsFlag] = answersetorbitcall(OCS, Smat, S, U, V, AxesHandles, InputFlags);
1035         if StopFlag
1036             break;
1037         end
1038
1039
1040         % Check beam current (this might be machine dependent)
1041         if getdcct < DCCTLOW
1042             fprintf('   Orbit correction stopped on iteration %d.   Beam current is below .05 milliampere!\n', iloop);
1043             break;
1044         end
1045
1046
1047         % Set the minimum update period
1048         while toc < OCS.MinimumPeriod
1049             if (OCS.MinimumPeriod-toc) > .3
1050                 sleep(.3);
1051             else
1052                 sleep(OCS.MinimumPeriod - toc);
1053             end
1054
1055             % Check for a stop request or change to the minimum update period
1056             [StopFlag, OCS, Smat, S, U, V, AxesHandles, MorePlotsFlag] = answersetorbitcall(OCS, Smat, S, U, V, AxesHandles, InputFlags);
1057             if StopFlag
1058                 break;
1059             end
1060         end
1061     end
1062 end
1063
1064
1065 % Orbit correction finished
1066 RingSetOrbit.RunFlag = 0;
1067 setappdata(0, 'RingSetOrbit', RingSetOrbit);
1068
1069
1070 % For multiple iterations put the total change in the .Delta & .DeltaRF fields
1071 for i = 1:length(OCS.CM)
1072     OCS.CM{i}.Delta = OCS.CM{i}.Data - OCS0.CM{i}.Data;
1073 end
1074 if OCS.FitRF
1075     OCS.DeltaRF = OCS.RF.Data - OCS0.RF.Data;
1076 end
1077
1078
1079 % Remove the cell array if the input was not a cell
1080 if NoCellBPMFlag
1081     OCS.BPM = OCS.BPM{1};
1082     OCS0.BPM = OCS0.BPM{1};
1083
1084     OCS.GoalOrbit = OCS.GoalOrbit{1};
1085     OCS0.GoalOrbit = OCS0.GoalOrbit{1};
1086
1087     OCS.BPMWeight = OCS.BPMWeight{1};
1088     OCS0.BPMWeight = OCS0.BPMWeight{1};
1089 end
1090 if NoCellCMFlag
1091     OCS.CM = OCS.CM{1};
1092     OCS0.CM = OCS0.CM{1};
1093
1094     if isfield(OCS, 'CMWeight')
1095         OCS.CMWeight = OCS.CMWeight{1};
1096         OCS0.CMWeight = OCS0.CMWeight{1};
1097     end
1098 end
1099
1100
1101 % if OCS.Display
1102 %     fprintf('   Orbit correction complete (%s)\n', datestr(clock, 0));
1103 % end
1104
1105
1106 %%%%%%%%%%%%%%%%%%%
1107 % End of Setorbit %
1108 %%%%%%%%%%%%%%%%%%%
1109
1110
1111
1112 %%%%%%%%%%%%%%%%%%%%%%%%%%
1113 % Ring/Answer Subroutine %
1114 %%%%%%%%%%%%%%%%%%%%%%%%%%
1115 function [StopFlag, OCS, Smat, S, U, V, FigureHandles, MorePlotsFlag] = answersetorbitcall(OCS, Smat, S, U, V, FigureHandles, InputFlags)
1116
1117 StopFlag = 0;
1118 MorePlotsFlag = 0;
1119 RingSetOrbit = getappdata(0, 'RingSetOrbit');
1120
1121 if ~isempty(RingSetOrbit)
1122
1123     if isfield(RingSetOrbit, 'RunFlag')
1124         if RingSetOrbit.RunFlag == -1
1125             StopFlag = 1;
1126         end
1127         %RingSetOrbit = rmfield(RingSetOrbit, 'RunFlag');
1128         %setappdata(0, 'RingSetOrbit', RingSetOrbit);
1129     end
1130
1131     if isfield(RingSetOrbit, 'MinimumPeriod')
1132         OCS.MinimumPeriod = RingSetOrbit.MinimumPeriod;
1133         if isempty(OCS.MinimumPeriod)
1134             OCS.MinimumPeriod = 0;
1135         end
1136         RingSetOrbit = rmfield(RingSetOrbit, 'MinimumPeriod');
1137         setappdata(0, 'RingSetOrbit', RingSetOrbit);
1138     end
1139
1140     if isfield(RingSetOrbit, 'Display')
1141         OCS.Display = RingSetOrbit.Display;
1142         RingSetOrbit = rmfield(RingSetOrbit, 'Display');
1143         setappdata(0, 'RingSetOrbit', RingSetOrbit);
1144     end
1145
1146     if isfield(RingSetOrbit, 'CorrectorGain')
1147         OCS.CorrectorGain = RingSetOrbit.CorrectorGain;
1148         RingSetOrbit = rmfield(RingSetOrbit, 'CorrectorGain');
1149         setappdata(0, 'RingSetOrbit', RingSetOrbit);
1150     end
1151
1152     if isfield(RingSetOrbit, 'FigureHandles')
1153         FigureHandles = RingSetOrbit.FigureHandles;
1154         RingSetOrbit = rmfield(RingSetOrbit, 'FigureHandles');
1155         setappdata(0, 'RingSetOrbit', RingSetOrbit);
1156
1157         if length(FigureHandles) == 6
1158             drawmoreplots(FigureHandles(4:6), OCS, Smat, S, U, V);
1159             %MorePlotsFlag = 1;
1160         end
1161     end
1162
1163
1164     if isfield(RingSetOrbit, 'FitRF')
1165         OCS.FitRF = RingSetOrbit.FitRF;
1166         RingSetOrbit = rmfield(RingSetOrbit, 'FitRF');
1167         setappdata(0, 'RingSetOrbit', RingSetOrbit);
1168
1169         if OCS.FitRF == 1
1170             % Include the RF frequency next time
1171             OCS.RF = getrf('Struct', InputFlags{:});
1172             [OCS, Smat, S, U, V] = orbitcorrectionmethods(OCS);  % Get new S, U, V matrices
1173         else
1174             % Don't include the RF frequency next time
1175             OCS.FitRF = 0;
1176             [OCS, Smat, S, U, V] = orbitcorrectionmethods(OCS);  % Get new S, U, V matrices
1177         end
1178     end
1179
1180 end
1181
1182
1183
1184 %%%%%%%%%%%%%%%%%%%%%%%%%%%
1185 %  Pre-correction display %
1186 %%%%%%%%%%%%%%%%%%%%%%%%%%%
1187 function [H, Haxis, OCS] = PreCorrectionDisplay(H, OCS0, OCS, Smat, S, U, V, NumberOfTrys, MorePlotsFlag, InputFlags)
1188
1189 % Build the orbit vector
1190 StartOrbitVec = [];
1191 Orbit0Vec = [];
1192 GoalOrbitVec = [];
1193 BPMWeight = [];
1194 for i = 1:length(OCS.BPM)
1195     StartOrbitVec = [StartOrbitVec; OCS.BPM{i}.Data];
1196     Orbit0Vec     = [Orbit0Vec;     OCS.BPM{i}.Data];
1197     GoalOrbitVec  = [GoalOrbitVec;  OCS.GoalOrbit{i}];
1198
1199     if isempty(OCS.BPMWeight{i})
1200         BPMWeight = [BPMWeight; ones(length(OCS.BPM{i}.Data),1)];
1201     else
1202         BPMWeight = [BPMWeight; OCS.BPMWeight{i}(:)];
1203     end
1204 end
1205
1206 % Plot some stuff
1207 L = getfamilydata('Circumference');
1208 if isempty(L)
1209     global THERING
1210     L = findspos(THERING, length(THERING)+1);
1211 end
1212
1213
1214 if isempty(H)
1215     HCF = get(0, 'CurrentFigure');
1216     if isempty(HCF)
1217         H = [gcf; NaN];
1218     else
1219         if rem(HCF,1)==0
1220             H = [HCF(1); NaN];
1221         else
1222             H = [figure; NaN];
1223         end
1224     end
1225     %drawnow
1226     subfig(2,2,2, H(1));
1227     p = get(H(1), 'Position');
1228     set(H(1), 'Position', [p(1) p(2)-.8*p(4) p(3) p(4)+.8*p(4)]);
1229 end
1230
1231
1232 if length(H) < 3
1233     figure(H(1));
1234     clf reset
1235     Haxis(1) = subplot(3,1,1);
1236     Haxis(2) = subplot(3,1,2);
1237     Haxis(3) = subplot(3,1,3);
1238     yaxesposition(1.05);
1239     orient portrait
1240 else
1241     Haxis = H;
1242 end
1243
1244
1245 ColorOrderMat = get(gca,'ColorOrder');
1246
1247
1248 %%%%%%%%%%%%%%%%%%%%%%%
1249 % Change in corrector %
1250 %%%%%%%%%%%%%%%%%%%%%%%
1251 axes(Haxis(1));
1252 for i4 = 1:length(OCS.CM)
1253     CMpos = getspos(OCS.CM{i4});
1254     [CMpos,isort] = sort(CMpos);
1255
1256     % Percentage from max
1257     %CMmax = maxsp(OCS.CM{i4});
1258     %plot(CMpos, 100*OCS.CM{i4}.Delta./CMmax, '.-','Color', ColorOrderMat(mod(i4,size(ColorOrderMat,1)),:));
1259     %%plot(CMpos, 100*OCS.CM{i4}.Delta./CMmax,'-square','Color', ColorOrderMat(mod(i4,size(ColorOrderMat,1)),:), 'Markersize',3, 'MarkerFaceColor', ColorOrderMat(mod(i4,size(ColorOrderMat,1)),:));
1260     %LabelCell4{i4} = sprintf('%s', OCS.CM{i4}.FamilyName);
1261
1262     % Absolute corrector change
1263     plot(CMpos, OCS.CM{i4}.Delta(isort), '.-','Color', ColorOrderMat(mod(i4,size(ColorOrderMat,1)),:));
1264     LabelCell4{i4} = sprintf('%s [%s]', OCS.CM{i4}.FamilyName, OCS.CM{i4}.UnitsString);
1265     hold on;
1266 end
1267 hold off;
1268 if length(OCS.CM) == 1
1269     %ylabel(sprintf('{\\Delta}%s [%%Max]', OCS.CM{1}.FamilyName));
1270     ylabel(sprintf('\\Delta %s [%s]', OCS.CM{1}.FamilyName, OCS.CM{1}.UnitsString));
1271 else
1272     %ylabel('\Delta Corrector [%Max]');
1273     ylabel('\Delta Corrector');
1274     h_legend = legend(LabelCell4, 0);
1275     set(h_legend, 'UserData', 'Axes1');
1276 end
1277
1278 %if NumberOfTrys == 1
1279 if OCS.FitRF
1280     title({sprintf('\\DeltaRF = %g %s   SV[%d out of %d]', OCS.DeltaRF, OCS.RF.UnitsString, max(OCS.SVDIndex), length(S)), 'Pre-Orbit Correction'});
1281 else
1282     title({sprintf('SV[%d out of %d]', max(OCS.SVDIndex), length(S)), 'Pre-Orbit Correction'});
1283 end
1284
1285 %xlabel('Position [Meters]');
1286 xaxis([0 L]);
1287 %set(gca,'XTickLabel','');
1288
1289
1290
1291 %%%%%%%%%%%%%%%%%%%%
1292 % Plot Orbit Error %
1293 %%%%%%%%%%%%%%%%%%%%
1294 axes(Haxis(2));
1295 for i = 1:length(OCS.BPM)
1296     BPMpos = getspos(OCS.BPM{i});
1297     [BPMpos, isort] = sort(BPMpos);
1298     plot(BPMpos, OCS.BPM{i}.Data(isort) - OCS.GoalOrbit{i}(isort),'.-','Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1299     hold on;
1300     LabelCell2{i} = sprintf('%s [%s]', OCS.BPM{i}.FamilyName, OCS.BPM{i}.UnitsString);
1301 end
1302 hold off
1303 if length(LabelCell2) == 1
1304     ylabel(sprintf('%s Starting Error [%s]', OCS.BPM{1}.FamilyName, OCS.BPM{1}.UnitsString));
1305 else
1306     ylabel('Starting Orbit Error');
1307     h_legend = legend(LabelCell2, 0);
1308     set(h_legend, 'UserData', 'Axes2');
1309 end
1310 %title(sprintf('Orbit Error Before Correction (Iteration 1 of %d)', NumberOfTrys));
1311 %xlabel('Position [Meters]');
1312 xaxis([0 L]);
1313 %set(gca,'XTickLabel','');
1314
1315
1316
1317 %%%%%%%%%%%%%%%%%%%%%%
1318 % Predicted Residual %
1319 %%%%%%%%%%%%%%%%%%%%%%
1320 axes(Haxis(3));
1321
1322 for i = 1:length(OCS.BPM)
1323     BPMpos = getspos(OCS.BPM{i});
1324     [BPMpos, isort] = sort(BPMpos);
1325
1326     % S-mat prediction: OrbitDelta + Error
1327     plot(BPMpos, OCS.BPM{i}.PredictedOrbitDelta(isort) + (OCS.BPM{i}.Data(isort)-OCS.GoalOrbit{i}(isort)),'.-','Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1328     hold on;
1329     LabelCell2{i} = sprintf('%s [%s]', OCS.BPM{i}.FamilyName, OCS.BPM{i}.UnitsString);
1330 end
1331 hold off
1332 if length(LabelCell2) == 1
1333     ylabel(sprintf('%s Residual [%s]', OCS.BPM{1}.FamilyName, OCS.BPM{1}.UnitsString));
1334 else
1335     ylabel('Orbit Residual');
1336     h_legend = legend(LabelCell2, 0);
1337     set(h_legend, 'UserData', 'Axes3');
1338 end
1339 %title('Predicted Orbit Residual (by the Response Matrix)');
1340 xlabel('Position [Meters]');
1341 xaxis([0 L]);
1342
1343
1344 % Add TimeStamp labels
1345 if length(H) < 3
1346     OCS.Handles.TimeStamp = addlabel(1, 0, datestr(OCS.BPM{1}.TimeStamp,0));
1347
1348     %if OCS.FitRF
1349     %    OCS.Handles.RF = addlabel(0, 0, sprintf('RF frequency will be changed by  %g %s', OCS.DeltaRF, OCS.RF.UnitsString));
1350     %end
1351 end
1352
1353
1354
1355
1356 if MorePlotsFlag || length(H)==6
1357
1358     %%%%%%%%%%%%%%%%
1359     % 3 More Plots %
1360     %%%%%%%%%%%%%%%%
1361
1362     if length(H) < 3
1363         if isnan(H(2))
1364             H(2) = H(1) + 1;
1365             subfig(2,2,1,H(2));
1366             p = get(H(2), 'Position');
1367             set(H(2), 'Position', [p(1) p(2)-.8*p(4) p(3) p(4)+.8*p(4)]);
1368             p = get(H(2), 'Position');
1369             set(H(2), 'Position', [p(1)+.2*p(3) p(2) p(3)-.1*p(3) p(4)]);
1370
1371             p = get(H(1), 'Position');
1372             set(H(1), 'Position', [p(1)+.1*p(3) p(2) p(3)-.1*p(3) p(4)]);
1373         end
1374
1375         figure(H(2));
1376         clf reset
1377
1378         Haxis(4) = subplot(3,1,1);
1379         Haxis(5) = subplot(3,1,2);
1380         Haxis(6) = subplot(3,1,3);
1381         yaxesposition(1.05);
1382         orient portrait
1383     end
1384
1385     drawmoreplots(Haxis(4:6), OCS, Smat, S, U, V);
1386 end
1387
1388 drawnow;
1389
1390
1391 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1392 %  End pre-correction display  %
1393 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1394
1395
1396
1397
1398 function drawmoreplots(Haxis, OCS, Smat, S, U, V)
1399
1400
1401 %%%%%%%%%%%%%%%%
1402 % 3 More Plots %
1403 %%%%%%%%%%%%%%%%
1404
1405 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1406 % Compute Orbit Error & CM strength vs SVD Number %
1407 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1408
1409 % Print wait messege
1410 %plot([0 1],[0 1],'w');
1411 %UnitsString = get(gca,'units');
1412 %set(gca,'units','characters');
1413 %p = get(gca,'Position');
1414 %set(gca,'XTick',[]); set(gca,'YTick',[]); cla; title(' '); xlabel(' '); ylabel(' ');
1415 %set(gca,'box','on');
1416 %Top = floor(p(4));
1417 %
1418 %text(4,Top-4,sprintf('Please wait ...'),'units','characters');
1419 %text(4,Top-6,sprintf('Computing correction performance'),'units','characters');
1420 %text(4,Top-7,sprintf('   as a function of singular value number.'),'units','characters');
1421 %set(gca, 'units', UnitsString);
1422 %drawnow;
1423
1424
1425 % The total kick as a function of SV
1426 hbar = waitbar(0, 'Computing Orbit Change vs SVD#.  Please wait ...');
1427 warning off;
1428 LastGoodSvalue = 1;
1429 OCStmp = OCS;
1430 N = length(S);
1431 for i = 1:N
1432     lastwarn('');
1433     waitbar(i/N);
1434
1435     OCStmp.SVDIndex = 1:i;
1436     OCStmp = orbitcorrectionmethods(OCStmp, Smat, S, U, V);
1437
1438
1439     % RMS orbit change of the corrector magnets
1440     for j = 1:length(OCS.CM)
1441         if isempty(lastwarn)
1442             CMSTDvec{j}(i) = std(OCStmp.CM{j}.Delta);
1443             CMTotal(j,i) = sum(abs(OCStmp.CM{j}.Delta));
1444         else
1445             CMSTDvec{j}(i) = NaN;
1446             CMTotal(j,i) = NaN;
1447         end
1448
1449
1450         % S-mat prediction residual: PredictedOrbitData + Error
1451         BPMresidual(j,i) = std(OCStmp.BPM{j}.PredictedOrbitDelta + (OCStmp.BPM{j}.Data-OCStmp.GoalOrbit{j}));
1452     end
1453
1454     if isempty(lastwarn)
1455         LastGoodSvalue = i;
1456         DeltaRFvec(i,1) = OCStmp.DeltaRF;
1457     else
1458         DeltaRFvec(i,1) = NaN;
1459         %fprintf('\n   S-value number %d warning: %s', i, lastwarn);
1460     end
1461 end
1462 try
1463     close(hbar);
1464 catch
1465 end
1466
1467
1468 warning on;
1469 if LastGoodSvalue ~= length(S)
1470     fprintf('   Computational warning for choosing singular values above %d. \n', LastGoodSvalue);
1471 end
1472
1473
1474 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1475 % CM strength vs SVD number %
1476 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1477 iSVDremove = 1:length(S);
1478 [tmp1, tmp2, i] = intersect(OCS.SVDIndex, iSVDremove);
1479 iSVDremove(i) = [];
1480
1481 for i = 1:length(OCS.CM)
1482     LabelCellCM{i} = sprintf('%s [%s]', OCS.CM{i}.FamilyName, OCS.CM{i}.UnitsString);
1483 end
1484 if OCS.FitRF
1485     %(Haxis(1));
1486     [ax, h1, h2] = plotyy(Haxis(1), 1:length(S), CMTotal, 1:length(S), DeltaRFvec, @plot, @plot);
1487     set(get(ax(2),'Ylabel'),'String',sprintf('\\DeltaRF Frequency [%s]', OCS.RF.UnitsString), 'Color',[.5 0 0]);
1488     set(h1,'LineStyle','-');
1489     set(h1,'Marker','.');
1490     set(h1,'MarkerSize',6);
1491     set(h2,'LineStyle','-');
1492     set(h2,'Color',[.5 0 0]);
1493     set(ax(2),'YColor',[.5 0 0]);
1494     set(h2,'Marker','.');
1495     set(h2,'MarkerSize',6);
1496     %set(get(ax(1),'XLabel'),'String', 'Singular Value Number');
1497     %set(get(ax(1),'Title'), 'String', 'Total Kick Strength');
1498
1499     set(ax(1),'XLim', [0 length(S)]);
1500     set(ax(2),'XLim', [0 length(S)]);
1501
1502     set(get(ax(1),'XLabel'),'String', '');
1503     set(get(ax(2),'XLabel'),'String', '');
1504     %set(ax(1),'XTickLabel', '');
1505     %set(ax(2),'XTickLabel', '');
1506
1507     set(get(ax(1),'title'),'string', {'Performance vs. Number of Singular Values',sprintf('Based on %s Orbit',datestr(OCS.BPM{1}.TimeStamp,0))});
1508
1509     if length(LabelCellCM) == 1
1510         set(get(ax(1),'YLabel'),'String',sprintf('\\Sigma \\mid%s\\mid [%s]', OCS.CM{1}.FamilyName, OCS.CM{1}.UnitsString));
1511     else
1512         set(get(ax(1),'YLabel'),'String',sprintf('\\Sigma \\midCM\\mid'));
1513         %h_legend = legend(Haxis(1), LabelCellCM, 0);
1514         %set(h_legend, 'UserData', 'Axes4');
1515         AxePosition = get(ax(2),'Position');
1516         set(ax(1),'Position', AxePosition);
1517     end
1518 else
1519     %semilogy(1:length(S), CMTotal, '.-');
1520     plot(Haxis(1), 1:length(S), CMTotal, '-');
1521     hold(Haxis(1), 'on');
1522     plot(Haxis(1), OCS.SVDIndex, CMTotal(:,OCS.SVDIndex), 's', 'markersize',2);
1523     plot(Haxis(1), iSVDremove,   CMTotal(:,iSVDremove),   'sr','markersize',2);
1524     hold(Haxis(1), 'off');
1525
1526     if length(LabelCellCM) == 1
1527         ylabel(Haxis(1), sprintf('\\Sigma \\mid%s\\mid [%s]', OCS.CM{1}.FamilyName, OCS.CM{1}.UnitsString));
1528     else
1529         ylabel(Haxis(1), '\Sigma \midCM\mid');
1530         %h_legend = legend(Haxis(1), LabelCellCM, 0);
1531         %set(h_legend, 'UserData', 'Axes4');
1532     end
1533     %xlabel(Haxis(1), 'Singular Value Number');
1534     title(Haxis(1), {'Performance vs. Number of Singular Values',sprintf('Based on %s Orbit',datestr(OCS.BPM{1}.TimeStamp,0))});
1535
1536     axis(Haxis(1), 'tight');
1537     a = axis(Haxis(1));
1538     axis(Haxis(1), [0 length(S) a(3:4)]);
1539     %set(gca,'XTickLabel','');
1540 end
1541
1542
1543 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1544 % Plot Orbit Error vs SVD Number %
1545 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1546 %axes(Haxis(2));
1547 ColorOrderMat = get(Haxis(2),'ColorOrder');
1548 for i = 1:length(OCS.BPM)
1549     %BPMpos = getspos(OCS.BPM{i});
1550     %semilogy(1:length(S), CMSTDvec{i},'.-','Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1551     plot(Haxis(2), 1:length(S), BPMresidual(i,:),'-', 'Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1552     hold(Haxis(2), 'on');
1553     plot(Haxis(2), OCS.SVDIndex, BPMresidual(i,OCS.SVDIndex), 's', 'markersize',2, 'Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1554     plot(Haxis(2), iSVDremove,   BPMresidual(i,iSVDremove),   'sr','markersize',2);
1555
1556     LabelCell2{i} = sprintf('%s [%s]', OCS.BPM{i}.FamilyName, OCS.BPM{i}.UnitsString);
1557 end
1558 hold(Haxis(2), 'off');
1559 if length(LabelCell2) == 1
1560     ylabel(Haxis(2), sprintf('STD %s [%s]', OCS.BPM{1}.FamilyName, OCS.BPM{1}.UnitsString));
1561 else
1562     ylabel(Haxis(2), 'std(Residual)');
1563     %h_legend = legend(Haxis(2), LabelCell2, 0);
1564     %set(h_legend, 'UserData', 'Axes5');
1565 end
1566 %title(Haxis(2), 'Standard Deviation of the Predicted Orbit Residual');
1567 %xlabel(Haxis(2), 'Singular Value Number');
1568
1569 axis(Haxis(2), 'tight');
1570 a = axis(Haxis(2));
1571 axis(Haxis(2), [0 length(S) a(3:4)]);
1572 %set(gca,'XTickLabel','');
1573
1574
1575 %%%%%%%%%%%%%%%%%%%%%%%%
1576 % Plot singular values %
1577 %%%%%%%%%%%%%%%%%%%%%%%%
1578 axes(Haxis(3));
1579 semilogy(S,'-b');
1580 hold on;
1581 semilogy(OCS.SVDIndex,S(OCS.SVDIndex),'sb','markersize',2);
1582 semilogy(iSVDremove,S(iSVDremove),'sr','markersize',2);
1583 hold off
1584 ylabel('Magnitude');
1585 xlabel('Singular Value Number');
1586 axis tight
1587 xaxis([0 length(S)]);
1588
1589 drawnow;
1590
1591
1592
1593
1594
1595 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1596 %  Post-correction display  %
1597 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1598 function PostCorrectionDisplay(H, OCS0, OCS, Smat, S, U, V, Iteration, NumberOfTrys, MorePlotsFlag, InputFlags)
1599
1600 ColorOrderMat = get(gca,'ColorOrder');
1601
1602 % Build the orbit vectors
1603 StartOrbitVec = [];
1604 Orbit0Vec = [];
1605 GoalOrbitVec = [];
1606 OrbitNewVec = [];
1607 %BPMWeight = [];
1608 for i = 1:length(OCS.BPM)
1609     StartOrbitVec = [StartOrbitVec; OCS.BPM{i}.Data];
1610     Orbit0Vec     = [Orbit0Vec;     OCS.BPM{i}.Data];
1611     GoalOrbitVec  = [GoalOrbitVec;  OCS.GoalOrbit{i}];
1612
1613     %OCS.BPM{i} = getpv(OCS.BPM{i}, 'Struct', InputFlags{:});
1614     OrbitNewVec = [OrbitNewVec; OCS.BPM{i}.Data];
1615
1616     %if isempty(OCS.BPMWeight{i})
1617     %    BPMWeight = [BPMWeight; ones(length(OCS.BPM{i}.Data),1)];
1618     %else
1619     %    BPMWeight = [BPMWeight; OCS.BPMWeight{i}(:)];
1620     %end
1621 end
1622
1623 L = getfamilydata('Circumference');
1624 if isempty(L)
1625     global THERING
1626     L = findspos(THERING, length(THERING)+1);
1627 end
1628
1629
1630 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1631 % Plot cumulative change in the corrector %
1632 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1633 set(H(1), 'YLimMode', 'Auto');
1634 hline = get(H(1), 'Children');
1635 for i = 1:length(OCS.CM)
1636     CMpos = getspos(OCS.CM{i});
1637     [CMpos, isort] = sort(CMpos);
1638     set(hline(end-i+1), 'YData', OCS.CM{i}.Data(isort)-OCS0.CM{i}.Data(isort));
1639 end
1640 if length(OCS.CM) == 1
1641     set(get(H(1),'YLabel'), 'String', sprintf('\\Delta %s [%s]', OCS.CM{1}.FamilyName, OCS.CM{1}.UnitsString));
1642 else
1643     set(get(H(1),'YLabel'), 'String', '\Delta Corrector');
1644 end
1645
1646 DeltaRF = OCS.RF.Data - OCS0.RF.Data;
1647 if NumberOfTrys == 1
1648     if OCS.FitRF
1649         TitleString = {sprintf('\\DeltaRF = %g %s   SV[%d out of %d]', DeltaRF, OCS.RF.UnitsString, max(OCS.SVDIndex), length(S)), 'Post-Orbit Correction'};
1650     else
1651         TitleString = {sprintf('SV[%d out of %d]', max(OCS.SVDIndex), length(S)), 'Post-Orbit Correction'};
1652     end
1653 else
1654     if OCS.FitRF
1655         TitleString = {...
1656             sprintf('\\DeltaRF = %g %s    SV[%d out of %d]', DeltaRF, OCS.RF.UnitsString, max(OCS.SVDIndex), length(S)), ...
1657             sprintf('Iteration %d of %d', Iteration, NumberOfTrys)};
1658     else
1659         TitleString = {...
1660             sprintf('SV[%d out of %d]', max(OCS.SVDIndex), length(S)), ...
1661             sprintf('Iteration %d of %d', Iteration, NumberOfTrys)};
1662     end
1663 end
1664 set(get(H(1),'Title'), 'String', TitleString);
1665
1666 %set(gca,'XTickLabel','');
1667
1668
1669
1670 %%%%%%%%%%%%%%%%%%%%
1671 % Plot Orbit Error %
1672 %%%%%%%%%%%%%%%%%%%%
1673 set(H(3), 'YLimMode', 'Auto');
1674 hline = get(H(3), 'Children');
1675 for i = 1:length(OCS.BPM)
1676     BPMpos = getspos(OCS.BPM{i});
1677     [BPMpos,isort] = sort(BPMpos);
1678     %plot(BPMpos, OCS.BPM{i}.Data(isort)-OCS.GoalOrbit{i}(isort),'.-','Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1679     set(hline(end-i+1), 'YData', OCS.BPM{i}.Data(isort)-OCS.GoalOrbit{i}(isort));
1680 end
1681 if length(OCS.BPM) == 1
1682     set(get(H(3),'YLabel'), 'String', sprintf('%s Remaining Error [%s]', OCS.BPM{1}.FamilyName, OCS.BPM{1}.UnitsString));
1683 else
1684     set(get(H(3),'YLabel'), 'String', 'Remaining Orbit Error');
1685 end
1686
1687
1688 % if OCS.FitRF
1689 %     set(OCS.Handles.RF, 'String', sprintf(' RF frequency was changed by  %g %s', OCS.DeltaRF, OCS.RF.UnitsString));
1690 % end
1691
1692
1693 drawnow;
1694
1695
1696
1697
1698
1699 % % Plot Orbit Error
1700 %
1701 % The problem here is the orbit gets updated but .PredictedOrbitDelta does not
1702 %
1703 % axes(H(3));
1704 %
1705 % ColorOrderMat = get(gca,'ColorOrder');
1706 % for i = 1:length(OCS.BPM)
1707 %     BPMpos = getspos(OCS.BPM{i});
1708 %     [BPMpos, isort] = sort(BPMpos);
1709 %
1710 %     % S-mat prediction: OrbitDelta + Error
1711 %     plot(BPMpos, OCS.BPM{i}.PredictedOrbitDelta(isort) + (OCS.BPM{i}.Data(isort)-OCS.GoalOrbit{i}(isort)),'.-','Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1712 %     hold on;
1713 %     LabelCell2{i} = sprintf('%s [%s]', OCS.BPM{i}.FamilyName, OCS.BPM{i}.UnitsString);
1714 % end
1715 % hold off
1716 % if length(LabelCell2) == 1
1717 %     ylabel(sprintf('%s Residual [%s]', OCS.BPM{1}.FamilyName, OCS.BPM{1}.UnitsString));
1718 % else
1719 %     ylabel('Orbit Residual');
1720 %     h_legend = legend(LabelCell2, 0);
1721 % end
1722 % title('Predicted Orbit Residual (by the Response Matrix)');
1723 % xlabel('Position [Meters]');
1724 % xaxis([0 L]);
1725 % set(gca,'XTickLabel','');
1726
1727
1728
1729 % %%%%%%%%%%%%%%%%%%%%%%
1730 % % Predicted Residual %
1731 % %%%%%%%%%%%%%%%%%%%%%%
1732 % if length(H) < 3
1733 %     figure(H(1));
1734 %     subplot(3,1,3);
1735 % else
1736 %     axes(H(3));
1737 % end
1738 % for i = 1:length(OCS.BPM)
1739 %     BPMpos = getspos(OCS.BPM{i});
1740 %     [BPMpos, isort] = sort(BPMpos);
1741 %
1742 %     % S-mat prediction: OrbitDelta + Error
1743 %     plot(BPMpos, OCS.BPM{i}.PredictedOrbitDelta(isort) + (OCS.BPM{i}.Data(isort)-OCS.GoalOrbit{i}(isort)),'.-','Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1744 %     hold on;
1745 %     LabelCell2{i} = sprintf('%s [%s]', OCS.BPM{i}.FamilyName, OCS.BPM{i}.UnitsString);
1746 % end
1747 % hold off
1748 % if length(LabelCell2) == 1
1749 %     ylabel(sprintf('%s Residual [%s]', OCS.BPM{1}.FamilyName, OCS.BPM{1}.UnitsString));
1750 % else
1751 %     ylabel('Orbit Residual');
1752 %     h_legend = legend(LabelCell2, 0);
1753 % end
1754 % %title('Predicted Orbit Residual (by the Response Matrix)');
1755 % xlabel('Position [Meters]');
1756 % xaxis([0 L]);
1757
1758
1759
1760 % for i = 1:length(OCS.BPM)
1761 %     BPMpos = getspos(OCS.BPM{i});
1762 %     [BPMpos,isort] = sort(BPMpos);
1763 %
1764 %     % S-mat prediction
1765 %     plot(BPMpos, (OCS0.BPM{i}.Data(isort)-OCS.GoalOrbit{i}(isort)) + (OCS.BPM{i}.PredictedOrbitDelta(isort)),'.-','Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1766 %     hold on;
1767 %     LabelCell2{i} = sprintf('%s [%s]', OCS.BPM{i}.FamilyName, OCS.BPM{i}.UnitsString);
1768 % end
1769 % hold off
1770 % if length(LabelCell2) == 1
1771 %     ylabel(sprintf('%s Residual [%s]', OCS.BPM{1}.FamilyName, OCS.BPM{1}.UnitsString));
1772 % else
1773 %     ylabel('Orbit Residual');
1774 %     h_legend = legend(LabelCell2, 0);
1775 % end
1776 % title('Predicted Orbit Residual (by the Response Matrix)');
1777 % xlabel('Position [Meters]');
1778 % xaxis([0 L]);
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791 %     %%%%%%%%%%%%%%%%%%%%%
1792 %     % Model predictions %
1793 %     %%%%%%%%%%%%%%%%%%%%%
1794 %     % %[Orbit0ModelX, Orbit0ModelY, Xpos, Ypos] = modeltwiss('x', 'All');
1795 %     % for i = 1:length(OCS.BPM)
1796 %     %     OCS0Model.BPM{i} = getpv(OCS.BPM{i},'Model');
1797 %     % end
1798 %     %
1799 %     % % Step the model
1800 %     % for i = 1:length(OCS.CM)
1801 %     %     steppv(OCS.CM{i}.FamilyName, OCS.CM{i}.Field, OCS.CM{i}.Delta, OCS.CM{i}.DeviceList, 'Model', InputFlags{:});
1802 %     % end
1803 %     % if OCS.FitRF
1804 %     %     stepsp('RF', OCS.DeltaRF, 'Model');
1805 %     % end
1806 %     %
1807 %     % %[OrbitModelX, OrbitModelY] = modeltwiss('x', 'All');
1808 %     % for i = 1:length(OCS.BPM)
1809 %     %     OCSModel.BPM{i} = getpv(OCS.BPM{i},'Model');
1810 %     % end
1811 %     %
1812 %     % % Step the model back
1813 %     % for i = 1:length(OCS.CM)
1814 %     %     steppv(OCS.CM{i}.FamilyName, OCS.CM{i}.Field, -1*OCS.CM{i}.Delta, OCS.CM{i}.DeviceList, 'Model', InputFlags{:});
1815 %     % end
1816 %     % if OCS.FitRF
1817 %     %     stepsp('RF', -OCS.DeltaRF, 'Model');
1818 %     % end
1819 %     %
1820 %     %
1821 %     % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1822 %     % % Plot Orbit Residue based on the AT model %
1823 %     % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1824 %     % axes(Haxis(7));
1825 %     % ColorOrderMat = get(gca,'ColorOrder');
1826 %     % for i = 1:length(OCS.BPM)
1827 %     %     BPMpos = getspos(OCS.BPM{i});
1828 %     %     [BPMpos,isort] = sort(BPMpos);
1829 %     %
1830 %     %     % Model prediction Error
1831 %     %     plot(BPMpos, (OCSModel.BPM{i}.Data(isort)-OCS0Model.BPM{i}.Data(isort)) - (OCS.GoalOrbit{i}(isort)-OCS.BPM{i}.Data(isort)),'.-','Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1832 %     %
1833 %     %     % S-mat prediction
1834 %     %     %    plot(BPMpos, (OCS0.BPM{i}.Data-OCS.GoalOrbit{i}) + (BPMSVDDeltaCell{i}),':','Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1835 %     %     hold on;
1836 %     %     LabelCell2{i} = sprintf('%s [%s]', OCS.BPM{i}.FamilyName, OCS.BPM{i}.UnitsString);
1837 %     % end
1838 %     % hold off
1839 %     % if length(LabelCell2) == 1
1840 %     %     ylabel(sprintf('%s Residual [%s]', OCS.BPM{1}.FamilyName, OCS.BPM{1}.UnitsString));
1841 %     % else
1842 %     %     ylabel('Orbit Residual');
1843 %     %     h_legend = legend(LabelCell2, 0);
1844 %     % end
1845 %     % title('Predicted Orbit Residual (by the Nonlinear AT Model)');
1846 %     % xlabel('Position [Meters]');
1847 %     % xaxis([0 L]);
1848 %     %
1849 %     %
1850 %     % % Linearization Error
1851 %     % if length(H) < 4
1852 %     %     figure(H(2));
1853 %     %     subplot(4,1,4);
1854 %     % else
1855 %     %     axes(H(8));
1856 %     % end
1857 %     % ColorOrderMat = get(gca,'ColorOrder');
1858 %     % for i = 1:length(OCS.BPM)
1859 %     %     BPMpos = getspos(OCS.BPM{i});
1860 %     %     [BPMpos,isort] = sort(BPMpos);
1861 %     %
1862 %     %     % Model - S-matrix prediction
1863 %     %     plot(BPMpos, (OCSModel.BPM{i}.Data(isort)-OCS0Model.BPM{i}.Data(isort)) - OCS.BPM{i}.PredictedOrbitDelta(isort),'.-','Color', ColorOrderMat(mod(i,size(ColorOrderMat,1)),:));
1864 %     %     hold on;
1865 %     %     LabelCell2{i} = sprintf('%s [%s]', OCS.BPM{i}.FamilyName, OCS.BPM{i}.UnitsString);
1866 %     % end
1867 %     % hold off
1868 %     % if length(LabelCell2) == 1
1869 %     %     %ylabel(sprintf('%s Linearization Error [%s]', OCS.BPM{1}.FamilyName, OCS.BPM{1}.UnitsString));
1870 %     %     ylabel(sprintf('Linearization Error [%s]', OCS.BPM{1}.UnitsString));
1871 %     % else
1872 %     %     ylabel('Linearization Error');
1873 %     %     h_legend = legend(LabelCell2, 0);
1874 %     % end
1875 %     % title('Predicted Orbit Change Error (AT Model - Response Matrix)');
1876 %     % xlabel('Position [Meters]');
1877 %     % xaxis([0 L]);