Description of setpv
Home > mml > setpv.m
setpv
PURPOSE
SETPV - Setpoint change of the online system or model
SYNOPSIS
function ErrorFlag = setpv(varargin)
DESCRIPTION
SETPV - Setpoint change of the online system or model
  FamilyName Method
  ErrorFlag = setpv(Family, Field, NewSP, DeviceList, WaitFlag)
  Data Structure
  ErrorFlag = setpv(DataStructure, WaitFlag)
  ChannelName (EPICS/TANGO) Method
  ErrorFlag = setpv(TangoName, NewSP, WaitFlag)
  ErrorFlag = setpv(ChannelName, NewSP, WaitFlag)
  ErrorFlag = setpv(ChannelName, Field, NewSP, WaitFlag)
  CommonName Method
  ErrorFlag = setpv(CommonNames, NewSP, WaitFlag)
  ErrorFlag = setpv(CommonNames, Field, NewSP, WaitFlag)
  ErrorFlag = setpv(Family, Field, NewSP, CommonNames, WaitFlag)
  INPUTS
  1. Family - FamilyName
              Data Structure
              Channel Name or matrix of Channel Names (see note #5)
              Tango Name or matrix of Tango Names
              AcceleratorObject
              Use Family=[] in CommonName method to search all Families
              (or Cell Array of inputs)
  2. Field - AcceleratorObject Field name ('Monitor', 'Setpoint', etc)
             {Default: 'Monitor' or '' for ChannelNames method}
             If Family is a cell array then Field must be a cell array
  3. NewSP - New Setpoints or cell array of Setpoints
             Note: Present, only LabCA can handle string setpoints.  String setpoints
                   will fail if hw2physics or physics2hw are needed.
  4. DeviceList - ([Sector Device #] or [element #]) {Default or empty list: whole family}
                  Note: all numerical inputs must be column vectors
     CommonName - Common name can replace a DeviceList (scalar or vector outputs)
  5. WaitFlag - 0    -> return immediately {Default}
                > 0  -> wait until ramping is done then adds an extra delay equal to WaitFlag
                = -1 -> wait until ramping is done
                = -2 -> wait until ramping is done then adds an extra delay for fresh data
                        from the BPMs
                = -3 -> wait until ramping is done then adds an extra delay for fresh data
                        from the tune measurement system
                = -4 -> wait until ramping is done then wait for a carriage return
     Note: For channel names, it is assumed the ramp time is immediate.
  6. Units flag overrides
     'Physics'  - Use physics  units
     'Hardware' - Use hardware units
  7. Mode flag overrides
     'Online' - Set data online
     'Model'  - Set data on the model
     'Manual' - Set data manually
  8. 'Abs' or 'Absolute'   - Absolute setpoint change {Default}
     'Inc' or 'Incrmental' - Incremental setpoint change
  OUTPUTS
  1. ErrorFlag - 0   -> OK
                else -> error or warning condition occurred
     Note: ErrorFlag is only used if AD.ErrorWarningLevel < 0, otherwise a Matlab error
           in issued.  Use try;catch statements to catch the errors.
  NOTES
  1. For data structure inputs:
     Family     = DataStructure.FamilyName (This field must exist)
     Field      = DataStructure.Field      (Field can be overridden on the input line)
     NewSP      = DataStructure.Data       (NewSP can be overridden on the input line)
     DeviceList = DataStructure.DeviceList (DeviceList can be overridden on the input line)
     Units      = DataStructure.Units      (Units can be overridden on the input line)
     (The Mode field is ignored!)
  2. The number of colomns of NewSP and DeviceList must be equal,
     or NewSP must be a scalar.  If NewSP is a scalar, then all
     devices in DeviceList will be set to the same value.
  3. When using cell array all inputs must be the same size cell array
     and the output will also be a cell array.  Field and WaitFlag can be
     cells but they don't have to be.
  4. ChannelName method:
     a. Always Online!
     b. The optional Field input is added as a .Field to the channel name
     c. If use setpv(ChannelName, NewSP, WaitFlag) then NewSP must a numeric.
        Use setpv(ChannelName, '',NewSP, WaitFlag) if NewSP is a string.
  5. For cell array inputs:
     a. Input 1 defines the maximum size of all cells
     b. The cell array size must be 1 or equal to the number of cell in input #1
     c. WaitFlag can be a cell but it doesn't have to be.
  6. WaitFlag
     a. If no change is seen on the AM then an error will occur.  The tolerance for this
        may need to be changed depending on the accelerator (edit the end of this function to do so)
     b. The delay for WaitFlag = -2 is in the AD.  It is often better to use the FreshDataFlag when
        getting BPM data but the data must to noisy for this to work.
  7. Strings - when setting string the Field input must exist otherwise the setpoint will be
               confused for a Field.
  8. If say Golden is a software field in the MML structure in the BPMx family, then
     setpv('BPMx','Golden', NewValue, DeviceList) will set the data in that field.
  EXAMPES
  1. setpv('HCM','Setpoint',1.23);               Sets the entire HCM family to 1.23
  2. setpv({'HCM','VCM'},'Setpoint',{10.4,5.3}); Sets the entire HCM family to 10.4 and VCM family to 5.3
  3. setpv('HCM','Setpoint',1.23,[1 3]);    Simple DeviceList method
  4. setpv('HCM','Setpoint',1.23, 3);       Simple ElementList method
  5. setpv(AO('HCM'),'Setpoint',1.5,[1 2]);     If AO is a properly formatted AcceleratorObject Structure
                                                    then this sets the 1st sector, 2nd element to 1.5
  6. setpv('HCM','Setpoint',1.23,'1CX3');   CommonName method with Family specified (spear3 naming convection)
  7. setpv([],'Setpoint',1.23,'1CX3');      CommonName method without Family (spear3 naming convection)
  See also getam, getsp, getpv, setsp, steppv, stepsp, setpvmodel, setpvonline
  Written by Greg Portmann
CROSS-REFERENCE INFORMATION
This function calls:
common2dev COMMON2DEV - Converts a common name to a device list
elem2dev ELEM2DEV - Converts a device list to an element list
family2dev FAMILY2DEV - Return the device list for a family
getam GETAM - Gets monitor channels
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getpv GETPV - Returns a variable from the online system or the model
getramprate GETRAMPRATE - Returns the ramp rate for a family
getrunflag GETRUNFLAG - Returns position if the device is in the process of changing a setpoint
getsp GETSP - Gets setpoint channels
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
isfamily ISFAMILY - True for family names
physics2hw PHYSICS2HW - Converts from 'Physics' units to 'Hardware' units
setfamilydata SETFAMILYDATA - Sets data associated with accelerator control
setpv SETPV - Setpoint change of the online system or model
This function is called by:
correctors2golden CORRECTORS2GOLDEN - Sets the default corrector families to the golden configuration values
measidfftable FFGETTBL - Measures an insertion device feed forward table for the vertical gap
setam SETAM - Sets analog monitor value
setenergy SETENERGY - Sets the storage ring energy (GeV) by ramping all lattice magnets
setmachineconfig SETMACHINECONFIG - Sets the storage ring setpoints from a file or configuration data structure
setorbit SETORBIT - Orbit correction function
setpv SETPV - Setpoint change of the online system or model
setrf SETRF - Sets the RF frequency
setsp SETSP - Makes an absolute setpoint change to the 'Setpoint' field
steppv STEPPV - Incremental setpoint change of a process variable or simulated value
stepsp STEPSP - Step the setpoint for family
sweepenergy SWEEPENERGY - Energy sweep of the storage ring
SUBFUNCTIONS
function ErrorFlag = local_setpv(AO, Field, NewSP, DeviceList, WaitFlag)
SOURCE CODE
function ErrorFlag = setpv(varargin)
%SETPV - Setpoint change of the online system or model
%
%  FamilyName Method
%  ErrorFlag = setpv(Family, Field, NewSP, DeviceList, WaitFlag)
%
%  Data Structure
%  ErrorFlag = setpv(DataStructure, WaitFlag)
%
%  ChannelName (EPICS/TANGO) Method
%  ErrorFlag = setpv(TangoName, NewSP, WaitFlag)
%  ErrorFlag = setpv(ChannelName, NewSP, WaitFlag)
%  ErrorFlag = setpv(ChannelName, Field, NewSP, WaitFlag)
%
%  CommonName Method
%  ErrorFlag = setpv(CommonNames, NewSP, WaitFlag)
%  ErrorFlag = setpv(CommonNames, Field, NewSP, WaitFlag)
%  ErrorFlag = setpv(Family, Field, NewSP, CommonNames, WaitFlag)
%
%  INPUTS
%  1. Family - FamilyName
%              Data Structure
%              Channel Name or matrix of Channel Names (see note #5)
%              Tango Name or matrix of Tango Names
%              AcceleratorObject
%              Use Family=[] in CommonName method to search all Families
%              (or Cell Array of inputs)
%
%  2. Field - AcceleratorObject Field name ('Monitor', 'Setpoint', etc)
%             {Default: 'Monitor' or '' for ChannelNames method}
%             If Family is a cell array then Field must be a cell array
%
%  3. NewSP - New Setpoints or cell array of Setpoints
%             Note: Present, only LabCA can handle string setpoints.  String setpoints
%                   will fail if hw2physics or physics2hw are needed.
%
%  4. DeviceList - ([Sector Device #] or [element #]) {Default or empty list: whole family}
%                  Note: all numerical inputs must be column vectors
%     CommonName - Common name can replace a DeviceList (scalar or vector outputs)
%
%  5. WaitFlag - 0    -> return immediately {Default}
%                > 0  -> wait until ramping is done then adds an extra delay equal to WaitFlag
%                = -1 -> wait until ramping is done
%                = -2 -> wait until ramping is done then adds an extra delay for fresh data
%                        from the BPMs
%                = -3 -> wait until ramping is done then adds an extra delay for fresh data
%                        from the tune measurement system
%                = -4 -> wait until ramping is done then wait for a carriage return
%     Note: For channel names, it is assumed the ramp time is immediate.
%
%  6. Units flag overrides
%     'Physics'  - Use physics  units
%     'Hardware' - Use hardware units
%
%  7. Mode flag overrides
%     'Online' - Set data online
%     'Model'  - Set data on the model
%     'Manual' - Set data manually
%
%  8. 'Abs' or 'Absolute'   - Absolute setpoint change {Default}
%     'Inc' or 'Incrmental' - Incremental setpoint change
%
%  OUTPUTS
%  1. ErrorFlag - 0   -> OK
%                else -> error or warning condition occurred
%     Note: ErrorFlag is only used if AD.ErrorWarningLevel < 0, otherwise a Matlab error
%           in issued.  Use try;catch statements to catch the errors.
%
%  NOTES
%  1. For data structure inputs:
%     Family     = DataStructure.FamilyName (This field must exist)
%     Field      = DataStructure.Field      (Field can be overridden on the input line)
%     NewSP      = DataStructure.Data       (NewSP can be overridden on the input line)
%     DeviceList = DataStructure.DeviceList (DeviceList can be overridden on the input line)
%     Units      = DataStructure.Units      (Units can be overridden on the input line)
%     (The Mode field is ignored!)
%
%  2. The number of colomns of NewSP and DeviceList must be equal,
%     or NewSP must be a scalar.  If NewSP is a scalar, then all
%     devices in DeviceList will be set to the same value.
%
%  3. When using cell array all inputs must be the same size cell array
%     and the output will also be a cell array.  Field and WaitFlag can be
%     cells but they don't have to be.
%
%  4. ChannelName method:
%     a. Always Online!
%     b. The optional Field input is added as a .Field to the channel name
%     c. If use setpv(ChannelName, NewSP, WaitFlag) then NewSP must a numeric.
%        Use setpv(ChannelName, '',NewSP, WaitFlag) if NewSP is a string.
%
%  5. For cell array inputs:
%     a. Input 1 defines the maximum size of all cells
%     b. The cell array size must be 1 or equal to the number of cell in input #1
%     c. WaitFlag can be a cell but it doesn't have to be.
%
%  6. WaitFlag
%     a. If no change is seen on the AM then an error will occur.  The tolerance for this
%        may need to be changed depending on the accelerator (edit the end of this function to do so)
%     b. The delay for WaitFlag = -2 is in the AD.  It is often better to use the FreshDataFlag when
%        getting BPM data but the data must to noisy for this to work.
%
%  7. Strings - when setting string the Field input must exist otherwise the setpoint will be
%               confused for a Field.
%
%  8. If say Golden is a software field in the MML structure in the BPMx family, then
%     setpv('BPMx','Golden', NewValue, DeviceList) will set the data in that field.
%
%  EXAMPES
%  1. setpv('HCM','Setpoint',1.23);               Sets the entire HCM family to 1.23
%  2. setpv({'HCM','VCM'},'Setpoint',{10.4,5.3}); Sets the entire HCM family to 10.4 and VCM family to 5.3
%  3. setpv('HCM','Setpoint',1.23,[1 3]);    Simple DeviceList method
%  4. setpv('HCM','Setpoint',1.23, 3);       Simple ElementList method
%  5. setpv(AO('HCM'),'Setpoint',1.5,[1 2]);     If AO is a properly formatted AcceleratorObject Structure
%                                                    then this sets the 1st sector, 2nd element to 1.5
%  6. setpv('HCM','Setpoint',1.23,'1CX3');   CommonName method with Family specified (spear3 naming convection)
%  7. setpv([],'Setpoint',1.23,'1CX3');      CommonName method without Family (spear3 naming convection)
%
%  See also getam, getsp, getpv, setsp, steppv, stepsp, setpvmodel, setpvonline
%
%  Written by Greg Portmann
% Defaults
WaitFlagDefault = 0;
FieldDefault = 'Setpoint';
%%%%%%%%%%%%%%%%%
% Input Parsing %
%%%%%%%%%%%%%%%%%
Field = FieldDefault;
IncrementalFlag = 0;
DeviceList = [];
WaitFlag = [];
ModeFlag = '';
UnitsFlag = '';
InputFlags = {};
for i = length(varargin):-1:1
    if isstruct(varargin{i})
        % Ignor structures
    elseif iscell(varargin{i})
        % Ignor cells
    elseif isa(varargin{i},'AccObj')
        AccObj1 = struct(varargin{i});
        Families = fieldnames(AccObj1);
        j = 0;
        for k = 1:length(Families)
            if ~isempty(AccObj1.(Families{k}))
                j = j + 1;
                tmpcell{j} = AccObj1.(Families{k});
            end
        end
        if length(tmpcell) == 1
            varargin{i} = tmpcell{1};
        else
            varargin{i} = tmpcell;
        end
    elseif strcmpi(varargin{i},'struct')
        % Remove and ignor
        varargin(i) = [];
    elseif strcmpi(varargin{i},'numeric')
        % Remove and ignor
        varargin(i) = [];
    elseif strcmpi(varargin{i},'simulator') || strcmpi(varargin{i},'model')
        ModeFlag = 'SIMULATOR';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Online')
        ModeFlag = 'Online';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Manual')
        ModeFlag = 'Manual';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Special')
        ModeFlag = 'Special';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'physics')
        UnitsFlag = 'Physics';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'hardware')
        UnitsFlag = 'Hardware';
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Inc') || strcmpi(varargin{i},'Incremental')
        IncrementalFlag = 1;
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Abs') || strcmpi(varargin{i},'Absolute')
        IncrementalFlag = 0;
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'String')
        % Remove and ignor
        varargin(i) = [];
    end
end
if isempty(varargin)
    error('Not enough inputs');
end
Family = varargin{1};
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CELL OR CELL ARRAY INPUT %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if iscell(varargin{1})
    % Iterate on each cell
    % ErrorFlag = setpv(Family, Field, NewSP, DeviceList, WaitFlag)
    % ErrorFlag = setpv(DataStructure, WaitFlag)
    % ErrorFlag = setpv(ChannelName, NewSP)
    % ErrorFlag = setpv(Family, Field, NewSP, CommonNames, WaitFlag)
    % Set everything with WaitFlag==0
    DoItAgainFlag = 0;
    ErrorFlag = 0;
    for i = 1:size(varargin{1},1)
        for j = 1:size(varargin{1},2)
            % Build the input line
            for k = 1:length(varargin)
                if ~iscell(varargin{k})
                    Inputs1{1,k} = varargin{k};
                elseif length(varargin{k}) == 1
                    Inputs1{1,k} = varargin{k}{1};
                elseif (size(varargin{k},1) == size(varargin{1},1)) && (size(varargin{k},2) == size(varargin{1},2))
                    Inputs1{1,k} = varargin{k}{i,j};
                else
                    error('When using cells, all the cells must be the same size or length 1 (repeated).');
                end
            end
            % Remove WaitFlag on first set if WaitFlag~=0 on any cell
            if isstruct(varargin{1}{i,j})
                if length(Inputs1) >= 2
                    if ischar(Inputs1{2})
                        % Inputs1{2} might be 'setpoint' due to setsp
                        if length(Inputs1) >= 3
                            if Inputs1{3} ~= 0
                                DoItAgainFlag = 1;
                                Inputs1{2} = 0;
                            end
                            Inputs1(3) = [];
                        else
                            DoItAgainFlag = 1;
                        end
                    else
                        if Inputs1{2} ~= 0
                            DoItAgainFlag = 1;
                            Inputs1{2} = 0;
                        end
                    end
                else
                    DoItAgainFlag = 1;
                end
            elseif length(Inputs1) == 2
                % For ChannelName just set once
            elseif length(Inputs1) == 3
                DoItAgainFlag = 1;
                Inputs1{4} = [];
                Inputs1{5} = 0;
            elseif length(Inputs1) == 4
                DoItAgainFlag = 1;
                Inputs1{5} = 0;
            elseif length(Inputs1) >= 5
                if Inputs1{5} ~= 0
                    DoItAgainFlag = 1;
                    Inputs1{5} = 0;
                end
            end
            % Make the setpoint change
            ErrorFlagNew = setpv(Inputs1{:}, InputFlags{:});
            ErrorFlag = ErrorFlag | any(ErrorFlagNew);
        end
    end
    % Wait for the waitflag
    if DoItAgainFlag
        for i = 1:size(varargin{1},1)
            for j = 1:size(varargin{1},2)
                % Build the input line
                for k = 1:length(varargin)
                    if ~iscell(varargin{k})
                        Inputs1{1,k} = varargin{k};
                    elseif length(varargin{k}) == 1
                        Inputs1{1,k} = varargin{k}{1};
                    elseif (size(varargin{k},1) == size(varargin{1},1)) && (size(varargin{k},2) == size(varargin{1},2))
                        Inputs1{1,k} = varargin{k}{i,j};
                    else
                        error('When using cells, all the cells must be the same size or length 1 (repeated).');
                    end
                end
                % Make the setpoint change
                ErrorFlagNew = setpv(Inputs1{:}, InputFlags{:});
                ErrorFlag = ErrorFlag | any(ErrorFlagNew);
            end
        end
    end
    return
end
%%%%%%%%%%%%%%%%%%
% End cell input %
%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% COMMONNAME - Commonname input with no family input %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isempty(Family)
    % Common names with Family = []
    % [], Field, NewSP, CommonNames
    if length(varargin) >= 2
        if ischar(varargin{2})
            Field = varargin{2};
            varargin(2) = [];
        end
    end
    if isempty(Field)
        Field = FieldDefault;
    end
    if length(varargin) >= 2
        NewSP = varargin{2};
    else
        error('New setpoint not found on input line');
    end
    if length(varargin) >= 3
        CommonNames = varargin{3};
    else
        CommonNames = [];
    end
    if length(varargin) >= 4
        WaitFlag = varargin{4};
    end
    if isempty(WaitFlag)
        WaitFlag = WaitFlagDefault;
    end
    if size(NewSP,1) == 1
        % Set all elements to same value
        NewSP = ones(size(CommonNames,1),1) * NewSP;
    elseif size(NewSP,1) == size(CommonNames,1)
        % Input OK
    else
        error('Size of NewSP must be equal to the number of Commonnames or a scalar!');
    end
    % Convert all the common names to Family and Device lists
    [DeviceList, Family, ErrorFlag] = common2dev(CommonNames, Field);
    % If all the families are the same then compress them
    FamilyTest = unique(Family, 'rows');
    if size(FamilyTest, 1) == 1
        % 1 Family, Multiple devices are ok
        ErrorFlag = setpv(FamilyTest, Field, NewSP, DeviceList, WaitFlag, InputFlags{:});
    else
        % Multiple families (loop)
        % It has to be in a loop for the simulator and to pickup special functions
        for i = 1:size(Family,1)
            ErrorFlag1 = setpv(Family(i,:), Field, NewSP(i,:), DeviceList(i,:), 0, InputFlags{:});
            ErrorFlag = ErrorFlag | ErrorFlag1;
        end
        if WaitFlag
            for i = 1:size(Family,1)
                ErrorFlag1 = setpv(Family(i,:), Field, NewSP(i,:), DeviceList(i,:), WaitFlag, InputFlags{:});
                ErrorFlag = ErrorFlag | ErrorFlag1;
            end
        end
    end
    return
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End CommonName input with no family input %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Parce inputs depending on Data structure, AO structure, Family, ChannelName method %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isstruct(Family)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % STRUCTURE INPUTS - Data structure or AO structure %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    if isfield(varargin{1},'FamilyName') && isfield(varargin{1},'Field')
        % setpv(DataStruct, Field, NewSP, WaitFlag)
        %   Select FamilyName, DeviceList, Units from the structure (if not on the input line)
        %   Mode in the structure is ignored
        Family = varargin{1}.FamilyName;
        % The only input for a Data Structure can Field and WaitFlag
        Field = '';
        if length(varargin) >= 2
            if ischar(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        if isempty(Field)
            Field = varargin{1}.Field;
        end
        NewSP = varargin{1}.Data;
        DeviceList = varargin{1}.DeviceList;
        if length(varargin) >= 2
           WaitFlag = varargin{2};
        end
        %if length(varargin) >= 2
        %    NewSP = varargin{2};
        %else
        %    NewSP = varargin{1}.Data;
        %end
        %if length(varargin) >= 3
        %    DeviceList = varargin{3};
        %else
        %    DeviceList = varargin{1}.DeviceList;
        %end
        %if length(varargin) >= 4
        %    WaitFlag = varargin{4};
        %end
        [FamilyIndex, AO] = isfamily(Family);
        % Change Units to the data structure units (command-line override comes latter)
        if isfield(AO, Field)
            AO.(Field).Units = varargin{1}.Units;
        end
        if FamilyIndex == 0
            error('Unknown family in the data structure');
        end
    elseif isfield(varargin{1},'FamilyName')
        % AO structure - use the AO structure directly
        % setpv(AO, Field, NewSP, DeviceList, WaitFlag)
        Field = '';
        if length(varargin) >= 2
            if ischar(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        if length(varargin) >= 2
            NewSP = varargin{2};
        else
            error('New setpoint not found on input line');
        end
        if length(varargin) >= 3
            DeviceList = varargin{3};
        else
            DeviceList = varargin{1}.DeviceList;
            iStatus = find(varargin{1}.Status == 0);
            DeviceList(iStatus,:) = [];
        end
        if length(varargin) >= 4
            WaitFlag = varargin{4};
        end
        FamilyIndex = 1;
        AO = Family;
    else
        error('Input #1 of unknown type');
    end
else
    % Family or ChannelName/TangoName is the only thing left
    [FamilyIndex, AO] = isfamily(Family);
    if FamilyIndex
        %%%%%%%%%%%%%%
        % FamilyName %
        %%%%%%%%%%%%%%
        if length(varargin) >= 2
            if ischar(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        if isempty(Field)
            Field = FieldDefault;
        end
        if length(varargin) >= 2
            NewSP = varargin{2};
        else
            error('New setpoint not found on input line');
        end
        if length(varargin) >= 3
            DeviceList = varargin{3};
        end
        if length(varargin) >= 4
            WaitFlag = varargin{4};
        end
        if isempty(WaitFlag)
            WaitFlag = WaitFlagDefault;
        end
    else
        % Look to see if it's a channel name or a common name
        % Just check the first name so it's a faster test
        [DeviceListTest, FamilyTest] = common2dev(Family(1,:));
        if ~isempty(FamilyTest)
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            % Common names where the family was the common name %
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            % The DeviceList should not be on the input line!
            if length(varargin) >= 2
                if ischar(varargin{2})
                    Field = varargin{2};
                    varargin(2) = [];
                end
            end
            if isempty(Field)
                Field = FieldDefault;
            end
            if length(varargin) >= 2
                NewSP = varargin{2};
            else
                error('New setpoint not found on input line');
            end
            if length(varargin) >= 3
                WaitFlag = varargin{3};
            end
            if isempty(WaitFlag)
                WaitFlag = WaitFlagDefault;
            end
            CommonNames = Family;
            if size(NewSP,1) == 1
                % Set all elements to same value
                NewSP = ones(size(CommonNames,1),1) * NewSP;
            elseif size(NewSP,1) == size(CommonNames,1)
                % Input OK
            else
                error('Size of NewSP must be equal to the number of Commonnames or a scalar!');
            end
            % Convert all the common names to Family and Device lists
            [DeviceList, Family, ErrorFlag] = common2dev(CommonNames);
            % If all the families are the same then compress them
            FamilyTest = unique(Family, 'rows');
            if size(FamilyTest, 1) == 1
                % 1 Family, Multiple devices are ok
                ErrorFlag = setpv(FamilyTest, Field, NewSP, DeviceList, WaitFlag, InputFlags{:});
            else
                % Multiple families (loop)
                % It has to be in a loop for the simulator and to pickup special functions
                for i = 1:size(Family,1)
                    ErrorFlag1 = setpv(Family(i,:), Field, NewSP(i,:), DeviceList(i,:), 0, InputFlags{:});
                    ErrorFlag = ErrorFlag | ErrorFlag1;
                end
                if WaitFlag
                    for i = 1:size(Family,1)
                        ErrorFlag1 = setpv(Family(i,:), Field, NewSP(i,:), DeviceList(i,:), WaitFlag, InputFlags{:});
                        ErrorFlag = ErrorFlag | ErrorFlag1;
                    end
                end
            end
            % Return for common names
           return
        else
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % CHANNEL NAME or TANGO NAME - Online Only %
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            % setpv(ChannelName, Field, NewSP, WaitFlag)
            % setpv(ChannelName, Field, NewSP)
            % setpv(ChannelName, NewSP, WaitFlag)  % NewSP cannot be string for this case
            % setpv(ChannelName, NewSP)
            Field = '';
            if length(varargin) == 2
                % setpv(ChannelName, NewSP)
                NewSP = varargin{2};
            elseif length(varargin) >= 3
                if ischar(varargin{2})
                    Field = varargin{2};
                    varargin(2) = [];
                end
                NewSP = varargin{2};
            end
            if length(varargin) >= 3
                WaitFlag = varargin{3};
            else
                WaitFlag = [];
            end
            if isempty(WaitFlag)
                WaitFlag = WaitFlagDefault;
            end
            % Don't set NaN's for now???
            %iNaN = find(isnan(NewSP));
            %if ~isempty(iNaN)
            %    Family(iNaN,:) = [];
            %    NewSP(iNaN,:) = [];
            %end
        % Can't use overrides with channel / TANGO name method
            if ~isempty(UnitsFlag)
            error('You cannot change the units when using channel or attribute names.')
            end
        if ~(isempty(ModeFlag) | strcmpi(ModeFlag, 'Online'))
            error('Channelor Tango names only have an ''Online'' Mode.')
            end
        % Get rid of repeated & blank channel or attribute names
            [Family, i] = unique(Family, 'rows');
            if size(NewSP,1) ~= 1
                NewSP = NewSP(i,:);
            end
            if isempty(deblank(Family(1,:)))
                Family(1,:) = [];
                if size(NewSP,1) ~= 1
                    NewSP(1,:) = [];
                end
            end
            % Add Field to Family.Field
            if ~isempty(Field)
                Family = strcat(Family, ['.',Field]);
            end
            % Incremental change in the setpoint
            if IncrementalFlag
                % Note: ModeFlag, UnitsFlag are ignored for channel name inputs
                %NewSP = NewSP + getpv(Family);
                if size(NewSP,2) == 1
                    SPpresent = getpvonline(Family, '', 1);
                else
                    SPpresent = getpvonline(Family);
                end
                NewSP = NewSP + SPpresent;
            else
                if size(NewSP,1) == 1 && size(Family,1) > 1
                    % Set all elements to same value
                    NewSP = NewSP * ones(size(Family,1),1);
                end
            end
            %%%%%%%%%%%%
            % Set data %
            %%%%%%%%%%%%
            % Could add N-Steps here???
            ErrorFlag = setpvonline(Family, NewSP);
            % Add a delay based on the WaitFlag
            if WaitFlag > 0
                sleep(WaitFlag);
            elseif WaitFlag == -2
                [N, BPMDelay] = getbpmaverages;
                BPMDelay = 2.2 * max(BPMDelay);
                if ~isempty(BPMDelay)
                    sleep(BPMDelay);
                end
            elseif WaitFlag == -3
                TUNEDelay = getfamilydata('TUNEDelay');
                if ~isempty(TUNEDelay)
                    sleep(TUNEDelay);
                end
            elseif WaitFlag == -4
                tmp = input('   Setpoint changed.  Hit return ready. ');
            end
            return
        end
    end
end
% End input selection:  data structure, AO structure, family, commonname, and channelname method
%%%%%%%%%%%%%%%%%%%%%%%%%
% SET DATA FOR FAMILIES %
%%%%%%%%%%%%%%%%%%%%%%%%%
% Family = FamilyName or AO structure with DeviceList or CommonName List
if isempty(DeviceList)                   % This is a very important line, it determines the default behavior
    DeviceList = family2dev(Family);     % Default behavior comes from family2dev
    %DeviceList = family2dev(Family,1);  % Good status only
    %DeviceList = AO.DeviceList;         % All devices
end
% If DeviceList is a string it's a common name list
if ischar(DeviceList)
    DeviceList = common2dev(DeviceList, AO);
end
% Convert DeviceList format to ElementList format
if (size(DeviceList,2) == 1)
    DeviceList = elem2dev(Family, DeviceList);
end
if isempty(WaitFlag)
    WaitFlag = WaitFlagDefault;
end
% Look for command-line over rides
if ~isempty(UnitsFlag)
    AO.(Field).Units = UnitsFlag;
end
if ~isempty(ModeFlag)
    AO.(Field).Mode = ModeFlag;
end
if size(NewSP,1) == 1 && size(DeviceList,1) > 1
    % Set all elements to same value
    NewSP = NewSP * ones(size(DeviceList,1),1);
elseif size(NewSP,1) ~= size(DeviceList,1)
    % This is either an error or NewSP equals the number of power supplies (not magnets)
    [DeviceList, ii, jj] = unique(DeviceList, 'rows');
    [TangoNames, i, j] = unique(family2tango(Family, DeviceList), 'rows');
    if size(NewSP,1) == size(TangoNames,1)
        NewSP = NewSP(j);
        NewSP = NewSP(ii);
    else
        error('The number of setpoints does not equal the number of magnets or magnet power supplies.');
    end
end
% Incremental change in the setpoint
if IncrementalFlag
    NewSP = NewSP + getpv(Family, Field, DeviceList, AO.(Field).Units, AO.(Field).Mode);
end
% Main call for all applications except ChannelName / TangoName method
ErrorFlag = local_setpv(AO, Field, NewSP, DeviceList, WaitFlag);
%%%%%%%%%%%%%%%%
% End of setpv %
%%%%%%%%%%%%%%%%
return
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Main Function for Setting Data using the Accelerator Object  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function ErrorFlag = local_setpv(AO, Field, NewSP, DeviceList, WaitFlag)
%  INPUTS
%  1. AO - the ACCELERATOR_OBJECT structure for the called family
%  2. Field - 'Monitor' or 'Setpoint'
%  3. NewSP - setpoint values
%  4. DeviceList - Device list
%
%  OUTPUTS
%  1. ErrorFlag - 0 if OK, else 1
%
%  NOTES
%  1. AO comes directly from the main AcceleratorObject family
%  2. Field is which field to use
%  3. DeviceList is which device list to use
%  4. AO.DeviceList is the entire device list
%
%  Note: local_setpv can not be used for channel names
TimeOutPeriodOnWaitFlag = 10;  % Seconds of monitor not changing
ErrorFlag = 0;
% Don't set NaN's for now???
iNaN = find(isnan(NewSP));
if ~isempty(iNaN)
    NewSP(iNaN,:) = [];
    DeviceList(iNaN,:) = [];
end
% Check for empty device list
if isempty(DeviceList)
    AM = [];
    %fprintf('   WARNING:  No devices to get for Family %s\n', AO.FamilyName));
    return;
end
% Find the index for where the desired data is in the total device list
DeviceListTotal = AO.DeviceList;
[DeviceIndex, iNotFound] = findrowindex(DeviceList, DeviceListTotal);
if length(iNotFound) > 0
    % Device not found
    for i = 1:length(iNotFound)
        fprintf('   No devices to get for Family %s(%d,%d)\n', AO.FamilyName, DeviceList(i,1), DeviceList(i,2));
    end
    error(sprintf('%d Devices not found', length(iNotFound)));
end
% If Field is not found in the AO, it is unclear what to do next.
% I could error here, but it's convenient to try to set
% EPICS subfields or other simulator fields at this point.
if ~isfield(AO, Field)
    % Try to check it online or simulator
    if isfield(AO, 'Setpoint')
        Mode = getfamilydata(AO.FamilyName, 'Setpoint', 'Mode');
    elseif isfield(AO, 'Monitor')
        Mode = getfamilydata(AO.FamilyName, 'Monitor', 'Mode');
    else
        Mode = '';
    end
    if strcmpi(Mode,'Simulator') || strcmpi(Mode,'Model')
        ErrorFlag = setpvmodel(AO.FamilyName, Field, NewSP, DeviceList, 'Physics');
        return
    end
    % Try changing the suffix of the Monitor or Setpoint field
    if isfield(AO, 'Setpoint')
        Tango = family2tango(AO, 'Setpoint', DeviceList);
    elseif isfield(AO, 'Monitor')
        Tango = family2tango(AO, 'Monitor', DeviceList);
    else
        error(sprintf('Field %s not found for Family %s', Field, AO.FamilyName));
    end
    % Get rid of repeated & blank TANGO names
    [Tango, i] = unique(Tango, 'rows');
    if size(NewSP,1) ~= 1
        NewSP = NewSP(i,:);
    end
    if isempty(deblank(Tango(1,:)))
        Tango(1,:) = [];
        if size(NewSP,1) ~= 1
            NewSP(1,:) = [];
        end
    end
    if any(strcmpi(getfamilydata('Machine'),{'spear3','spear'}))
        % Change the last ':' Field
        %i = findstr(Channel(1,:),':');
        %if ~isempty(i)
        %    Channel(:,i:end) = [];
        %end
        %ChannelNew = strcat(Channel, [':',Field]);
        % Since the location of ":" can be different in each row, loop
        ChannelNew = [];
        for j = 1:size(Channel,1)
            i = findstr(Channel(j,:),':');
            if isempty(i)
                % I'm not sure what to do if ":" is missing, I'm just add a ":"
                ChannelNew = strvcat(ChannelNew, [Channel(j,1:i), ':', Field]);
            else
                ChannelNew = strvcat(ChannelNew, [Channel(j,1:i), Field]);
            end
        end
        TangoNew = strcat(Tango, [':',Field]);
    else
        % Add a .Field
        TangoNew = strcat(Tango, ['.',Field]);
    end
    ErrorFlag = setpvonline(TangoNew, NewSP);
    if WaitFlag > 0
        sleep(WaitFlag);
    elseif WaitFlag == -2
        [N, BPMDelay] = getbpmaverages;
        BPMDelay = 2.2 * max(BPMDelay);
        if ~isempty(BPMDelay)
            sleep(BPMDelay);
        end
    elseif WaitFlag == -3
        TUNEDelay = getfamilydata('TUNEDelay');
        if ~isempty(TUNEDelay)
            sleep(TUNEDelay);
        end
    elseif WaitFlag == -4
        tmp = input('   Setpoint changed.  Hit return ready. ');
    end
    return
end
% Extract 'Mode'
if isfield(AO.(Field), 'Mode')
    Mode = AO.(Field).Mode;
else
    Mode = 'Online';
end
% Check if Online should really be special
if strcmpi(Mode, 'Online')
   if isfield(AO.(Field), 'SpecialFunctionSet')
       Mode = 'Special';
   end
end
if ~isstruct(AO.(Field))
    % If it's not a structure that just set the field
    % Hardward and physics get ignored
    setfamilydata(NewSP, AO.FamilyName, Field, DeviceList);
elseif strcmpi(Mode,'Online')
    %%%%%%%%%%
    % Online %
    %%%%%%%%%%
    % Could add N-Steps here???
    % Change to hardware units if in physics units
    if strcmpi(AO.(Field).Units, 'Physics')
        NewSP = physics2hw(AO.FamilyName, Field, NewSP, DeviceList);
    end
    if  strcmpi(AO.(Field).DataType,'scalar')
        ErrorFlag = setpvonline(AO.(Field).TangoNames(DeviceIndex,:), NewSP);
    elseif  strcmpi(AO.(Field).DataType,'vector')
        % There can only be one Tango name for DataType='Vector'
        TangName = deblank(AO.(Field).TangoNames(1,:));
        % Get the vector and only load what is requested
        FullVector = getpvonline(TangName);
        if isfield(AO.(Field), 'DataTypeIndex')
            FullVector(AO.(Field).DataTypeIndex(DeviceIndex)) = NewSP;
        else
            FullVector(DeviceIndex) = NewSP;
        end
        % Vectorized put
        ErrorFlag = setpvonline(TangName, FullVector);
    else
        % Not a scalar or vector
        error(sprintf('Unknown DataType %s for family %s.', AO.(Field).DataType, AO.FamilyName));
    end
    %%%%%%%%%%%%%%%%%%%%%%%
    % WaitFlag Processing %
    %%%%%%%%%%%%%%%%%%%%%%%
    if WaitFlag && WaitFlag~=-4
        t00 = gettime;
        [RunFlag, Delta0, Tol] = getrunflag(AO, Field, DeviceList);
        RampRate = getramprate(AO, DeviceList, 'Hardware');
        if any(Tol == 0) || isempty(Tol)
            % Tol should not be set to zero, but if it is then base time-out on percentage of SP
            % This many not be a good criterion and may need to be adjusted based on the machine!!!
            TimeoutTol = NewSP / 200;   % .5 percent
        else
            % Check if the Delta has changed by at least a few tolerances in the last TimeOutPeriodOnWaitFlag seconds
            % This many not be a good criterion and may need to be adjusted based on the machine!!!
            TimeoutTol = 5 * Tol;
            % Or base on the ramprate
            %if ~isempty(RampRate) & ~any(isnan(RampRate))
            %    RR = max(abs(RampRate));
            %    if ~isnan(RR)
            %        % Base time-out on .1 what the monitor should have changed in TimeOutPeriodOnWaitFlag seconds
            %        TimeoutTol = .1 * RR * TimeOutPeriodOnWaitFlag;
            %    end
1000             %end
1001         end
1002
1003         t0  = gettime;
1004         while any(RunFlag)
1005             % Pause a little so that the network doesn't get too thrashed
1006             sleep(.1);
1007
1008             [RunFlag, Delta, Tol] = getrunflag(AO, Field, DeviceList);
1009
1010             % Check if the Delta has changed in the last TimeOutPeriodOnWaitFlag seconds
1011             if gettime-t0 > TimeOutPeriodOnWaitFlag
1012                 x = (abs(Delta) > Tol) & (abs(abs(Delta)-abs(Delta0)) <= TimeoutTol);
1013                 if any(x)
1014                     TangoName = '';
1015                     for i = 1:length(x)
1016                         if x(i)
1017                             TangoNameNext = family2tango(AO.FamilyName,  DeviceList(i,:));
1018                             if ~strcmp(TangoName, TangoNameNext)
1019                                 if isfield(AO,'Monitor') & isfield(AO,'Setpoint')
1020                                     fprintf('   %s(%d,%d) SP-AM > Tol and the monitor does not appear to be changing.\n', AO.FamilyName,  DeviceList(i,1), DeviceList(i,2));
1021                                     SP = getsp(AO.FamilyName,  DeviceList(i,:));
1022                                     AM = getam(AO.FamilyName,  DeviceList(i,:));
1023                                     fprintf('           Setpoint = %f,  Monitor = %f,  SP-AM = %f,  getrunflag Delta = %f,  Tolerance = %f\n', SP, AM, SP-AM, Delta(i), Tol(i));
1024                                 else
1025                                     fprintf('   %s(%d,%d) timed-out waiting for run flag to change.\n', AO.FamilyName,  DeviceList(i,1), DeviceList(i,2));
1026                                 end
1027                             end
1028                             TangoName = TangoNameNext;
1029                         end
1030                     end
1031
1032                     % Decide whether or not to error on a SP-AM problem
1033                     ErrorWarningLevel = getfamilydata('ErrorWarningLevel');
1034                     if isempty(ErrorWarningLevel) || ErrorWarningLevel >= 0
1035                         error(sprintf('Time-Out:  Monitor did not appear to be changing for the last %.1f seconds.', TimeOutPeriodOnWaitFlag));
1036                     elseif ErrorWarningLevel == -1
1037                         warning('Time-Out:  Monitor did not appear to be changing for the last %.1f seconds.', TimeOutPeriodOnWaitFlag);
1038                     elseif ErrorWarningLevel == -2
1039                         try
1040                             % Make some noise
1041                             sound(cos(1:10000));
1042                         catch
1043                         end
1044                         CommandInput = questdlg(...
1045                             {'The run flag is not changing.  This is often a', ...
1046                              'Setpoint-Monitor tolerance problem.  Either manually', ...
1047                              'varify that the magnet is at the proper setpoint and', ...
1048                              ' ', ...
1049                              'Continue - recheck the run condition', ...
1050                              'Stop - issue an error and see if there is error handling', ...
1051                              'Ignore the problem and push on'}, ...
1052                             'SETPV Question', ...
1053                             'Continue', ...
1054                             'Stop', ...
1055                             'Ignore', ...
1056                             'Continue');
1057                         switch CommandInput
1058                             case 'Stop'
1059                                 error('SP-AM error in setpv.');
1060                             case 'Continue'
1061                             case 'Ignore'
1062                                 RunFlag = 0;
1063                         end
1064                     else % ErrorWarningLevel <= -3
1065                         % Do nothing
1066                         ErrorFlag = -1;
1067                     end
1068                 end
1069
1070                 % Reset Delta0 and timeout timer
1071                 Delta0 = Delta;
1072                 t0 = gettime;
1073             end
1074         end
1075
1076         % Add extra delay for continued ramping due to the size of the tolerance
1077         if isempty(Tol) && isempty(Delta0)
1078             % If Tol and Delta) are empty, then WaitFlag is probably not wanted
1079             %if WaitFlag < 0
1080             %    WaitFlag = 0;
1081             %end
1082         else
1083             % In case Tol is large, use the min of Tol and the present Delta SP-AM
1084             if any(isnan(RampRate))
1085                 % For lack of a better idea: If the RampRate is not defined, calculate what it has been doing.
1086                 iNaN = find(isnan(RampRate));
1087                 RampRate(iNaN) = abs(Delta0(iNaN) / (gettime-t00));
1088             end
1089             if isempty(RampRate)
1090                 % For lack of a better idea: If the RampRate is not defined, calculate what it has been doing.
1091                 RampRate = abs(Delta0 / (gettime-t00));
1092             end
1093             if any(RampRate == 0)
1094             else
1095                 T = min([(Tol./RampRate) abs(Delta0./RampRate)],[],2);
1096                 if ~isempty(max(T))
1097                     sleep(1.05*max(T));
1098                 end
1099             end
1100         end
1101     end
1102
1103     if WaitFlag && ~strcmpi(Mode,'Simulator')
1104         % Add a delay based on the WaitFlag
1105         if WaitFlag > 0
1106             sleep(WaitFlag);
1107         elseif WaitFlag == -2
1108             [N, BPMDelay] = getbpmaverages;
1109             BPMDelay = 2.2 * max(BPMDelay);
1110             if ~isempty(BPMDelay)
1111                 sleep(BPMDelay);
1112             end
1113         elseif WaitFlag == -3
1114             TUNEDelay = 2.2 * getfamilydata('TUNEDelay');
1115             if ~isempty(TUNEDelay)
1116                 sleep(TUNEDelay);
1117             end
1118         elseif WaitFlag == -4
1119             tmp = input('   Setpoint changed.  Hit return ready. ');
1120         end
1121     end
1122
1123
1124 elseif strcmpi(Mode,'Manual')
1125     %%%%%%%%%%%%%%%
1126     % Manual mode %
1127     %%%%%%%%%%%%%%%
1128
1129     % Change to hardware units if in physics units
1130     if strcmpi(AO.(Field).Units, 'Physics')
1131         NewSP = physics2hw(AO.FamilyName, Field, NewSP, DeviceList);
1132     end
1133
1134     % NewSP is always in hardware units at this point
1135     for i = 1:length(DeviceIndex)
1136         if strcmpi(AO.(Field).Units, 'Hardware')
1137             fprintf('   Manually set:  %s(%d,%d) = %f [%s]\n', AO.FamilyName, AO.DeviceList(DeviceIndex(i),1), AO.DeviceList(DeviceIndex(i),2), NewSP(i), AO.(Field).HWUnits);
1138         else
1139             NewSP(i) = hw2physics(AO.FamilyName, Field, NewSP(i), AO.DeviceList(DeviceIndex(i),:));
1140             fprintf('   Manually set:  %s(%d,%d) = %f [%s]\n', AO.FamilyName, AO.DeviceList(DeviceIndex(i),1), AO.DeviceList(DeviceIndex(i),2), NewSP(i), AO.(Field).PhysicsUnits);
1141         end
1142     end
1143     if length(NewSP) == 1
1144         input(sprintf('   Set device manually and hit return '));
1145     else
1146         input(sprintf('   Set these devices manually and hit return '));
1147     end
1148     fprintf('   \n');
1149
1150     %if strcmp(AO.FamilyName, 'RF')
1151     %    input(sprintf('   Manually set the RF frequency to %f [MHz] and hit return.', NewSP));
1152     %else
1153     %    for i = 1:length(DeviceIndex)
1154     %        fprintf('   Manually set:  %s(%d,%d) = %f\n', AO.FamilyName, AO.DeviceList(DeviceIndex(i),1), AO.DeviceList(DeviceIndex(i),2), NewSP(i));
1155     %    end
1156     %    input(sprintf('   Set these devices manually and hit return.'));
1157     %end
1158
1159 elseif strcmpi(Mode,'Special')
1160     %===================================
1161     % Special mode (evaluate a function)
1162     %===================================
1163
1164     % Could add N-Steps here???
1165
1166     % Change to hardware units if in physics units
1167     if strcmpi(AO.(Field).Units, 'Physics')
1168         NewSP = physics2hw(AO.FamilyName, Field, NewSP, DeviceList);
1169     end
1170
1171     if isfield(AO.(Field), 'SpecialFunctionSet')
1172         ErrorFlag = feval(AO.(Field).SpecialFunctionSet, AO.FamilyName, Field, NewSP, DeviceList, WaitFlag);
1173     else
1174         error(sprintf('No special function specified for Family %s (setpv).', AO.FamilyName));
1175     end
1176
1177 elseif strcmpi(Mode,'Simulator')
1178     %==================
1179     % AT simulator mode
1180     %==================
1181
1182     ErrorFlag = setpvmodel(AO, Field, NewSP, DeviceList, AO.(Field).Units);
1183
1184 else
1185     error(sprintf('Unknown mode % for family %s.', Mode, AO.FamilyName));
1186 end
1187
1188
1189
1190
1191 % Old Cell Input Method
1192
1193 %     if length(varargin) == 1
1194 %         % One data structure input (NewSP contained in data structure)
1195 %         % Call without WaitFlag, then set with WaitFlag
1196 %         for i = 1:length(Family)
1197 %             setpv(Family{i}, 0);
1198 %         end
1199 %
1200 %         % Then set with default WaitFlag
1201 %         for i = 1:length(Family)
1202 %             setpv(Family{i});
1203 %         end
1204 %         return
1205 %     end
1206 %
1207 %     % For (DataStructure, WaitFlag) or (ChannelName, NewSP) inputs
1208 %     if length(varargin) == 2
1209 %         if isstruc(Family)
1210 %             % Data structure input
1211 %             if iscell(Field)
1212 %                 if length(Family) ~= length(Field)
1213 %                     error('If WaitFlag is a cell array it must be the same size as DataStructure');
1214 %                 end
1215 %             end
1216 %
1217 %             % Call without WaitFlag, then set with WaitFlag
1218 %             for i = 1:length(Family)
1219 %                 setpv(Family{i}, 0);
1220 %             end
1221 %             for i = 1:length(Family)
1222 %                 if iscell(Field)
1223 %                     setpv(Family{i}, Field{i});
1224 %                 else
1225 %                     setpv(Family{i}, Field);
1226 %                 end
1227 %             end
1228 %         else
1229 %             % ChannelName input
1230 %             if iscell(Field)
1231 %                 if length(Family) ~= length(Field)
1232 %                     error('Family and NewSP must be the same size cell arrays');
1233 %                 end
1234 %             else
1235 %                 error('NewSP must be a cell array');
1236 %             end
1237 %             for i = 1:length(Family)            % call setpv recursively for each cell
1238 %                 if iscell(Field)
1239 %                     setpv(Family{i}, Field{i});
1240 %                 else
1241 %                     setpv(Family{i}, Field);
1242 %                 end
1243 %             end
1244 %         end
1245 %         return
1246 %     end
1247 %
1248 %
1249 %     % 3 or greater inputs implies a Family method
1250 %     if length(varargin) < 3
1251 %         error('Must have at least 3 inputs when using cells with families');
1252 %     end
1253 %
1254 %
1255 %     % If Field is a cell it must be the same size as Family
1256 %     if iscell(Field)
1257 %         if length(Family) ~= length(Field)
1258 %             error('If Field is a cell it must be the same size as Family');
1259 %         end
1260 %     end
1261 %
1262 %     % NewSP must a cell array equal to the length of Family
1263 %     if ~iscell(NewSP)
1264 %         error('If Family is a cell array, then NewSP must be a cell array');
1265 %     end
1266 %     if length(Family) ~= length(NewSP)
1267 %         error('Family and NewSP must be the same size cell arrays');
1268 %     end
1269 %
1270 %     if length(varargin) >= 4
1271 %         % DeviceList must a cell array equal to the length of Family
1272 %         if ~iscell(DeviceList)
1273 %             error('If Family is a cell array, then DeviceList must be a cell array');
1274 %         end
1275 %         if length(Family) ~= length(DeviceList)    % same number of DeviceLists as Families
1276 %             error('Family and DeviceList must be the same size cell arrays');
1277 %         end
1278 %     end
1279 %
1280 %     if length(varargin) >= 5
1281 %         % If WaitFlag is a cell it must be the same size as Family
1282 %         if iscell(WaitFlag)
1283 %             if length(Family) ~= length(WaitFlag)
1284 %                 error('If WaitFlag is a cell it must be the same size as Family');
1285 %             end
1286 %         end
1287 %     end
1288 %
1289 %     % First set everything without WaitFlag  (still cell array of Families)
1290 %     for i = 1:length(Family)
1291 %         if nargin >= 4
1292 %            DeviceList = family2dev(Family{i});     % Default behavior comes from family2dev
1293 %            %DeviceList = family2dev(Family{i},1);  % Good status only
1294 %             if iscell(Field)
1295 %                 setpv(Family{i}, Field{i}, NewSP{i}, DeviceList{i}, 0);
1296 %             else
1297 %                 setpv(Family{i}, Field, NewSP{i}, DeviceList{i}, 0);
1298 %             end
1299 %         else  % only 2 inputs specified (2 inputs finished above)
1300 %             if iscell(Field)
1301 %                 setpv(Family{i}, Field{i}, NewSP{i}, [], 0);
1302 %             else
1303 %                 setpv(Family{i}, Field, NewSP{i}, [], 0);
1304 %             end
1305 %         end  % end nargin >= 4
1306 %     end % end loop on Families without WaitFlag
1307 %
1308 %     % Then check for WaitFlag
1309 %     for i = 1:length(Family)
1310 %         if nargin == 3 % assumes default WaitFlag
1311 %             if iscell(Field)
1312 %                 ErrorFlag{i} = setpv(Family{i}, Field{i}, NewSP{i});
1313 %             else
1314 %                 ErrorFlag{i} = setpv(Family{i}, Field, NewSP{i});  % single entry for field
1315 %             end
1316 %         elseif nargin == 4
1317 %             if iscell(Field)
1318 %                 ErrorFlag{i} = setpv(Family{i}, Field{i}, NewSP{i}, DeviceList{i});
1319 %             else
1320 %                 ErrorFlag{i} = setpv(Family{i}, Field, NewSP{i}, DeviceList{i}); % single entry for field
1321 %             end
1322 %         else  % must be nargin == 5 because nargin == 2 complete above
1323 %             if iscell(Field)
1324 %                 if iscell(WaitFlag)
1325 %                     ErrorFlag{i} = setpv(Family{i}, Field{i}, NewSP{i}, DeviceList{i}, WaitFlag{i});
1326 %                 else
1327 %                     ErrorFlag{i} = setpv(Family{i}, Field{i}, NewSP{i}, DeviceList{i}, WaitFlag);
1328 %                 end
1329 %             else
1330 %                 if iscell(WaitFlag)
1331 %                     ErrorFlag{i} = setpv(Family{i}, Field, NewSP{i}, DeviceList{i}, WaitFlag{i});
1332 %                 else
1333 %                     ErrorFlag{i} = setpv(Family{i}, Field, NewSP{i}, DeviceList{i}, WaitFlag);
1334 %                 end
1335 %             end
1336 %         end
1337 %     end %end second loop over families with WaitFlag
1338 %     return
1339
1340