function KEMgui
%KEMgui - GUI for KEM controling. Usefull for FAM

%
% Written by Laurent S. Nadolski

%Clear previous ORBIT figure
orbfig = findobj(allchild(0),'tag','kemgui'); 

if ~isempty(orbfig), delete(orbfig); end

kmax = 2; % button number

height = 10 + kmax*30 + 30; %670;
a = figure('Color',[0.8 0.8 0.8], ...
    'Interruptible', 'on', ...   
    'HandleVisibility','off', ...
    'MenuBar','none', ...
    'Name', 'KEM gui', ...
    'NumberTitle','off', ...
    'Units','pixels', ...
    'Position',[5 70 210*4 height], ...
    'Resize','off', ...
    'Tag','kemgui');

height = height - 35;

for k = 1:kmax,
    b1(k) = uicontrol('Parent',a, ...
        'Position',[3 height-(k-1)*30 204 27], ...
        'Interruptible', 'off', ...
        'Tag','button22');
end

for k = 1:kmax,
    b2(k) = uicontrol('Parent',a, ...
        'Position',[3 + 210 height-(k-1)*30 204 27], ...
        'Interruptible', 'off', ...
        'Tag','button22');
end

for k = 1:kmax,
    b3(k) = uicontrol('Parent',a, ...
        'Position',[3 + 210*2 height-(k-1)*30 204 27], ...
        'Interruptible', 'off', ...
        'Tag','button22');
end

for k = 1:kmax,
    b4(k) = uicontrol('Parent',a, ...
        'Position',[3 + 210*3 height-(k-1)*30 204 27], ...
        'Interruptible', 'off', ...
        'Tag','button22');
end

bn = uicontrol('Parent',a, ...
        'Position',[3+310 height-(kmax)*30+5 204 27/2], ...
        'Interruptible', 'off', ...
        'Style','text', 'String', 'Interface for turn by turn measurements', 'ForegroundColor', 'r');

set(b1(1), 'Callback','switchsynchro(''Injection''); disp(''injection'');', 'String','Synchro : injection');
set(b1(2), 'Callback','switchsynchro(''KEM''); disp(''KEM'');', 'String','Synchro KEM');

set(b2(1), 'Callback','switchbpm(''Injection''); disp(''BPM: normal'')', 'String','BPM Normal');
set(b2(2), 'Callback','switchbpm(''KEM''); disp(''BPM: KEM'') ', 'String','BPM: KEM');

set(b3(1), 'Callback','soft_trigger; getdcct', 'String','Trigger Soft');
set(b3(2), 'Callback','burst_trigger; getdcct', 'String','Injection');

