Description of getattribute
Home > mml > links > tango > getattribute.m
getattribute
PURPOSE
GETATTRIBUTE - Decomposes a full attributename into device and attribute names
SYNOPSIS
function [AttributeNames, DeviceNames] = getattribute(varargin)
DESCRIPTION
GETATTRIBUTE - Decomposes a full attributename into device and attribute names
  [AttributeNames, DeviceNames] =  getattribute(varargin)
 INPUTS
 1. varargin = vector full attribute names
 OUTPUTS
 1. AttributeNames = names of the attributes
 2. DeviceNames    = names of the corresponding devices
 EXAMPLES
 1. [AttributeNames, DeviceNames] =  getattribute('ANS-C01/DG/BPM.1/X')
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
readattribute READATTRIBUTE - Reads a list of Tango attributes
setpvonline SETPVONLINE - Set value to online machine
tango_get_attribute_property TANGO_GET_ATTRIBUTE_PROPERTY - Get properties for an attribute property
tango_get_device_property TANGO_GET_DEVICE_PROPERTY - Set a device property to a given value
tango_set_attribute_property TANGO_SET_ATTRIBUTE_PROPERTY - Set an attribute property to a given value
tango_set_device_property TANGO_SET_DEVICE_PROPERTY - Set a device property to a given value
writeattribute WRITEATTRIBUTE - Writes a list of TANGO attributes
SOURCE CODE
function [AttributeNames, DeviceNames] =  getattribute(varargin)
%GETATTRIBUTE - Decomposes a full attributename into device and attribute names
%  [AttributeNames, DeviceNames] =  getattribute(varargin)
%
% INPUTS
% 1. varargin = vector full attribute names
%
% OUTPUTS
% 1. AttributeNames = names of the attributes
% 2. DeviceNames    = names of the corresponding devices
%
% EXAMPLES
% 1. [AttributeNames, DeviceNames] =  getattribute('ANS-C01/DG/BPM.1/X')
%
% Written by Laurent S. Nadolski
if (length(varargin) == 0)
  error('No TangoName provided');
end
% get list of full tango attribute names
TangoNames = varargin{:};
% Regular expression and tokens
% first parenthesis gets device names
% second parenthesis gets device names
if ischar(TangoNames)
    TangoNames = cellstr(TangoNames);
end
t = regexp(TangoNames,'(.*)/(\w*)','tokens');
taille = length(t);
a = cell(taille,2);
for k=1:taille
    a(k,:) = cellstr(t{k}{:});
end
DeviceNames    = a(:,1);
AttributeNames = a(:,2);
% separator = regexpi(cellstr(TangoNames),'/');
%
% if iscell(separator)
%    separator = cell2mat(separator);
% end
% separator = separator(:,3);
% AttributeNames = TangoNames(:,separator+1:end);
% DeviceNames    = TangoNames(:,1:separator-1);