%version for 25/02/2016

mmlroot=['/Users/ichaikov/Documents/MATLAB/MML_v1'];

%remove this file folder, since the buildin 
% function "drift.m" in this file folder is 
% conflict with the "drift.m" file in AT.
mroot=matlabroot;
%rmpath([matlabroot,'/toolbox/finance/finsupport:']);

%add path for MML (not all the files in the MML file folders)
%add subfolders of /Users/mbp_mbp_ichaikov/Documents/MATLAB/thomx-mml/mml/at
MMLPath=[...
    mmlroot,'/mml:', ...
    mmlroot,'/applications/loco:', ...
    mmlroot,'/applications/orbit:', ...
    mmlroot,'/online/tango:', ...
    mmlroot,'/mml/simulators/at:', ...
    mmlroot,'/simulators/at2.0:', ...
    mmlroot,'/online/tango:'...
    mmlroot,'/machine/THOMX/StorageRing/Lattices:', ...
    genpath([mmlroot, '/simulators/at2.0']) ...
    %'/Users/ichaikov/Documents/MATLAB/thomx-mml/mml/setorbitgui:', ...
    %'/Users/ichaikov/Documents/MATLAB/thomx-mml/mml/setorbitbumpgui:', ...
    %'/Users/ichaikov/Documents/MATLAB/thomx-mml/machine/THOMX:', ...
    %'/Users/ichaikov/Documents/MATLAB/thomx-mml/machine/THOMX/TL/Matching:', ...
    %'/Users/ichaikov/Documents/MATLAB/thomx-mml/machine/THOMX/StorageRing:', ...
    %'/Users/ichaikov/Documents/MATLAB/thomx-mml/machine/THOMX/StorageRing/Lattices:', ...
     %'/Users/ichaikov/Documents/MATLAB/thomx-mml/applications/m2html:', ...
    %'/Users/ichaikov/Documents/MATLAB/thomx-mml/applications/mmlviewer:', ...
    ];

addpath(MMLPath);

% %remove the folder with old stuff => change later
% rmpath(genpath('/Users/ichaikov/Documents/MATLAB/thomx-mml/at_v2.0/atmat/atphysics/old'));
% rmpath(genpath('/Users/ichaikov/Documents/MATLAB/thomx-mml/at_v2.0/atmat/atdemos/old'));
% %rmpath(genpath('/Users/ichaikov/Documents/MATLAB/thomx-mml/at_v2.0/atmat/pubtools'));
% 
% addpath('/Users/ichaikov/Documents/MATLAB/thomx-mml/machine/THOMX/StorageRing/Lattice_studies/ataddons')