% macro match dba test lattice beta functions and dispersion using
% quadrupoles.
clear Constr Variab;
%load('dbatest.mat','RING');
RING=lat_nano_155_229_122BPM_bxSDL01_09_11m;
%%  VARIABLES
vi=   0; % variable number for fit, initial value

% %% Tunes
vi=vi+1;
Variab{vi}=struct('PERTURBINDX',findcells(RING,'FamName','Q7'),...
    'PVALUE',0,...
    'Fam',1,...
    'LowLim',[],...
    'HighLim',[],...
    'FIELD','PolynomB',...
    'IndxInField',{{1,2}}); % the double braces {{}} are necessary in orded 
                            % to avoid the creation of multiple structures.

vi=vi+1;
Variab{vi}=struct('PERTURBINDX',findcells(RING,'FamName','Q9')...
    ,'PVALUE',0,...
    'Fam',1,...
    'LowLim',[],...
    'HighLim',[],...
    'FIELD','PolynomB',...
    'IndxInField',{{1,2}});
%% Chroma
vi=vi+1;
Variab{vi}=struct('PERTURBINDX',findcells(RING,'FamName','S7'),...
    'PVALUE',0,...
    'Fam',1,...
    'LowLim',[],...
    'HighLim',[],...
    'FIELD','PolynomB',...
    'IndxInField',{{1,3}}); % the double braces {{}} are necessary in orded 
                            % to avoid the creation of multiple structures.

vi=vi+1;
Variab{vi}=struct('PERTURBINDX',findcells(RING,'FamName','S9')...
    ,'PVALUE',0,...
    'Fam',1,...
    'LowLim',[],...
    'HighLim',[],...
    'FIELD','PolynomB',...
    'IndxInField',{{1,3}});


%%  CONSTRAINTS
c_i=0; % initialization

c_i=c_i+1;
% Tunes
Constr{c_i}=struct('Fun',@(RING)attune(RING),...
    'Min',[0.17; 0.23], ...
    'Max',[0.17; 0.23],...
    'Weight',1);

% Chroma
c_i=c_i+1;
Constr{c_i}=struct('Fun',@(RING)atchro(RING),...
    'Min',[0.0; 0.0], ...
    'Max',[0.0; 0.0],...
    'Weight',1);



%% MATCHING

% Optimization toolbox
RING_matched=atmatch(RING,Variab,Constr,10^-10,1000,'lsqnonlin',1);%
%RING_matched=atmatch(RING,Variab,Constr,10^-6,1000,'lsqnonlin',0);%

% STandard optmization (slow)
% 22 iterations
% RING_matched=atmatch(RING,Variab,Constr,10^-6,1000,'fminsearch',0);%

attune(RING_matched)
atchro(RING_matched)

%%
% initial lattice
figure;atplot(RING);% export_fig('ringdba.pdf','-transparent');
% lattice after matching
figure;atplot(RING_matched);% export_fig('ringdba_matched.pdf','-transparent');
