function RUN_HU80_MICROFOC_BUMP()
% AFFICHAGE DE LA FREQUENCE RF
getrf
% ENREGISTREMENT DE LA VALEUR DES CORRECTEURS DE LA MACHINE
hcor=getam('HCOR')
% VALEURS DES CORRECTEURS MACINE À LEUR ANCIENNE VALEUR
setsp('HCOR',hcor)
% AFFICHAGE DES NOMBRES D'ONDE
gettune
% GENERATION DU BUMP EN X
setorbitbump('BPMx',[14 1;14 2],1.0*[1;1],'HCOR',[-5 -4 -3 -2 -1 1 2 3 4 5],'FitRF')
% ENREGISTREMENT DE L'ORBITE L'ENTREFER 250 MM ET 15.5 MM
Orbit=idMeasElecBeamUnd_NoTime('HU80_MICROFOC', 0, ['/home/operateur/GrpGMI/HU80_MICROFOC/SESSION_13_09_10/BUMP_-10mm_G2500'], 0);
Orbit=idMeasElecBeamUnd_NoTime('HU80_MICROFOC', 0, ['/home/operateur/GrpGMI/HU80_MICROFOC/SESSION_13_09_10/BUMP_-10mm_G155'], 0);
end
