Description of corgui
Home > applications > orbit > corgui.m
corgui
PURPOSE
CORGUI - controls corrector manipulation and plotting for orbit program
SYNOPSIS
function corgui(action, varargin)
DESCRIPTION
 CORGUI - controls corrector manipulation and plotting for orbit program
varargout = corgui(action, varargin)
=============================================================
 INPUT
1. action among:
   PlotCor_Init
   Fract
   ApplyCorrection
   RemoveCorrection
   ApplyFit
   UpdateCors
   GetAct
   UpdateAct
   PlotAct
   PlotFit
   ClearFit
   ClearPlots
   ShowPlots
   HidePlots
   RePlot
   ylimits
   CorSelect
   CorDown
   ProcessCor
   CorBar
   UpdateCorBox
   CorBox
   Up
   CORmove
   SelectAll
   SelectNone
   ToggleCor
   ShowResp
   ShowEig
   SaveCors
   RestoreCors
   CorEdit
   ShowCORState
CROSS-REFERENCE INFORMATION
This function calls:
bpmgui function varargout = bpmgui(action, varargin)
corgui CORGUI - controls corrector manipulation and plotting for orbit program
orbgui ORBGUI -- Contains routines to set up the main orbit control panel
This function is called by:
bpmgui function varargout = bpmgui(action, varargin)
corgui CORGUI - controls corrector manipulation and plotting for orbit program
orbgui ORBGUI -- Contains routines to set up the main orbit control panel
respgui RESPGUI - Part treating of the response matrice and the correction
SOURCE CODE
function corgui(action, varargin)
% CORGUI - controls corrector manipulation and plotting for orbit program
%varargout = corgui(action, varargin)
%=============================================================
%
% INPUT
%1. action among:
%   PlotCor_Init
%   Fract
%   ApplyCorrection
%   RemoveCorrection
%   ApplyFit
%   UpdateCors
%   GetAct
%   UpdateAct
%   PlotAct
%   PlotFit
%   ClearFit
%   ClearPlots
%   ShowPlots
%   HidePlots
%   RePlot
%   ylimits
%   CorSelect
%   CorDown
%   ProcessCor
%   CorBar
%   UpdateCorBox
%   CorBox
%   Up
%   CORmove
%   SelectAll
%   SelectNone
%   ToggleCor
%   ShowResp
%   ShowEig
%   SaveCors
%   RestoreCors
%   CorEdit
%   ShowCORState
%
%
% Written by William J. Corbett
% Adapted by Laurent S. Nadolski
%globals
global COR RSP SYS
% HCORFamily = 'HCOR';
% VCORFamily = 'VCOR';
% BPMxFamily = 'BPMx';
% BPMzFamily = 'BPMz';
orbfig = findobj(0,'tag','orbfig');
plane  = SYS.plane;
switch action
    %==========================================================
    case 'PlotCor_Init'             % *** PlotCor_Init ***
        %============Replot==============================================
        %draw patches to create a "bar" plot for the correctors.
        set(SYS.ahcor,'Xlim',[0 SYS.xlimax]);
        %========================================
        %initialize for plane that IS NOT default
        %========================================
        plane     = 1 + mod(plane,2);
        SYS.plane = plane;
        xd = orbgui('GetAbscissa',SYS,'COR');  %horizontal coordinates for plotting
        COR(plane).id = 1;        %first corrector selected as default
        for ii = 1:size(COR(plane).name,1)
            c     = xd(ii);     %horizontal coordinate
            color = 'k';        %default black if not in status vector
            if ~isempty(find(COR(plane).status==ii,1)), color='y'; end  %yellow for available
            if ~isempty(find(COR(plane).ifit==ii,1)),   color='g'; end  %green for fit
            %actual corrector strength (green)
            COR(plane).hact(ii,1) = line('parent',SYS.ahcor,'XData', ...
                c,'YData',0,'Marker','diamond',...
                'MarkerFaceColor',color,'MarkerSize',6,...
                'tag', ['c' num2str(plane) '_' num2str(ii)],...   %c for corrector
                'ButtonDownFcn','corgui(''CorSelect'')');
            %vertical bar to icon
            COR(plane).hact(ii,2) = line('parent',SYS.ahcor,'XData', ...
                [c c],'YData',[0 0],'Color','b');
            %actual+fitted strength (red)
            COR(plane).hfit(ii,1) = line('parent',SYS.ahcor,'XData', ...
                c,'YData',0,'Marker','o',...
                'MarkerFaceColor','r','MarkerSize',4,...
                'tag', ['f' num2str(plane) '_' num2str(ii)],...   %f for fit
                'ButtonDownFcn','corgui(''CorSelect'')');
            %vertical bar to icon
            COR(plane).hfit(ii,2)=line('parent',SYS.ahcor,'XData', ...
                [c c],'YData',[0 0],'Color','b');
            if strcmp(color,'k')    %if status bad make single black dot
                set(COR(plane).hact(ii,1),'MarkerSize',4,'Marker','o');
                set(COR(plane).hfit(ii,1),'MarkerFaceColor','k');
            end
        end
        %========================================
        %initialize for plane that IS default
        %========================================
        plane = 1+mod(plane,2);    %return to default plane
        SYS.plane = plane;
        COR(plane).id = 1;
        xd = orbgui('GetAbscissa',SYS,'COR');  %horizontal coordinates for plotting
        for ii = 1:size(COR(plane).name,1)
            c = xd(ii);
            color = 'k';   %black if not in status vector
            if ~isempty(find(COR(plane).status==ii,1)), color='y'; end  %yellow for for available
            if ~isempty(find(COR(plane).ifit==ii,1)),   color='g'; end  %green for fit
            %actual corrector strength (green)
            COR(plane).hact(ii,1)=line('parent',SYS.ahcor,'XData', ...
                c,'YData',0,'Marker','diamond',...
                'MarkerFaceColor',color,'MarkerSize',6,...
                'tag', ['c' num2str(plane) '_' num2str(ii)],...
                'ButtonDownFcn','corgui(''CorSelect'')');
            %vertical bar to icon
            COR(plane).hact(ii,2)=line('parent',SYS.ahcor,'XData', ...
                [c c],'YData',[0 0]);
            %actual+fitted strength (red)
            COR(plane).hfit(ii,1)=line('parent',SYS.ahcor,'XData', ...
                c,'YData',0,'Marker','o',...
                'MarkerFaceColor','r','MarkerSize',4,...
                'tag', ['f' num2str(plane) '_' num2str(ii)],...
                'ButtonDownFcn','corgui(''CorSelect'')');
            %vertical bar to icon
            COR(plane).hfit(ii,2)=line('parent',SYS.ahcor,'XData', ...
                [c c],'YData',[0 0]);
            if strcmp(color,'k')    %if status bad make single black dot
                set(COR(plane).hact(ii,1),'MarkerSize',4,'Marker','o');
                set(COR(plane).hfit(ii,1),'MarkerFaceColor','k');
            end
        end
        %set limits on corrector plot
        ylim = get(SYS.ahcor,'YLim');
        %vertical bar on selected corrector
        SYS.lhcid = line('parent',SYS.ahcor,...
            'XData',[xd(COR(plane).id),xd(COR(plane).id)+0.001],...
            'YData',[ylim(1),ylim(2)],'Color','k');
        set(SYS.lhcid,'ButtonDownFcn','corgui(''CorSelect'')');
        corgui('ylimits');
        %===========================================================
    case 'Fract'                                 %*** Fract ***
        %===========================================================
        %callback of the text box used to set fraction
        h1    = SYS.fract;
        fract = str2double(get(h1,'String'));
        if isnan(fract) || ~isnumeric(fract) || ~length(fract) == 1
            % flush the bad string out of the edit; replace with current value:
            set(h1,'String',num2str(COR(plane).fract));
            disp('Warning: Invalid fraction entry.');
            orbgui('LBox','Warning: Invalid fraction entry');
            return;
        else
            COR(plane).fract = fract;
            %NOTE: fraction scalar only used at time of corrector application
            %   respgui('UpdateFit');
            %   orbgui('RefreshOrbGUI');
        end
        %===========================================================
    case 'ApplyCorrection'              %*** ApplyCorrection ***
        %===========================================================
        %Apply orbit correction
        if ~isempty(COR(plane).ifit) || RSP(plane).rfflag
            orbgui('LBox',' Apply Correction for current plane');
            corgui('ApplyFit');
        else
            orbgui('LBox',' Correction not valid for current plane');
        end
        %===========================================================
    case 'RemoveCorrection'            %*** RemoveCorrection ***
        %===========================================================
        %restore to corrector pattern prior to 'ApplyFit'
        if ~isempty(COR(plane).ifit) || RSP(plane).rfflag
            orbgui('LBox',' Removing Correction');
            if COR(plane).ifit % Corrector magnet part
                %NOTE: corrector pattern (.act) measured at time of fit in RefreshOrbGUI
                % Select good status correctors
                status = COR(plane).status;
                val    = COR(plane).rst(status);
                %restore values
                setsp(COR(plane).AOFamily,val,status,SYS.mode);
            end
            if RSP(plane).rfflag % RF part
                stepsp('RF', -SYS.drfrst, SYS.mode);
            end
            % Update gui
            bpmgui('GetAct');
            corgui('GetAct');
            orbgui('RefreshOrbGUI');
        else
            orbgui('LBox',' Correction not valid for current plane');
        end
        %===========================================================
    case 'ApplyFit'                            %*** ApplyFit ***
        %===========================================================
        %apply corrector fit pattern scaled by fract
        %NOTE: corrector pattern (.act) measured at time of fit in RefreshOrbGUI
        if ~isempty(COR(plane).ifit) % corrector magnet part
            % Actual value + fitted value
            val = COR(plane).act(COR(plane).ifit) + ...
                COR(plane).fract*COR(plane).fit;
            % Test if saturation
            istoobig = (abs(val) > COR(plane).lim(COR(plane).ifit));
            if sum(istoobig) ~= 0
                orbgui('LBox',' Warning: cannot apply correction strength too large');
                return;
            end
            %load restore field to enable corrector pattern removal
            COR(plane).rst = COR(plane).act;
            % Set new current values
            setsp(COR(plane).AOFamily,val,COR(plane).ifit,SYS.mode);
            pause(2); % pause for letting correctors reach their final value % (should be a special flag in setsp)
        end
        if RSP(plane).rfflag % Apply RF correction
            stepsp('RF',COR(plane).fract*SYS.drf, SYS.mode);
            %load restore field to enable corrector pattern removal
            SYS.drfrst = COR(plane).fract*SYS.drf;
        end
        setappdata(0,'SYS',SYS);
        bpmgui('GetAct');
        corgui('GetAct');
        orbgui('RefreshOrbGUI');
        %==========================================================
    case 'UpdateCorrs'                  % *** UpdateCorrs ***
        %==========================================================
        %callback of the 'refresh corrector' button
        %acquire corrector readbacks, plot, re-calculate fit
        corgui('UpdateAct');
        orbgui('RefreshOrbGUI');
        %==========================================================
    case 'GetAct'                              % *** GetAct ***
        %==========================================================
        %get readback corrector values from database
        %load values into full length array slots with valid status
        % H-correctors
        status             = COR(1).status;
        COR(1).act(status) = getam(COR(1).AOFamily,[],SYS.mode);
        % V-correctors
        status             = COR(2).status;
        COR(2).act(status) = getam(COR(2).AOFamily,[],SYS.mode);
        setappdata(0,'COR',COR);
        %==========================================================
    case 'UpdateAct'                  % *** UpdateAct ***
        %==========================================================
        %callback of the 'refresh corrector' button
        %acquire corrector readbacks and plot
        corgui('GetAct');
        corgui('PlotAct');
        corgui('UpdateCorBox');
        orbgui('LBox',' Refresh Corrector Setpoints');
        %==========================================================
    case 'PlotAct'                            % *** PlotAct ***
        %==========================================================
        %draw stem plot for the actual corrector values.
        %act contains real values
        %scale start patch
        ah = get(SYS.ahcor);
        set(orbfig,'currentaxes',SYS.ahcor)
        xd = orbgui('GetAbscissa',SYS,'COR');
        nstat = length(COR(plane).act);
        kk = (1:nstat)';
        colorcell = repmat({'g'},nstat,1); %green for fit
        colorcell(setdiff(kk,COR(plane).ifit))  = {'y'};  %yellow for no fit
        colorcell(setdiff(kk,COR(plane).status)) = {'k'};  %black for not available
        if strcmpi(COR(plane).units,'Physics') == 1
            fact = COR(plane).hw2physics;
        else
            fact = 1;
        end
        yd      = zeros(nstat,1);
        idx     = intersect(kk,COR(plane).status);
        yd(idx) = COR(plane).act(idx);
        yd      = yd*fact;
        set(COR(plane).hact(:,1),{'XData'},num2cell(xd),{'YData'}, ...
            num2cell(yd),{'MarkerFaceColor'},colorcell);
        set(COR(plane).hact(:,2),{'XData'},num2cell([xd xd],2), ...
            {'YData'},num2cell([0*yd yd],2));
%         for kk = 1:size(COR(plane).name,1)
%             yd    = 0.0;      %default corrector value
%             color = 'k';   %default black if not in status vector
%             if ~isempty(find(COR(plane).status == kk))
%                 color = 'y';  %yellow for available
%                 yd    = COR(plane).act(kk);
%             end
%
%             if ~isempty(COR(plane).ifit);
%                 if ~isempty(find(COR(plane).ifit == kk))
%                     color = 'g';
%                 end
%             end
%
%             if strcmpi(COR(plane).units,'Physics') == 1
%                 fact = COR(plane).hw2physics;
%             else
%                 fact = 1;
%             end
%
%             set(COR(plane).hact(kk,1),'XData',xd(kk),'YData', ...
%                 yd*fact,'MarkerFaceColor',color);
%             set(COR(plane).hact(kk,2),'XData',[xd(kk) xd(kk)], ...
%                 'YData',[0 yd*fact]);
%         end  %end loop over all correctors
        corgui('ylimits');
        %==========================================================
    case 'PlotFit'                      % *** PlotFit ***
        %==========================================================
        %draw stem plot for the total predicted corrector values after fitting
        %note:COR(plane).fit is compressed
        if isempty(COR(plane).fit)
            return
        end
        xd = orbgui('GetAbscissa',SYS,'COR');
        len = length(COR(plane).ifit);
        idx = COR(plane).ifit(1:len); %get indices
        xd  = xd(idx);
        yd  = COR(plane).act(idx) + COR(plane).fit(1:len); % new value
        if strcmpi(COR(plane).units,'Physics') == 1
            fact = COR(plane).hw2physics;
        else
            fact = 1;
        end
        yd  = yd *fact;
        set(COR(plane).hfit(idx,1),{'Xdata'}, num2cell(xd), ...
            {'YData'}, num2cell(yd));
        set(COR(plane).hfit(idx,2),{'Xdata'},num2cell([xd xd],2), ...
            {'YData'}, num2cell([0*yd yd],2));
%         for kk = 1:length(COR(plane).ifit)
%             k  = COR(plane).ifit(kk);
%             yd = COR(plane).act(k) + COR(plane).fit(kk);
%
%             if strcmpi(COR(plane).units,'Physics') ==1
%                 fact = COR(plane).hw2physics;
%             else
%                 fact = 1;
%             end
%
%             set(COR(plane).hfit(k,1),'Xdata', xd(k),'YData', yd*fact);
%             set(COR(plane).hfit(k,2),'Xdata',[xd(k) xd(k)],'YData',[0 yd*fact]);
%         end
%         corgui('ylimits');
        %==========================================================
    case 'ClearFit'                      % *** ClearFit ***
        %==========================================================
        %clear horizontal fit
        set(COR(1).hfit(:,1),'YData',0);
        set(COR(1).hfit(:,2),'YData',[0 0]);
        %clear vertical   fit
        set(COR(2).hfit(:,1),'YData',0);
        set(COR(2).hfit(:,2),'YData',[0 0]);
        %==========================================================
    case 'ClearPlots'                    % *** Clearplots ***
        %==========================================================
        corgui('ClearFit');
        %clear horizontal actuals
        set(COR(1).hact(:,1),'YData',0);
        set(COR(1).hact(:,2),'YData',[0 0]);
        %clear vertical   actuals
        set(COR(2).hact(:,1),'YData',0);
        set(COR(2).hact(:,2),'YData',[0 0]);
        %==========================================================
    case 'ShowPlots'                    % *** Showplots ***
        %==========================================================
        %hide stem plots for current plane
        set(COR(plane).hact,'Visible','On');
        set(COR(plane).hfit,'Visible','On');
        %==========================================================
    case 'HidePlots'                    % *** Hideplots ***
        %==========================================================
        %hide stem plots for current plane
        set(COR(plane).hact,'Visible','Off');
        set(COR(plane).hfit,'Visible','Off');
        %=============================================================
    case 'RePlot'                                  % *** RePlot ***
        %=============================================================
        corgui('ClearPlots');
        set(orbfig,'currentaxes',SYS.ahcor)
        corgui('PlotAct');                        %plot actual correctors
        corgui('PlotFit');                        %plot fitted correctors
        corgui('ylimits');
        corgui('CorBar');
        %=============================================================
    case 'ylimits'                             % *** ylimits ***
        %=============================================================
        %compute vertical axes limits for corrector plot
        if COR(plane).scalemode == 0
            return;  %manual mode
        end
        orbgui('AutoScaleCorrAxis');
%         mxfit = 0;
%         if ~isempty(COR(plane).ifit)
%             mxfit = max(abs(COR(plane).fit(:) + COR(plane).act(COR(plane).ifit)));
%         end
%
%         mxact = max(abs(COR(plane).act(COR(plane).status)));
%
%         ylim  = max(mxfit, mxact)*1.1;
%
%         if strcmpi(COR(plane).units,'Physics') == 1
%             fact = COR(plane).hw2physics;
%         else
%             fact = 1;
%         end
%
%         ylim = ylim*fact;
%
%         %% Saturation @ 10 um
%         if ylim < 0.01
%             ylim = 0.01;
%         end
%
%         set(SYS.ahcor,'YLim',ylim*[-1, 1]);
        %=============================================================
    case 'CorSelect'                          % *** CorSelect ***
        %=============================================================
        %used if mouse clicks anywhere in COR window
        cpa = get(SYS.ahcor,'CurrentPoint');
        pos = cpa(1); % current position
        switch SYS.xscale
            case 'meter'
                id = find(min(abs(COR(plane).s-pos)) == abs(COR(plane).s-pos));
            case 'phase'
                id = find(min(abs(COR(plane).phi-pos)) == abs(COR(plane).phi-pos));
        end
        COR(plane).id = id;
        setappdata(0,'COR',COR);
        c = COR(plane).hact(id,1);  %...get handle
        corgui('ProcessCor',id,c);
        corgui('CorBar');
        %=============================================================
    case 'CorDown'                              % *** CorDown ***
        %=============================================================
        c    = gcbo;
        ctag = get(c,'tag');
        id   = str2double(ctag(4:length(ctag))); %strip off 'c/plane_' to get the cor index
        corgui('ProcessCor',id,c);
        %=============================================================
    case 'ProcessCor'                           % *** ProcessCor ***
        %=============================================================
        %This function is activated whenever the left mouse button is pressed inside a BPM patch.
        %It sets up corfig to interpret movement of the mouse and also puts data about the
        %particular cor into the text fields.
        %identify COR handle and number
        id = varargin{1}; %corrector index 'id' comes through varargin
        c  = varargin{2}; %bpm handle 'c' comes through varargin
        %c = gcbo;
        %cortag = get(c,'tag');
        %id = str2num(cortag(2:length(cortag)));         %strip off 'c' to get the cor index
        if COR(plane).mode == 1   %Correctors in toggle mode
            first = 0;
            if isempty(COR(plane).ifit)       %no CORs chosen
                COR(plane).ifit(1) = id;
                set(c,'MarkerFaceColor','g'); %add to fit list
                first = 1;
                setappdata(0,'COR',COR);
            end
            if ~isempty(find(COR(plane).ifit == id,1)) && first == 0  %presently selected for fit
                set(c,'MarkerFaceColor','y');
                COR(plane).ifit(find(COR(plane).ifit == id)) = 0;  %set fit vector to zero
                COR(plane).ifit = COR(plane).ifit(find(COR(plane).ifit)); % compress data
%                 nfit = length(COR(plane).ifit);         %compute vector length used ???
                setappdata(0,'COR',COR);
            elseif isempty(find(COR(plane).ifit == id,1)) && ...
                    ~isempty(find(COR(plane).avail == id, 1))
                %Corrector added to OK for fit
                %elseif ~isempty(find(COR(plane).avail==id))  %corrector is available
                set(c,'MarkerFaceColor','g');
                t = COR(plane).ifit;
                t = t(find(t));       % number 1 to 56 out of 120 for instance
                t = sort([t; id]);    % add to fit list
                COR(plane).ifit = t;  % updated corrector list for fit
%                 nfit            = length(COR(plane).ifit); % used ???
                setappdata(0,'COR',COR);
            end
            orbgui('RefreshOrbGUI');
        else
            corgui('UpdateCorBox');
        end    %end toggle mode condition
        set(orbfig,'WindowButtonUpFcn','corgui(''Up'')');
        %update response matrix column plot
        if strcmpi(RSP(plane).disp(1:3), 'off')     %Response display mode
            set(SYS.lhrsp,'XData',[],'YData',[]);
        else
            bpmgui('PlotResp');                            %plot matrix column vector
        end
        %=============================================================
    case 'CorBar'                              % *** CorBar ***
        %=============================================================
        %move black line in window to indicate selection
        id   = COR(plane).id;
        ylim = get(SYS.ahcor,'YLim');
        if isempty(find(COR(plane).status == id, 1))
            yd = ylim/4;
        else
            yd = COR(plane).act(id) + ylim/4;
        end
        xd = orbgui('GetAbscissa',SYS,'COR');  %horizontal coordinates for plotting
        xd = [xd(id) xd(id) + 0.001];
        set(SYS.lhcid,'XData',xd,'YData',yd);
        %=============================================================
    case 'UpdateCorBox'                     % *** UpdateCorBox ***
        %=============================================================
        %update UpdateCorBox
        %called from orbgui(RefreshOrbGUI), corgui(UpdateCorrs),
        id = COR(plane).id;
        %put fit value in offset box and in request box
        fitindx = [];
        if ~isempty(COR(plane).ifit)
            fitindx = find(COR(plane).ifit == id);
        end
        if ~isempty(fitindx)
            offset  = COR(plane).fit(fitindx);
            request = COR(plane).act(id)+offset;
        else
            offset  = 0.0;
            request = COR(plane).act(id);
        end
        % mean val
        meanV = mean(COR(plane).act(COR(plane).status));
        % rms val
        sigma = std(COR(plane).act(COR(plane).status));
        corgui('CorBox',COR(plane).name(id,:),COR(plane).act(id),...
            COR(plane).save(id),offset,request,...
            meanV,sigma,id);
        %=============================================================
    case 'CorBox'                            % *** CorBox ***
        %=============================================================
        %called from
        %corgui('CorBox',COR(plane).name(id,:),COR(plane).act(id),...
        %                COR(plane).ref(id),id);
        corname   = SYS.corname;
        actual    = SYS.coract;
        reference = SYS.corref;
        offset    = SYS.coroffset;
        request   = SYS.correq;
        rmsval    = SYS.cormean;
        meanval   = SYS.corrms;
        name = varargin{1};
        act  = varargin{2};
        ref  = varargin{3};
        off  = varargin{4};
        req  = varargin{5};
        rms  = varargin{6};
        meanV= varargin{7};
        id   = varargin{8};
        if strcmpi(COR(plane).units,'Physics') == 1
            fact = COR(plane).hw2physics;
        else
            fact = 1;
        end
        % conversion in device list
        dev = elem2dev(COR(plane).AOFamily,id);
        set(corname,  'String',[name '  [',num2str(dev(1)),' ', ...
            num2str(dev(2)),']']);
        set(actual,   'String',num2str(act*fact,   '%6.3f'));
        set(reference,'String',num2str(ref*fact,   '%6.3f'));
        set(offset,   'String',num2str(off*fact,   '%6.3f'));
        set(meanval,  'String',num2str(meanV*fact, '%6.3f'));
        set(rmsval,   'String',num2str(rms*fact,   '%6.3f'));
        set(request,  'String',num2str(req*fact,   '%6.3f'));
        %=============================================================
    case 'Up'                                  % *** Up ***
        %=============================================================
        %once the mouse button is let up, don't respond to motion any more.
        set(orbfig,'WindowButtonMotionFcn','','WindowButtonUpFcn','');
        %=============================================================
    case 'CORmove'                      % *** CORmove ***
        %=============================================================
        %empty for now: can't drag correctors
        return;
        %=============================================================
    case 'SelectAll'                           % *** SelectAll ***
        %============================================================
        %load all available correctors into ifit field
        COR(plane).ifit = [];
        set(COR(plane).hact(COR(plane).avail,1),'MarkerFaceColor','g');
        vavail = 1:length(COR(plane).avail);
        COR(plane).ifit(vavail) = COR(plane).avail;
%         for kk = 1:length(COR(plane).avail)
%             k  = COR(plane).avail(kk);
%             h1 = COR(plane).hact(k,1);  %k,1 is the icon
%             set(h1,'MarkerFaceColor','g');
%             COR(plane).ifit(kk)=k;
%         end
        COR(plane).ifit = COR(plane).ifit(:);
        setappdata(0,'COR',COR);
        corgui('ClearFit'); %be sure to remove residual red corrector bars
        orbgui('RefreshOrbGUI');
        %=============================================================
    case 'SelectNone'                           % *** SelectNone ***
        %=============================================================
        COR(plane).ifit = [];
        COR(plane).fit  = [];
        set(COR(plane).hact(COR(plane).avail,1),'MarkerFaceColor','y');
%         for kk = 1:length(COR(plane).avail)
%             k  = COR(plane).avail(kk);
%             h1 = COR(plane).hact(k,1);  %k,1 is the icon
%             set(h1,'MarkerFaceColor','y');
%         end
        setappdata(0,'COR',COR);
        RSP(plane).nsvd   = 1;
        RSP(plane).nsvdmax = 1;
        setappdata(0,'RSP',RSP);
        orbgui('RefreshOrbGUI');
        %respgui('FitOff',num2str(plane));
        %==========================================================
    case 'ToggleCor'                              %  ToggleCor
        %==========================================================
        h1  = SYS.togglecor;
        val = get(h1,'Value');
        if val == 0                        %radio was on, push turned off
            COR(plane).mode = 0;               %'0' for display
        elseif val == 1                    %radio was off, push turned on
            COR(plane).mode = 1;               %'1' for toggle
        end
        setappdata(0,'COR',COR);
        %==========================================================
    case 'ShowResp'                       %  ShowResp
        %==========================================================
        %toggle the 'showresp' flag to display columns of response matrix
        %plotting in bpmgui('PlotResp')
        %first make sure eigenvector display is off
        val = get(SYS.showeig,'Checked');
        if strcmpi(val,'On')                        %radio on, turn off
%             RSP(plane).eig = 'off';
            setappdata(0,'RSP',RSP);
            set(SYS.lheig,'XData',[],'YData',[]);
            set(SYS.showeig,'Checked','Off');
        end
        val = get(SYS.showresp,'Checked');
        %RSP=getappdata(0,'RSP');
        if strcmpi(val,'on')                       %radio was on, push turned off
%             RSP(plane).disp = 'off';
            set(SYS.lhrsp,'XData',[],'YData',[]);
            set(SYS.showresp,'Checked','Off');
        elseif strcmpi(val,'off')                    %radio was off, push turned on
%             RSP(plane).disp = 'on';
            setappdata(0,'RSP',RSP);
            bpmgui('PlotResp');
            set(SYS.showresp,'Checked','On');
        end
        %==========================================================
    case 'ShowEig'                       %  ShowEig
        %==========================================================
        %toggle state to show eigenvectors
        %first make sure response matrix display is off
        val = get(SYS.showresp,'Checked');
        if strcmpi(val, 'On')                   %radio on, turn off
            RSP(plane).disp = 'off';
            set(SYS.lhrsp,'XData',[],'YData',[]);
            set(SYS.showresp,'Checked','Off');
        end
        val = get(SYS.showeig,'Checked');
        if strcmpi(val, 'On')                       %radio was on, push turned off
%             RSP(plane).eig = 'off';
            set(SYS.lheig,'XData',[],'YData',[]);
            set(SYS.showeig,'Checked','Off');
        elseif strcmpi(val, 'Off')                    %radio was off, push turned on
%             RSP(plane).eig = 'on';
            bpmgui('PlotEig');
            set(SYS.showeig,'Checked','On');
        end
        %===========================================================
    case 'SaveCors'                          %*** SaveCors ***
        %===========================================================
        %Save Corrector Readbacks for RESET button
        plane = varargin{1};
        % Corrector magnet part
        % Read true values for want all correctors
        val    = getsp(COR(plane).AOFamily, SYS.mode);
        status = COR(plane).status;
        COR(plane).save(status) = val;
        % Set corrector save flag
        COR(plane).saveflag = 1;
        setappdata(0,'COR',COR);
        % RF part
        SYS.rfsave = getrf(SYS.mode);
        SYS.rfsaveflag = 1;
        setappdata(0,'SYS',SYS);
        %update corrector display
        corgui('UpdateCorBox');
        orbgui('LBox',[' Corrector and RF saved for plane: ' num2str(plane)]);
        %===========================================================
    case 'RestoreCors'                    %*** RestoreCors ***
        %===========================================================
        %restore correctors to saved values
        if ~COR(plane).saveflag || ~SYS.rfsaveflag
            orbgui('LBox',[' Corrector pattern not saved for plane: ' ...
                num2str(plane)]);
            return
        end
        if COR(plane).saveflag % Corrector magnet
            %Get saved corrector values
            val    = COR(plane).save;
            status = COR(plane).status;
            % set back coorector values
            setsp(COR(plane).AOFamily, val(status), status, SYS.mode);
            orbgui('LBox',[' Corrector pattern restored for plane: ' num2str(plane)]);
        end
        if SYS.rfsaveflag % RF part
            setrf(SYS.rfsave, SYS.mode);
            orbgui('LBox','RF frequency restored ');
        end
        %% Update gui
        bpmgui('GetAct');
        corgui('GetAct');
        orbgui('RefreshOrbGUI');
%         %==============================================================
%     case 'MakeOrbitSlider'                       %  MakeOrbitSlider
%         %==============================================================
%         %figure to create bump sliders and/or write files
%
%         [screen_wide, screen_high]=screensizecm;
%         fig_start = [0.4*screen_wide 0.5*screen_high];
%         fig_size  = [0.4*screen_wide 0.25*screen_high];
%
%         h = findobj(0,'tag','makeorbitslider');
%         if ~isempty(h)
%             delete(h);
%         end
%
%         if SYS.plane==1
%             planestr = 'Horizontal ';
%         else
%             planestr = 'Vertical';
%         end
%
%         figh = figure('units','centimeters',...                %...Figure
%             'Position',[fig_start fig_size],'tag','makeorbitslider',...
%             'NumberTitle','off','Doublebuffer','on','Visible','On','Name',[planestr 'corrector bump panel'],...
%             'PaperPositionMode','Auto','MenuBar','None');
%         %------------------------------------------------------------------
%         path     = getfamilydata('Directory','BumpData');
%         filename = appendtimestamp('bump', clock);
%
%         uicontrol('Style','Text',...                           %...Header
%             'units', 'normalize', ...
%             'Position', [.02 .8 .12 .08],'ForeGroundColor','k','HorizontalAlignment','Left',...
%             'String','Header:','ToolTipString','Name of slider in gui display',...
%             'FontSize',8,'FontWeight','demi');
%
%         SYS.bumpheader=uicontrol('Style','Edit',...       %...Header
%             'units', 'normalize', ...
%             'Position', [.2 .8 .4 .08],'ForeGroundColor','k','HorizontalAlignment','Left',...
%             'String','Bump','ToolTipString','Name of slider in gui display',...
%             'FontSize',8,'FontWeight','demi');
%
%         uicontrol('Style','Text',...                           %...File Name
%             'units', 'normalize', ...
%             'Position', [.02 .7 .12 .08],'ForeGroundColor','k','HorizontalAlignment','Left',...
%             'String','File Name:','ToolTipString','Name of file written to disk',...
%             'FontSize',8,'FontWeight','demi');
%
%         SYS.bumpfile=uicontrol('Style','Edit',...      %...File Name
%             'units', 'normalize', ...
%             'Position', [.2 .7 .5 .08],'ForeGroundColor','k','HorizontalAlignment','Left',...
%             'String',filename,'ToolTipString','Name of file written to disk',...
%             'FontSize',8,'FontWeight','demi');
%
%         uicontrol('Style','Text',...                          %...Save Directory
%             'units', 'normalize', ...
%             'Position', [.02 .6 .12 .08],'ForeGroundColor','k','HorizontalAlignment','Left',...
%             'String','File Path','ToolTipString','Path of file written to disk',...
%             'FontSize',8,'FontWeight','demi');
%
%         SYS.bumppath=uicontrol('Style','Edit',...      %...Save Directory
%             'units', 'normalize', ...
%             'Position', [.2 .6 .8 .08],'ForeGroundColor','k','HorizontalAlignment','Left',...
%             'String',path,'ToolTipString','Path of file written to disk',...
%             'FontSize',8,'FontWeight','demi');
%
%         uicontrol('Style','pushbutton',...                      %...Save Command
%             'units', 'normalize', ...
%             'Position', [.2 .3 .3 .1],'ForeGroundColor','k',...
%             'String','Save file','ToolTipString','Write bump file to disk (do not launch slider)',...
%             'FontSize',8,'FontWeight','demi','Callback',['corgui(''WriteBumpFile'');', 'close(''gcf'')']);
%
%         uicontrol('Style','pushbutton',...                      %...Save & Launch Command
%             'units', 'normalize', ...
%             'Position', [.6 .3 .3 .1],'ForeGroundColor','k',...
%             'String','Save file/Launch Slider','ToolTipString','Write bump file to disk and launch slider',...
%             'FontSize',8,'FontWeight','demi','Callback','corgui(''LaunchBumpSlider'')');
%
%         uicontrol('Style','pushbutton',...                      %...cancel
%             'units', 'normalize','Position', [.8 .08 .1 .1],'ForeGroundColor','k','String','cancel',...
%             'Callback','delete(gcf)','FontSize',8,'FontWeight','demi');
%
%         %==========================================================
%     case 'WriteBumpFile'             % *** WriteBumpFile ***
%         %==========================================================
%         %call of MakeOrbitSlider
%         %call function WriteBumpFile with corrector strengths
%
%         if plane == 1
%             Family = HCORFamily;
%         elseif plane == 2
%             Family = VCORFamily;
%         end
%
%         pv    = common2tango(COR(plane).name(COR(plane).ifit,:),'Setpoint',Family);
%         delta = zeros(length(COR(plane).ifit),1);
%         for ii = 1:length(COR(plane).ifit)
%             jj          = COR(plane).ifit(ii);
%             delta(ii,1) = COR(plane).fit(ii)-COR(plane).act(jj);
%         end
%
%         header   = get(SYS.bumpheader,'String');
%         path     = get(SYS.bumppath,'String');
%         filename = get(SYS.bumpfile,'String');
%
%         if isempty(header)   header = 'slider'; end
%         if isempty(path) path = getfamilydata('Directory','BumpFiles'); end
%
%         set(SYS.bumppath,'String',path);       %update so launchbumpslider has correct path
%
%         if isempty(filename) filename = appendtimestamp('bump', clock);
%             if isempty(findstr(filename,'.m')) filename = [filename '.m']; end
%             set(SYS.bumpfile,'String',filename);   %update so launchbumpslider has correct filename
%         end
%
%         writebumpfile(pv,delta,header,path,filename);
%         orbgui('LBox',[' Bump File Created: ', filename]);
%
%         %==========================================================
%     case 'LaunchBumpSlider'             % *** LaunchBumpSlider ***
%         %==========================================================
%         %call of MakeOrbitSlider 'Save and Launch
%         %call function SingleSlider with corrector strengths
%
%         corgui('WriteBumpFile');    %first write file
%
%         header=  get(SYS.bumpheader,'String');
%         path=    get(SYS.bumppath,'String');
%         filename=get(SYS.bumpfile,'String');
%
%         if isempty(header)   header='slider'; end
%         if isempty(path)     path=getfamilydata('Directory','BumpFiles'); end
%         if isempty(filename) filename=appendtimestamp('bump', clock); end
%
%         setappdata(0,'SliderIndex',1);
%         setappdata(0,'SliderFigHandle',gcf);
%
%         singleslider(path,filename);
        %==========================================================
    case 'CorEdit'                                %...CorEdit
        %==========================================================
        %The callback of the single corrector edit box (not implemented)
        %
        h1 = SYS.corname;
        if ~isempty(get(h1,'String'))
            set(SYS.coredit,'String',num2str(0.0));
            return
        end
        %===========================================================
    case 'ShowCORState'              %*** ShowCORState ***
        %===========================================================
        % Show =corrector settings
1000         len = size(COR(plane).name,1);
1001         tavail  = zeros(len,1);
1002         tfit    = zeros(len,1);
1003         tifit   = zeros(len,1);
1004         tstatus = zeros(len,1);
1005
1006         idx = intersect(COR(plane).avail,1:len);
1007         tavail(idx) = idx;
1008         idx = intersect(COR(plane).ifit,1:len);
1009         tifit(idx) = idx;
1010         tfit(idx) = COR(plane).fit;
1011         idx = intersect(COR(plane).status,1:len);
1012         tstatus(idx) = idx;
1013
1014 %         findx=1;
1015 %         for ind=1:length(COR(plane).name)
1016 %             if ~isempty(find(COR(plane).avail==ind)) tavail(ind)=ind;  end
1017 %             if ~isempty(find(COR(plane).ifit==ind))
1018 %                 tifit(ind)=ind;
1019 %                 tfit(ind)=COR(plane).fit(findx);
1020 %                 findx=findx+1;
1021 %             end
1022 %             if ~isempty(find(COR(plane).status==ind)) tstatus(ind)=ind;  end
1023 %         end
1024
1025   %%% BUILD UP CELL TO DISPLAY
1026         ivec = (1:len)';
1027         Strcell = cell(8,len);
1028         Strcell(1,:) = num2cell(ivec);
1029         Strcell(2,:) = cellstr(COR(plane).name(ivec,:))';
1030         Strcell(3:end,:) = num2cell([tstatus(ivec),tavail(ivec),tifit(ivec), ...
1031             COR(plane).act(ivec),tfit(ivec),COR(plane).wt(ivec) ])';
1032
1033         %% Speed issue
1034         %  see bpmgui('ShowBPMState') for more details
1035
1036         filename = [SYS.localdata 'cordata.txt'];
1037         fid = fopen(filename,'w');
1038         fprintf(fid,'%s\n','index   name     stat  avail ifit      act        fit       weight');
1039         fprintf(fid,'%3d %10s %5d %5d %5d %10.3f %10.3f %10.3f\n', Strcell{:});
1040         fclose(fid)
1041 %         edit 'cordata.txt'
1042         system(['nedit ', filename, ' &']); %much faster
1043
1044 %         fprintf('%s\n','index name       stat  avail ifit      act        fit       weight');
1045 %         for ind=1:length(COR(plane).name)
1046 %             fprintf('%3d %10s %5d %5d %5d %10.3f %10.3f %10.3f\n',...
1047 %                 ind, COR(plane).name(ind,:),...
1048 %                 tstatus(ind),tavail(ind),tifit(ind),COR(plane).act(ind),tfit(ind),COR(plane).wt(ind));
1049 %         end
1050
1051 %         %==========================================================
1052 %     case 'MeasureXResp'                  % *** MeasureXResp ***
1053 %         %==========================================================
1054 %         %callback of the 'Measure X-Response' menu selection
1055 %
1056 %         orbitfiginvisible;
1057 %
1058 %         disp('Orbit gui visibility turned off while response matrix measurement in progress');
1059 %         disp(['To re-activate, issue command :  ', 'OrbitFigVisible']);
1060 %
1061 %         % acquire initial orbit
1062 %         disp('   Acquiring initial orbit')
1063 %         Xorb                = getx('struct');
1064 %         Xorb.DataDescriptor = 'ResponseMatrixReference';
1065 %         Zorb                = getz('struct');
1066 %         Zorb.DataDescriptor = 'ResponseMatrixReference';
1067 %
1068 %         %acquire machine configuration
1069 %         disp('   Acquiring machine configuration')
1070 %         machineconfig = getmachineconfig;
1071 %
1072 %         ad = getad;
1073 %
1074 %         xbpms = BPM(1).status;
1075 %         ybpms = BPM(2).status;
1076 %
1077 %         xcors = COR(1).status;
1078 %         xkick = COR(1).ebpm(xcors);
1079 %
1080 %         WaitFlag   = ad.BPMDelay;
1081 %         ExtraDelay = 0;
1082 %
1083 %         disp('   *** Begin measuring horizontal response matrix ***');
1084 %         mat = measrespmat({BPMxFamily,BPMzFamily},{xbpms,ybpms},HCORFamily, ...
1085 %             xcors,xkick,'bipolar',WaitFlag,ExtraDelay,'struct');
1086 %
1087 %         % Make a response matrix array
1088 %         Rmat(1,1) = mat{1};  % xx
1089 %         Rmat(2,1) = mat{2};  % zx
1090 %
1091 %         %load xx data
1092 %         Rmat(1,1).NaNData              = zeros(size(getlist(BPMxFamily,0),1), ...
1093 %             size(getlist(HCORFamily,0),1));
1094 %         Rmat(1,1).NaNData(:)           = deal(NaN);
1095 %         Rmat(1,1).NaNData(xbpms,xcors) = mat{1}.Data;     %Kick x, look x
1096 %         %
1097 %         %load zx data
1098 %         Rmat(2,1).NaNData              = zeros(size(getlist(BPMzFamily,0),1), ...
1099 %             size(getlist(HCORFamily,0),1));
1100 %         Rmat(2,1).NaNData(:)           = deal(NaN);
1101 %         Rmat(2,1).NaNData(ybpms,xcors) = mat{2}.Data;     %Kick x, look z
1102 %
1103 %         for ii = 1:2
1104 %             Rmat(ii,1).X              = Xorb;
1105 %             Rmat(ii,1).Y              = Zorb;
1106 %             Rmat(ii,1).MachineConfig  = machineconfig;
1107 %         end
1108 %         Rmat(1,1).Monitor.DataDescriptor  = 'Horizontal Orbit';
1109 %         Rmat(1,1).Actuator.DataDescriptor = 'Horizontal Correctors';
1110 %         Rmat(2,1).Monitor.DataDescriptor  = 'Vertical Orbit';
1111 %         Rmat(2,1).Actuator.DataDescriptor = 'Horizontal Correctors';
1112 %
1113 %         RSP(1) = response2rsp(Rmat(1,1),RSP(1),1);
1114 %
1115 %         orbitfigvisible;
1116 %
1117 %         BPM = SortBPMs(BPM,RSP);
1118 %         COR = SortCORs(COR,RSP);
1119 %         orbgui('RefreshOrbGUI');
1120 %
1121 %         orbgui('LBox',' Finished measuring horizontal eBPM response matrix');
1122 %
1123 %         %==========================================================
1124 %     case 'MeasureZResp'                  % *** MeasureZResp ***
1125 %         %==========================================================
1126 %
1127 %         %callback of the 'Measure Z-Response' menu selection
1128 %
1129 %         orbitfiginvisible;
1130 %
1131 %         disp('Orbit gui visibility turned off while response matrix measurement in progress');
1132 %         disp(['To re-activate, issue command :  ', 'OrbitFigVisible']);
1133 %
1134 %         % acquire initial orbit
1135 %         disp('   Acquiring initial orbit')
1136 %         Xorb                = getx('struct');
1137 %         Xorb.DataDescriptor = 'ResponseMatrixReference';
1138 %         Zorb                = getz('struct');
1139 %         Zorb.DataDescriptor = 'ResponseMatrixReference';
1140 %
1141 %         %acquire machine configuration
1142 %         disp('   Acquiring machine configuration')
1143 %         machineconfig=getmachineconfig;
1144 %
1145 %         ad = getad;
1146 %
1147 %         xbpms = BPM(1).status;
1148 %         ybpms = BPM(2).status;
1149 %
1150 %         ycors = COR(2).status;
1151 %         ykick = COR(2).ebpm(ycors);
1152 %
1153 %         WaitFlag   = 0;
1154 %         ExtraDelay = ad.BPMDelay;
1155 %
1156 %         disp('   *** Begin measuring vertical response matrix ***');
1157 %         mat = measrespmat({BPMxFamily,BPMzFamily},{xbpms,ybpms}, ...
1158 %             VCORFamily,ycors,ykick,'bipolar',WaitFlag,ExtraDelay,'struct');
1159 %
1160 %         % Make a response matrix array
1161 %         Rmat(1,2) = mat{1};  % zx
1162 %         Rmat(2,2) = mat{2};  % zz
1163 %
1164 %         %load x-y data
1165 %         Rmat(1,2).NaNData              = zeros(size(getlist(BPMzFamily,0),1), ...
1166 %             size(getlist(VCORFamily,0),1));
1167 %         Rmat(1,2).NaNData(:)           = deal(NaN);
1168 %         Rmat(1,2).NaNData(xbpms,ycors) = mat{1}.Data;     %Kick x, look z
1169 %
1170 %         %load y-y data
1171 %         Rmat(2,2).NaNData              = zeros(size(getlist(BPMxFamily,0),1), ...
1172 %             size(getlist(VCORFamily,0),1));
1173 %         Rmat(2,2).NaNData(:)           = deal(NaN);
1174 %         Rmat(2,2).NaNData(xbpms,ycors) = mat{2}.Data;     %Kick z, look z
1175 %         %
1176 %         for ii = 1:2
1177 %             Rmat(ii,2).X              = Xorb;
1178 %             Rmat(ii,2).Y              = Zorb;
1179 %             Rmat(ii,2).MachineConfig  = machineconfig;
1180 %         end
1181 %
1182 %         Rmat(1,2).Monitor.DataDescriptor  = 'Horizontal Orbit';
1183 %         Rmat(1,2).Actuator.DataDescriptor = 'Vertical Correctors';
1184 %         Rmat(2,2).Monitor.DataDescriptor  = 'Vertical Orbit';
1185 %         Rmat(2,2).Actuator.DataDescriptor = 'Vertical Correctors';
1186 %
1187 %         RSP(2) = response2rsp(Rmat(2,2),RSP(2),2);
1188 %
1189 %         orbitfigvisible;
1190 %
1191 %         BPM = SortBPMs(BPM,RSP);
1192 %         COR = SortCORs(COR,RSP);
1193 %         orbgui('RefreshOrbGUI');
1194 %
1195 %         orbgui('LBox',' Finished measuring vertical eBPM response matrix');
1196
1197         %==========================================================
1198     otherwise
1199         disp(['Warning: no CASE found in corgui: ' action]);
1200
1201 end  %end switchyard