Description of physics_synchronousphase
Home > machine > Soleil > StorageRing > physics_synchronousphase.m
physics_synchronousphase
PURPOSE
PHYSICS_SYNCHRONOUSPHASE - Compute synchronous phase
SYNOPSIS
function phis = physics_synchronousphase(eVRF,E,rho)
DESCRIPTION
  PHYSICS_SYNCHRONOUSPHASE - Compute  synchronous phase
  INPUTS
  1. eVRF - RF voltage in keV
  2. E - Energy in GeV
  3. rho - Curvature radius in meters
  OUPUTS
  1. phis - synchronous phase
  EXAMPLES
  1. physics_synchronousphase(4000,2.75,5.36)*180/pi
     is 13.65 degrees for Soleil
  See Also  physics_RFacceptance, physics_quatumlifetime,
  physics_energyloss
CROSS-REFERENCE INFORMATION
This function calls:
physics_energyloss PHYSICS_ENERGYLOSS - Computed energy loss per turn
This function is called by:
physics_bunchlength PHYSICS_bunchlength - Compute bunch length
physics_synchrotrontune PHYSICS_ENERGYLOSS - Computed synchrotron tune
SOURCE CODE
function phis = physics_synchronousphase(eVRF,E,rho)
%  PHYSICS_SYNCHRONOUSPHASE - Compute  synchronous phase
%
%  INPUTS
%  1. eVRF - RF voltage in keV
%  2. E - Energy in GeV
%  3. rho - Curvature radius in meters
%
%  OUPUTS
%  1. phis - synchronous phase
%
%  EXAMPLES
%  1. physics_synchronousphase(4000,2.75,5.36)*180/pi
%     is 13.65 degrees for Soleil
%
%  See Also  physics_RFacceptance, physics_quatumlifetime,
%  physics_energyloss
%
% Written by Laurent S. Nadolski
U0 = physics_energyloss(E,rho); % keV
phis = asin(U0./eVRF);