function res=test_imbrique()
global PRESENTCURRENT;
global SENSEOFCURRENT;
global BXSENSEOFCURRENTFORHEL;
global BXPRESENTCURRENTFORHEL;
% global APERIODIC;
% global DEBUG;
% global LISTOFCURRENTS;
% global BXLISTOFCURRENTSFORHEL;
res=-1;
delete('/home/operateur/GrpGMI/HU256_CASSIOPEE/MatlabScripts/Helicoidal/TempTests/*')
fprintf ('###### Avant init : PRESENTCURRENT : %3.0f, SENSEOFCURRENT : %1.0f, BXPRESENTCURRENTFORHEL : %3.0f, BXSENSEOFCURRENTFORHEL : %1.0f\n', PRESENTCURRENT, SENSEOFCURRENT, BXPRESENTCURRENTFORHEL, BXSENSEOFCURRENTFORHEL)
HU256_TotalCycling(15, 'inithel', 'hel', '', 0, '/home/operateur/GrpGMI/HU256_CASSIOPEE/MatlabScripts/Helicoidal/TempTests', 'i0', 1)
fprintf ('###### Après init : PRESENTCURRENT : %3.0f, SENSEOFCURRENT : %1.0f, BXPRESENTCURRENTFORHEL : %3.0f, BXSENSEOFCURRENTFORHEL : %1.0f\n', PRESENTCURRENT, SENSEOFCURRENT, BXPRESENTCURRENTFORHEL, BXSENSEOFCURRENTFORHEL)
HU256_TotalCycling(15, 'bz', 'hel', '', 0, '/home/operateur/GrpGMI/HU256_CASSIOPEE/MatlabScripts/Helicoidal/TempTests', 'i0', 1)
fprintf ('###### Après 1er cycle Bz : PRESENTCURRENT : %3.0f, SENSEOFCURRENT : %1.0f, BXPRESENTCURRENTFORHEL : %3.0f, BXSENSEOFCURRENTFORHEL : %1.0f\n', PRESENTCURRENT, SENSEOFCURRENT, BXPRESENTCURRENTFORHEL, BXSENSEOFCURRENTFORHEL)
HU256_TotalCycling(15, 'bx', 'hel', '', 0, '/home/operateur/GrpGMI/HU256_CASSIOPEE/MatlabScripts/Helicoidal/TempTests', 'i0', 1)
fprintf ('###### Après déplacement Bx : PRESENTCURRENT : %3.0f, SENSEOFCURRENT : %1.0f, BXPRESENTCURRENTFORHEL : %3.0f, BXSENSEOFCURRENTFORHEL : %1.0f\n', PRESENTCURRENT, SENSEOFCURRENT, BXPRESENTCURRENTFORHEL, BXSENSEOFCURRENTFORHEL)
HU256_TotalCycling(15, 'bz', 'hel', '', 0, '/home/operateur/GrpGMI/HU256_CASSIOPEE/MatlabScripts/Helicoidal/TempTests', 'i0', 1)
fprintf ('###### Après 2ème cycle Bz : PRESENTCURRENT : %3.0f, SENSEOFCURRENT : %1.0f, BXPRESENTCURRENTFORHEL : %3.0f, BXSENSEOFCURRENTFORHEL : %1.0f\n', PRESENTCURRENT, SENSEOFCURRENT, BXPRESENTCURRENTFORHEL, BXSENSEOFCURRENTFORHEL)
res=1;