Description of do_update
Home > machine > Soleil > common > synchro > do_update.m
do_update
PURPOSE
SYNOPSIS
function do_update
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
retour_update retour update
This function is called by:
synchro_injecteur7_rafale SYNCHRO_INJECTEUR7_RAFALE M-file for synchro_injecteur7_rafale.fig
synchro_injecteur8_rafale SYNCHRO_INJECTEUR8_RAFALE M-file for synchro_injecteur8_rafale.fig
synchro_survey SYNCHRO_SURVEY M-file for synchro_survey.fig
SOURCE CODE
function do_update
fprintf('*****Update des 16 cartes locales******\n')
r=tango_command_inout2('ANS/SY/LOCAL.SDC.1','Update');  retour_update('ANS/SY/LOCAL.SDC.1',r);
r=tango_command_inout2('LT1/SY/LOCAL.DG.1','Update');  retour_update('LT1/SY/LOCAL.DG.1',r);
r=tango_command_inout2('LIN/SY/LOCAL.SPM.1','Update');  retour_update('LIN/SY/LOCAL.SPM.1',r);
r=tango_command_inout2('BOO/SY/LOCAL.Binj.1','Update'); retour_update('BOO/SY/LOCAL.Binj.1',r);
r=tango_command_inout2('BOO/SY/LOCAL.Alim.1','Update'); retour_update('BOO/SY/LOCAL.Alim.1',r);
r=tango_command_inout2('BOO/SY/LOCAL.DG.3',  'Update'); retour_update('BOO/SY/LOCAL.DG.3',r);
r=tango_command_inout2('BOO/SY/LOCAL.Bext.1','Update'); retour_update('BOO/SY/LOCAL.Bext.1',r);
r=tango_command_inout2('ANS-C01/SY/LOCAL.Ainj.1','Update'); retour_update('ANS-C01/SY/LOCAL.Ainj.1',r);
r=tango_command_inout2('ANS-C01/SY/LOCAL.Ainj.2','Update'); retour_update('ANS-C01/SY/LOCAL.Ainj.2',r);
r=tango_command_inout2('ANS-C02/SY/LOCAL.DG.1',  'Update'); retour_update('ANS-C02/SY/LOCAL.DG.1',r);
r=tango_command_inout2('ANS-C04/SY/LOCAL.DG.1',  'Update'); retour_update('ANS-C04/SY/LOCAL.DG.1',r);
r=tango_command_inout2('ANS-C06/SY/LOCAL.DG.1',  'Update'); retour_update('ANS-C06/SY/LOCAL.DG.1',r);
r=tango_command_inout2('ANS-C08/SY/LOCAL.DG.1',  'Update'); retour_update('ANS-C08/SY/LOCAL.DG.1',r);
r=tango_command_inout2('ANS-C10/SY/LOCAL.DG.1',  'Update'); retour_update('ANS-C10/SY/LOCAL.DG.1',r);
r=tango_command_inout2('ANS-C12/SY/LOCAL.DG.1',  'Update'); retour_update('ANS-C12/SY/LOCAL.DG.1',r);
r=tango_command_inout2('ANS-C14/SY/LOCAL.DG.1',  'Update'); retour_update('ANS-C14/SY/LOCAL.DG.1',r);
r=tango_command_inout2('ANS-C16/SY/LOCAL.DG.1',  'Update'); retour_update('ANS-C16/SY/LOCAL.DG.1',r);
fprintf('**************************************\n')