Description of fix_quart
Home > machine > Soleil > common > synchro > fix_quart.m
fix_quart
PURPOSE
fix premier quart
SYNOPSIS
function [clk_pc,clk_soft]=fix_quart
DESCRIPTION
 fix premier quart
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
synchro_injecteur5 SYNCHRO_INJECTEUR5 M-file for synchro_injecteur5.fig
synchro_injecteur6 SYNCHRO_INJECTEUR6 M-file for synchro_injecteur6.fig
synchro_injecteur7 SYNCHRO_INJECTEUR7 M-file for synchro_injecteur7.fig
SOURCE CODE
% fix premier quart
function [clk_pc,clk_soft]=fix_quart
n=1;
temp=tango_read_attribute2('ANS/SY/CENTRAL', 'TPcStepDelay');
clk1=temp.value(n);
temp=tango_read_attribute2('ANS/SY/CENTRAL', 'TSoftStepDelay');
clk2=temp.value(n);
jump=int32([0 39 26 13]);
clk_pc  =jump +  int32(clk1);
clk_soft=jump  + int32(clk2);