Description of getcharge
Home > machine > Soleil > common > synchro > getcharge.m
getcharge
PURPOSE
calcul efficacité
SYNOPSIS
function [q1,q2,n]=getcharge(q1,q2,n)
DESCRIPTION
 calcul efficacité
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
synchro_injecteur5 SYNCHRO_INJECTEUR5 M-file for synchro_injecteur5.fig
synchro_injecteur6 SYNCHRO_INJECTEUR6 M-file for synchro_injecteur6.fig
synchro_injecteur7 SYNCHRO_INJECTEUR7 M-file for synchro_injecteur7.fig
SOURCE CODE
% calcul efficacité
function  [q1,q2,n]=getcharge(q1,q2,n)
temp=tango_read_attribute2('LT1/DG/MC','qIct2');        lt1charge=temp.value;
temp=tango_read_attribute2('BOO-C01/DG/DCCT','qExt');   boocharge=-temp.value;
q1=q1+lt1charge ;
q2=q2+(boocharge+0.09);
n=n+1;