Description of retour_update
Home > machine > Soleil > common > synchro > retour_update.m
retour_update
PURPOSE
retour update
SYNOPSIS
function retour_update(carte,r)
DESCRIPTION
 retour update
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
synchro_injecteur5 SYNCHRO_INJECTEUR5 M-file for synchro_injecteur5.fig
synchro_injecteur6 SYNCHRO_INJECTEUR6 M-file for synchro_injecteur6.fig
synchro_injecteur7 SYNCHRO_INJECTEUR7 M-file for synchro_injecteur7.fig
synchro_survey SYNCHRO_SURVEY M-file for synchro_survey.fig
SOURCE CODE
% retour update
function retour_update(carte,r)
if     (r==0)
    fprintf('Carte %s = OK\n',carte)
elseif (r==-1)
    fprintf('Carte %s = Probleme\n',carte)
end
pause(0.5)