Description of start_soft
Home > machine > Soleil > common > synchro > start_soft.m
start_soft
PURPOSE
test 3Hz
SYNOPSIS
function start_soft
DESCRIPTION
 test 3Hz
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
synchro_injecteur5 SYNCHRO_INJECTEUR5 M-file for synchro_injecteur5.fig
synchro_injecteur6 SYNCHRO_INJECTEUR6 M-file for synchro_injecteur6.fig
synchro_injecteur7 SYNCHRO_INJECTEUR7 M-file for synchro_injecteur7.fig
SOURCE CODE
% test 3Hz
function start_soft
% Déclenche dans l'ordre les elements pulsés et le linac
    tango_command_inout2('BOO/SY/LOCAL.Binj.1',  'Update');
    tango_command_inout2('BOO/SY/LOCAL.Bext.1',  'Update');
    tango_command_inout2('ANS-C01/SY/LOCAL.Ainj.1', 'Update');
    tango_command_inout2('ANS-C01/SY/LOCAL.Ainj.2',  'Update');
display('Soft started')