Description of step
Home > machine > Soleil > common > synchro > step.m
step
PURPOSE
reglage delta tune à 110 MeV
SYNOPSIS
This is a script file.
DESCRIPTION
  reglage delta tune à 110 MeV
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
synchro_injecteur1 SYNCHRO_INJECTEUR1 M-file for synchro_injecteur1.fig
synchro_injecteur2 SYNCHRO_INJECTEUR2 M-file for synchro_injecteur2.fig
synchro_injecteur3 SYNCHRO_INJECTEUR3 M-file for synchro_injecteur3.fig
synchro_injecteur4 SYNCHRO_INJECTEUR4 M-file for synchro_injecteur4.fig
synchro_injecteur5 SYNCHRO_INJECTEUR5 M-file for synchro_injecteur5.fig
synchro_injecteur6 SYNCHRO_INJECTEUR6 M-file for synchro_injecteur6.fig
synchro_injecteur7 SYNCHRO_INJECTEUR7 M-file for synchro_injecteur7.fig
SOURCE CODE
%  reglage delta tune à 110 MeV
getam('QD')
%stepsp('QF', kqp(1));
%stepsp('QD', kqp(2));