Description of stop_3Hz
Home > machine > Soleil > common > synchro > stop_3Hz.m
stop_3Hz
PURPOSE
test 3Hz
SYNOPSIS
function stop_3Hz
DESCRIPTION
 test 3Hz
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
synchro_injecteur5 SYNCHRO_INJECTEUR5 M-file for synchro_injecteur5.fig
synchro_injecteur6 SYNCHRO_INJECTEUR6 M-file for synchro_injecteur6.fig
synchro_injecteur7 SYNCHRO_INJECTEUR7 M-file for synchro_injecteur7.fig
SOURCE CODE
% test 3Hz
function stop_3Hz
% Stop dans l'ordre le linac et les elements pulsés
   %tango_command_inout2('LT1/SY/LOCAL.DG.1',  'Reset');
   tango_write_attribute2('LIN/SY/LOCAL.LPM.1', 'lpmEvent',int32(0));
   tango_write_attribute2('LIN/SY/LOCAL.SPM.1', 'spmLinacEvent',int16(0));
   tango_command_inout2('ANS-C01/SY/LOCAL.Ainj.1', 'Reset');
   tango_command_inout2('ANS-C01/SY/LOCAL.Ainj.2',  'Reset');
   tango_command_inout2('BOO/SY/LOCAL.Bext.1',  'Reset');
   tango_command_inout2('BOO/SY/LOCAL.Binj.1',  'Reset');
display('3Hz stopped')